### PR TITLE
[Snackbar] API to set `accessibilityHint`.

### LINKED ISSUE #4923: [Snackbar] Snackbar messages should have an accessibilityHint
Clients have no way to set the `accessibilityHint` of the Snackbar's message (the title label). The default `accessibilityHint`, "Double-tap to dismiss", should not be used since the gesture may be incorrect.

## Reproduction steps
In an MDCSnackbarMessage or MDCSnackbarMessageView, attempt to set an `accessibilityHint` value for the message.

## Expected behavior
MDCSnackbarMessageView uses its `accessibilityHint` for the `accessibilityHint` of its label, similar to how it uses `accessibilityLabel`.

## Actual behavior
In internal builds, the Snackbar message has no accessibility hint and there is no way to assign one.

## Platform (please complete the following information)
iPhone 4S/iOS 9.3.5

## Additional context
Internal build (development build via Xcode).

### PR DESCRIPTION
**Pull request by romoore**
Clients should be able to set/override the `accessibilityHint` value for
the Snackbar message label. There is already an API to set the
`accessibilityLabel`, but nothing for the hint.

Closes #4923

### CODE REVIEW

File: components/Snackbar/src/MDCSnackbarMessageView.m [hunk 1]
```diff
@@ -349,17 +349,20 @@ - (instancetype)initWithMessage:(MDCSnackbarMessage *)message
...
+    // so we'll make sure the label is treated like a button.
     _label.accessibilityTraits = UIAccessibilityTraitButton;
     _label.accessibilityIdentifier = MDCSnackbarMessageTitleAutomationIdentifier;
     _label.accessibilityHint = accessibilityHint;
 
-    // If an accessibility label was set on the message model object, use that instead of the text
-    // in the label.
+    // If an accessibility label or hint was set on the message model object, use that instead of
+    // the text in the label or the default hint.
     if ([message.accessibilityLabel length]) {
```
Comment (yarneo) [inline components/Snackbar/src/MDCSnackbarMessageView.m:360]: do we want to be more explicit about the actual number? i.e., > 0

File: components/Snackbar/src/MDCSnackbarMessageView.m [hunk 2]
```diff
@@ -349,17 +349,20 @@ - (instancetype)initWithMessage:(MDCSnackbarMessage *)message
...
       _label.accessibilityLabel = message.accessibilityLabel;
     }
+    if (message.accessibilityHint.length) {
```
Comment (yarneo) [inline components/Snackbar/src/MDCSnackbarMessageView.m:363]: same here

File: components/Snackbar/src/MDCSnackbarMessageView.m (hunk 1 above)
Comment (romoore) [reply components/Snackbar/src/MDCSnackbarMessageView.m:360]: [`length` is an NSUInteger](https://developer.apple.com/documentation/foundation/nsstring/1414212-length?language=objc), so I don't think it's ever anything other than 0 or the actual length. In our ObjC code, I think we do a lot of conditional checking for nil by implicit casting to a `BOOL` and this is very similar. If you think it's important, I can change it but I was keeping with the file's approach and trying to minimize changes.

Comment (yarneo) [reply components/Snackbar/src/MDCSnackbarMessageView.m:360]: by doing some quick searches it looks like we've been inconsistent with the way we check for `count`, but not for `length`, so i'm leaving this as you see fit. This would be a good coding style question though.

**Review by yarneo — APPROVED** [review]
