### PR TITLE
[List] Use UICollectionView as environment in List snapshot test.

### LINKED ISSUE #7487: List's layout is broken in its snapshot test.
List's layout is broken in its snapshot test.

### PR DESCRIPTION
**Pull request by fluxminds**
closes https://github.com/material-components/material-components-ios/issues/7487.

In the old List snapshot test, the cell didn't auto-size because it was initialized with a fixed size. The self sizing cell should work in a collection view environment. This PR fixes this issue and updated the golden image to reflect the test result.

### CODE REVIEW

File: components/List/tests/snapshot/MDCSelfSizingStereoCellSnapshotTests.m [hunk 1]
```diff
@@ -109,78 +124,112 @@ - (void)generateSnapshotWithContentSizeCategoryAndNotificationPost:
...
+                                                forIndexPath:indexPath];
+  // Temporarily add dequeuedCell as a subview of collectionView
+  // to inherit traitCollection. The dequeuedCell will be removed
+  // from parent at the end of this method.
+  [self.collectionView addSubview:dequeuedCell];
+  MDCSelfSizingStereoCell *cell = self.arrayOfCells[indexPath.item];
+
+  // Draw border to distinguish cell from the collection view.
+  dequeuedCell.layer.borderColor = UIColor.blackColor.CGColor;
+  dequeuedCell.layer.borderWidth = 1;
```
Comment (jverkoey) [inline components/List/tests/snapshot/MDCSelfSizingStereoCellSnapshotTests.m]: Rather than use a border (which might affect aspects of the cell rendering in the future), can we give the collection view background a distinct color?

Comment (fluxminds) [reply components/List/tests/snapshot/MDCSelfSizingStereoCellSnapshotTests.m]: Addressed in 2b20b083810b2ec36477e4820fffc48341ac0235. It uses grey color as backgroundColor now.

Comment (jverkoey) [reply components/List/tests/snapshot/MDCSelfSizingStereoCellSnapshotTests.m]: Ahh, can we change the collection view's background color so that the cell looks more close to what a cell would typically look like? We care less about the collection view's background color for the purpose of these tests.

Comment (fluxminds) [reply components/List/tests/snapshot/MDCSelfSizingStereoCellSnapshotTests.m]: Oh. sorry. I misunderstood it. Addressed in bfe6d57a772e264c20ac342fa6c5dd81d78618ae

**Review by jverkoey — APPROVED** [review]

File: components/List/tests/snapshot/MDCSelfSizingStereoCellSnapshotTests.m [hunk 2]
```diff
@@ -109,78 +124,111 @@ - (void)generateSnapshotWithContentSizeCategoryAndNotificationPost:
...
+
+- (UICollectionViewCell *)collectionView:(UICollectionView *)collectionView
+                  cellForItemAtIndexPath:(NSIndexPath *)indexPath {
+  MDCSelfSizingStereoCell *dequeuedCell =
+      [collectionView dequeueReusableCellWithReuseIdentifier:kSelfSizingStereoCellIdentifier
+                                                forIndexPath:indexPath];
+  // Temporarily add dequeuedCell as a subview of collectionView
+  // to inherit traitCollection. The dequeuedCell will be removed
+  // from parent at the end of this method.
+  [self.collectionView addSubview:dequeuedCell];
```
Comment (fluxminds) [inline components/List/tests/snapshot/MDCSelfSizingStereoCellSnapshotTests.m:218]: @andrewoverton is going to open an issue to fix it inside MDCSelfSizingStereoCell by adding support for `traitCollectionDidChange:`:)

File: components/List/tests/snapshot/MDCSelfSizingStereoCellSnapshotTests.m [hunk 3]
```diff
@@ -109,78 +124,111 @@ - (void)generateSnapshotWithContentSizeCategoryAndNotificationPost:
...
+  // Change backgroundColor to distinguish cell from the collection view.
+  dequeuedCell.backgroundColor = UIColor.whiteColor;
+  dequeuedCell.titleLabel.text = cell.titleLabel.text;
+  dequeuedCell.titleLabel.font = cell.titleLabel.font;
+  dequeuedCell.detailLabel.text = cell.detailLabel.text;
+  dequeuedCell.detailLabel.font = cell.detailLabel.font;
+  dequeuedCell.leadingImageView.image = cell.leadingImageView.image;
+  dequeuedCell.trailingImageView.image = cell.trailingImageView.image;
+  dequeuedCell.mdc_adjustsFontForContentSizeCategory = cell.mdc_adjustsFontForContentSizeCategory;
+  [dequeuedCell removeFromSuperview];
```
Comment (andrewoverton) [inline components/List/tests/snapshot/MDCSelfSizingStereoCellSnapshotTests.m:230]: If MDCSelfSizingStereoCell implemented `-traitCollectionDidChange:` to call `-adjustFontsForDynamicType` similar to how `-contentSizeCategoryDidChange:` does it then we wouldn't have to do this roundabout adding and removing of subviews. I think that might be an improvement. It would result in the test code more closely resembling app code. Right now this "cellForItemAt" implementation is sort of unusual. But this is also fine.
