### PR TITLE
[BottomNavigation] Lays out the bar when titleVisibility is changed

### LINKED ISSUE #6151: [BottomNavigation] Title visibility changes don't happen immediately
When bottomNavigation.titleVisibility is set for an already-displayed MDCBottomNavigationBar, there is no visible change until a tab is selected.

## Reproduction steps

1. Make an app with an MDCBottomNavigationBar.
2. Put a button in your app that toggles bottomNavigation.titleVisibility between .always and .never.

## Expected behavior

When the toggling button is tapped, the title immediately becomes visible or invisible.

## Actual behavior

When the toggling button is tapped, nothing visible happens. The next time a tab is tapped, the title visibility change happens.

This is particularly egregious when switching visibility on tab selection. You can end up with the title and the image both centered, and thus on top of each other.

## Platform

 - Device: Simulated iPhone 5s
 - OS: iOS 12.1

---
#### Internal data
- Associated internal bug: [b/122264214](http://b/122264214)

### PR DESCRIPTION
**Pull request by Ruberik**
Closes #6151.

### CODE REVIEW

**Comment by Ruberik** [comment]
FYI, I just updated this change so that the demo is in its own file, instead of in BottomNavigationTypicalUseExample.

File: components/BottomNavigation/src/private/MDCBottomNavigationItemView.m [hunk 1]
```diff
@@ -383,6 +383,7 @@ - (void)setTitle:(NSString *)title {
 -(void)setTitleVisibility:(MDCBottomNavigationBarTitleVisibility)titleVisibility {
   _titleVisibility = titleVisibility;
   [self updateLabelVisibility];
+  [self centerLayoutAnimated:YES];
```
Comment (romoore) [inline components/BottomNavigation/src/private/MDCBottomNavigationItemView.m]: Does it not work to call `setNeedsLayout` here instead so any layout related to visibility can be performed in a standard UIKit layout pass?

**Review by romoore — CHANGES_REQUESTED** [review]
Thanks for the PR! Is there a unit test that could be added to test this condition? If not, is there a small snippet that could be turned into a snapshot test?  Perhaps changing the bounds/frame while the titles are not visible?

It would be great to find the code path that causes this bug and make sure we've gotten it squashed.

File: components/BottomNavigation/src/private/MDCBottomNavigationItemView.m (hunk 1 above)
Comment (Ruberik) [reply components/BottomNavigation/src/private/MDCBottomNavigationItemView.m]: Yes, that's better. I'm actually going to move that into updateLabelVisibility, since that seems like a better place for that to live.

Comment (romoore) [reply components/BottomNavigation/src/private/MDCBottomNavigationItemView.m]: Sounds good! 👍

**Comment by Ruberik** [comment]
@romoore Test added! I'll consider this a helpful introduction to Objective-C; all the hair will grow back.

**Comment by Ruberik** [comment]
BTW, while I have your attention on this test file, does testSetSelectedItemTintColorUpdatesInkColor look right to you? It has the same check for item1 and item2, even though one is selected, the other isn't, and the point of the test is to make sure selection changes something.

**Comment by romoore** [comment]
Hi @Ruberik . That test changes the `selectedItemTintColor` on both a selected and unselected item. It then confirms that both have changed.  Since how the Ripple (here called "ink") color's actual value is documented publicly, the test doesn't make any assumptions about what the new color should be - only that it isn't the original color.  The reason for that test (and the related fix in https://github.com/material-components/material-components-ios/pull/4950 was to fix a bug in the implementation and update how Ripple color is applied to Bottom Navigation items.

I could certainly see an improvement being made where we assert that both items have the same (changed) color. I've opened https://github.com/material-components/material-components-ios/pull/6190 to add that check.

Was there something else in the test that you think could be improved?

File: components/BottomNavigation/examples/BottomNavigationTitleVisibilityChangeExample.swift [hunk 2]
```diff
@@ -0,0 +1,117 @@
...
+                                  y: view.bounds.height / 2 - size.height / 2,
+                                  width: size.width,
+                                  height: size.height)
+    instructionLabel.frame = instructionFrame
+  }
+  
+  override func viewWillLayoutSubviews() {
+    super.viewWillLayoutSubviews()
+    layoutBottomNavBar()
+    addInstructionLabel()
```
Comment (romoore) [inline components/BottomNavigation/examples/BottomNavigationTitleVisibilityChangeExample.swift:94]: I may be mistaken, but this looks like it creates a new UILabel every time the view is resized or rotated?   Did you mean to put the call to `addInstructionLabel()` in `viewDidLoad`?

File: components/BottomNavigation/examples/BottomNavigationTitleVisibilityChangeExample.swift [hunk 3]
```diff
@@ -0,0 +1,117 @@
...
+    commonBottomNavigationTypicalUseSwiftExampleInit()
+  }
+  
+  @available(*, unavailable)
+  required init?(coder aDecoder: NSCoder) {
+    super.init(coder: aDecoder)
+  }
+  
+  func commonBottomNavigationTypicalUseSwiftExampleInit() {
+    view.backgroundColor = .lightGray
```
Comment (romoore) [inline components/BottomNavigation/examples/BottomNavigationTitleVisibilityChangeExample.swift]: Nit: Please use `colorScheme.backgroundColor` for the background color.

**Review by romoore — APPROVED** [review]
LGTM. Just a pair of minor comments about the example.

**Comment by randallli** [comment]
I reran the kokoro CI.
We need to merge develop so that we get #6184 which should fix the failing kokoro/pr/website check.

**Comment by randallli** [comment]
error from kokoro (Internal CI):

Test Suite 'BottomNavigationItemViewTests' started at 2019-01-07 07:58:32.626
Test Case '-[BottomNavigationItemViewTests testBadgeCenterIsCorrectWithoutRTL]' started.
Test Case '-[BottomNavigationItemViewTests testBadgeCenterIsCorrectWithoutRTL]' passed (0.002 seconds).
Test Case '-[BottomNavigationItemViewTests testBadgeCenterIsCorrectWithRTL]' started.
Test Case '-[BottomNavigationItemViewTests testBadgeCenterIsCorrectWithRTL]' passed (0.002 seconds).
Test Case '-[BottomNavigationItemViewTests testContentInsetLayout]' started.
Test Case '-[BottomNavigationItemViewTests testContentInsetLayout]' passed (0.016 seconds).
Test Case '-[BottomNavigationItemViewTests testHorizontalMarginLayout]' started.
Test Case '-[BottomNavigationItemViewTests testHorizontalMarginLayout]' passed (0.003 seconds).
Test Case '-[BottomNavigationItemViewTests testSetSelectedItemTintColorUpdatesInkColor]' started.
Test Case '-[BottomNavigationItemViewTests testSetSelectedItemTintColorUpdatesInkColor]' passed (0.002 seconds).
Test Case '-[BottomNavigationItemViewTests testSetTitleVisibilityUpdatesLayout]' started.
components/BottomNavigation/tests/unit/BottomNavigationItemViewTests.m:141: error: -[BottomNavigationItemViewTests testSetTitleVisibilityUpdatesLayout] : ((imageMidY) equal to (32.75) +/- (0.001)) failed: ("32.5") is not equal to ("32.75") +/- ("0.001")

File: components/BottomNavigation/tests/unit/BottomNavigationItemViewTests.m [hunk 4]
```diff
@@ -127,6 +127,28 @@ - (void)testSetSelectedItemTintColorUpdatesInkColor {
...
+  MDCBottomNavigationItemView *view = [[MDCBottomNavigationItemView alloc] init];
+  view.title = @"Test Content";
+  view.image = fakeImage();
+  view.bounds = CGRectMake(0, 0, 100, 100);
+  view.contentVerticalMargin = 20;
+  view.contentHorizontalMargin = 20;
+  view.titleVisibility = MDCBottomNavigationBarTitleVisibilityAlways;
+  [view layoutIfNeeded];
+  CGFloat imageMidY = CGRectGetMidY(view.iconImageView.frame);
+  XCTAssertEqualWithAccuracy(imageMidY, 32.75, 0.001);
```
Comment (romoore) [inline components/BottomNavigation/tests/unit/BottomNavigationItemViewTests.m]: Tip: Consider making this a less-than-equal and greater-than-equal so you can verify the "approximate" location.  It seems like we don't care too much about the exact placement, but rather only that it is "to the left of center" by some reasonable amount.

File: components/BottomNavigation/examples/BottomNavigationTitleVisibilityChangeExample.swift (hunk 2 above)
Comment (Ruberik) [reply components/BottomNavigation/examples/BottomNavigationTitleVisibilityChangeExample.swift:94]: Thank you for spotting that. Moved to viewDidLoad().

File: components/BottomNavigation/examples/BottomNavigationTitleVisibilityChangeExample.swift (hunk 3 above)
Comment (Ruberik) [reply components/BottomNavigation/examples/BottomNavigationTitleVisibilityChangeExample.swift]: Fixed, here and in other BottomNav Swift examples.

File: components/BottomNavigation/tests/unit/BottomNavigationItemViewTests.m (hunk 4 above)
Comment (Ruberik) [reply components/BottomNavigation/tests/unit/BottomNavigationItemViewTests.m]: Good point. I appreciate you giving a broader view; I admit I was happy just to get a passing test that wouldn't have passed before.

**Comment by Ruberik** [comment]
I'll preface this by saying that I'm a Git noob who, so far, has managed to make things... sort of work.

I've made the changes, but I can't seem to get them on github.com/Ruberik/material-components-ios. Here's what happened:

1. When I created this PR, I (unwisely?) made it in my own `develop` branch.
2. When I rebase my local `develop` branch onto material-components' `develop` branch, it works fine. When I try to force push (is that really what I should be doing?) onto github.com/Ruberik/material-components-ios's `develop` branch, here's what I get. The commandline is coming from Sourcetree, for what it's worth:

```
git --no-optional-locks -c color.branch=false -c color.diff=false -c color.status=false -c diff.mnemonicprefix=false -c core.quotepath=false -c credential.helper=sourcetree -c lfs.customtransfer.bitbucket-media-api.path=/Applications/Sourcetree.app/Contents/Resources/git_local/git-lfs/git-lfs-bitbucket-media-api push -v --force origin refs/heads/develop:refs/heads/develop 
Pushing to https://github.com/Ruberik/material-components-ios.git
open /Users/Bartholomew/dev/material-components-ios/snapshot_test_goldens/goldens_64/MDCTextAreaOutlinedControllerBaselineCharacterCountArabicSnapshotTests/testTextFieldEmptyDisabled_11_2@2x.png: no such file or directory
error: failed to push some refs to 'https://github.com/Ruberik/material-components-ios.git'
Completed with errors, see above
```

Sorry to drag you into my own personal Git troubles.

**Comment by romoore** [comment]
Can you try  `git lfs fetch --all` and then push?  Let me know if that helps.

**Comment by romoore** [comment]
In general, if you found you've created a commit in the wrong branch, you can do the following:

1. Use `git log` to find the commits since you branched from upstream's `develop`. Grab the commit hash.
2. Use `git reset --soft <COMMIT HASH>` to undo ALL of your work and have it sitting as if it's just been modified on the file system.
3. Use `git stash` to put all modified files (but not newly-created files) into the stash
4. Use `git checkout -b my-new-branch` to create the new branch, `my-new-branch`
5. Use `git stash apply` to unstash your changes and put them in the working directory
6. Commit your changes to the new branch
7. Push (forced?) to the existing remote branch or push to a new remote branch (and open a new PR).

As clean-up, you'll also want to do `git stash drop` to drop the latest stash entry. **Be careful!**  If you aren't sure, you can always `git stash list` to take a look at what's in your stash.

**Comment by romoore** [comment]
Oops, I had the wrong `git lfs` command above. It's been correct to spell "all" correctly.

File: components/BottomNavigation/tests/unit/BottomNavigationItemViewTests.m [hunk 5]
```diff
@@ -127,6 +127,27 @@ - (void)testSetSelectedItemTintColorUpdatesInkColor {
...
+  [view layoutIfNeeded];
+  CGFloat imageMidYWithTitle = CGRectGetMidY(view.iconImageView.frame);
+
+  // When
+  view.titleVisibility = MDCBottomNavigationBarTitleVisibilityNever;
+  [view layoutIfNeeded];
+
+  // Then
+  CGFloat imageMidYWithoutTitle = CGRectGetMidY(view.iconImageView.frame);
+  XCTAssertGreaterThan(imageMidYWithoutTitle, imageMidYWithTitle + 1);  // We add 1 to make sure the change in position is greater than a rounding error. Practically, it's likely to be greater than 10.
```
Comment (romoore) [inline components/BottomNavigation/tests/unit/BottomNavigationItemViewTests.m]: Nit: This line looks a bit long. Consider breaking it up or running clang-format on your changes.

**Review by romoore — DISMISSED** [review]

File: components/BottomNavigation/tests/unit/BottomNavigationItemViewTests.m (hunk 5 above)
Comment (Ruberik) [reply components/BottomNavigation/tests/unit/BottomNavigationItemViewTests.m]: Broken up and clang-formatted.

**Comment by Ruberik** [comment]
Thanks! That `git lfs` command fixed me up nicely. I believe the currently-pushed thing in my fork is properly rebased and has addressed all comments.

Thanks for all the help writing this. I've definitely become a more competent git user after this.

File: components/BottomNavigation/examples/BottomNavigationTitleVisibilityChangeExample.swift [hunk 6]
```diff
@@ -0,0 +1,120 @@
...
+    instructionLabel.frame = instructionFrame
+  }
+  
+  override func viewWillLayoutSubviews() {
+    super.viewWillLayoutSubviews()
+    layoutBottomNavBar()
+  }
+  
+  override func viewDidLoad() {
+    addInstructionLabel()
```
Comment (romoore) [inline components/BottomNavigation/examples/BottomNavigationTitleVisibilityChangeExample.swift:94]: Did you forget to call `super.viewDidLoad()`?

Comment (Ruberik) [reply components/BottomNavigation/examples/BottomNavigationTitleVisibilityChangeExample.swift:94]: I did! Did a lint pick that up, or did you spot it?

**Comment by romoore** [comment]
;_; Looks like the force-push lost the commit history.  I'll take another review at this today.

File: components/BottomNavigation/examples/BottomNavigationTitleVisibilityChangeExample.swift (hunk 6 above)
Comment (romoore) [reply components/BottomNavigation/examples/BottomNavigationTitleVisibilityChangeExample.swift:94]: That was just me. I've often made the same mistake in the past, so I try to catch it where I can. ;-)

**Comment by Ruberik** [comment]
Aww! Sorry. Dumb question: is there a better way to handle catching up with your `develop` branch than rebasing my changes in my local repository, then force pushing them? I tried to find a way to directly rebase my GitHub repository, but couldn't find one.

**Comment by romoore** [comment]
If you do your work on a local branch, you can then `git merge develop` to pull changes into your development branch.  Here's my typical workflow:

1. `git checkout -b issue-1234`
2. Do work....
3. `git commit`
4. `git push origin issue-1234`
5. `git checkout develop`
6. `git pull upstream develop` (this keeps my local `develop` fast-forwarded with changes upstream)
7. `git push origin develop`
7. `git checkout issue-1234`
8. `git merge develop`  (resolve any conflicts)
9. `git push origin issue-1234`

I will repeat 2-9 for any additional work, feedback, etc.  If a PR is still sitting in GitHub in the morning, I try to do a merge from `develop` before doing any more work.  I just opened https://github.com/material-components/material-components-ios/issues/6280 to reduce the number of errors not caught by outdated PRs.

**Comment by Ruberik** [comment]
Thanks for explaining that! All the guides I could find seemed to assume nothing was happening to the repository other than the reader's changes, and skipped 4-10. Is there a Google guide to GitHub workflow somewhere external? Or a good guide somewhere that you used to learn this stuff?

**Review by romoore — APPROVED** [review]

**Comment by romoore** [comment]
I'm not sure, but Atlassian has a good description of the differences.

https://www.atlassian.com/git/tutorials/merging-vs-rebasing
