### PR TITLE
[Catalog] Make theme picker available to VoiceOver

### LINKED ISSUE #3652: [Catalog] It is not possible to select a material palette color in the Themes menu with VoiceOver
Repro steps:

- Enable VoiceOver.
- Open MDCCatalog.
- Open any component landing page.
- Open the menu.
- Select "Themes".
- Attempt to select a color

Expected behavior:
- It is possible to select a color with VoiceOver.

Actual behavior:
- VoiceOver stops at "Material Palette" and doesn't allow you to select a specific color.

### PR DESCRIPTION
**Pull request by romoore**
The Theme picker was not accessible to VoiceOver due to a few missing
properties. Adding those properties and enhancing the text a bit to clarify
what the screen does.

Closes #3652

### CODE REVIEW

File: catalog/MDCCatalog/MDCThemePickerViewController.swift [hunk 1]
```diff
@@ -36,36 +47,37 @@ class MDCThemePickerViewController: UIViewController, UICollectionViewDataSource
...
+    MDCColorThemeCellConfiguration(name: "Default",
+                                   mainColor: AppTheme.defaultTheme.colorScheme.primaryColor,
+                                   colorScheme: { return AppTheme.defaultTheme.colorScheme }()
     ),
-    (
-      mainColor: MDCPalette.blue.tint500,
-      colorScheme: { return createSchemeWithPalette(MDCPalette.blue) }
+    MDCColorThemeCellConfiguration(name: "Blue",
+                                   mainColor: MDCPalette.blue.tint500,
+                                   colorScheme: { return createSchemeWithPalette(MDCPalette.blue) }()
```
Comment (andrewoverton) [inline catalog/MDCCatalog/MDCThemePickerViewController.swift]: Pretty sure you can change all of these to `colorScheme: createSchemeWithPalette(MDCPalette.blue)` etc. Not necessary to wrap the function call in a closure and execute that

File: catalog/MDCCatalog/MDCThemePickerViewController.swift [hunk 2]
```diff
@@ -27,6 +27,17 @@ private func createSchemeWithPalette(_ palette: MDCPalette) -> MDCSemanticColorS
   return scheme
 }
 
+class MDCColorThemeCellConfiguration {
+  var name: String
```
Comment (andrewoverton) [inline catalog/MDCCatalog/MDCThemePickerViewController.swift]: If these are immutable they should be `let`s

**Review by ianegordon — APPROVED** [review]
Please address Andrew's comments before merge.
Otherwise, LGTM.

File: catalog/MDCCatalog/MDCThemePickerViewController.swift (hunk 1 above)
Comment (romoore) [reply catalog/MDCCatalog/MDCThemePickerViewController.swift]: Oh, I thought it was going to be lazy and not evaluate the closure until it was referenced?

Comment (romoore) [reply catalog/MDCCatalog/MDCThemePickerViewController.swift]: Except that my code is no longer lazy!  Spoke with @yarneo and we'll decide whether to keep the closures or do proper properties.

File: catalog/MDCCatalog/MDCThemePickerViewController.swift (hunk 2 above)
Comment (romoore) [reply catalog/MDCCatalog/MDCThemePickerViewController.swift]: Done.

Comment (yarneo) [reply catalog/MDCCatalog/MDCThemePickerViewController.swift]: they still look like `var`

Comment (yarneo) [reply catalog/MDCCatalog/MDCThemePickerViewController.swift]: This is also a struct potential

File: catalog/MDCCatalog/MDCThemePickerViewController.swift (hunk 1 above)
Comment (yarneo) [reply catalog/MDCCatalog/MDCThemePickerViewController.swift]: So the thought process behind making it lazy is that we won't have to initialize X many color schemes but rather only the color scheme you would need. Does that make sense? I felt like the scheme creation so many times was unneeded and can be heavy.

Comment (romoore) [reply catalog/MDCCatalog/MDCThemePickerViewController.swift]: I understood the reasons behind it, I just didn't know how much we care to keep it around.  Since I believe you were the original author, I thought you might have an opinion one way or the other.

File: catalog/MDCCatalog/MDCThemePickerViewController.swift (hunk 2 above)
Comment (romoore) [reply catalog/MDCCatalog/MDCThemePickerViewController.swift]: Sorry, committed but didn't push it up.

**Review by yarneo — APPROVED** [review]
