### PR TITLE
[Banner] Apply text theme to button in the typical example.

### LINKED ISSUE #7531: [Banner] Buttons don't show any touch feedback
Repro steps:

1. Open MDCDragons.
2. Open the Banner > Banner example.
3. Tap any option to show a Banner.
4. Tap down on any Banner button.

Expected behavior: the button shows an ink effect in response to the user's interaction.

Actual behavior: nothing

---
#### Internal data
- Associated internal bug: [b/134446736](http://b/134446736)
- Blocked by: https://github.com/material-components/material-components-ios/issues/7811

### PR DESCRIPTION
**Pull request by fluxminds**
closes https://github.com/material-components/material-components-ios/issues/7531.

Originally the text theme was not applied in the example. It is fixed in this PR.

### CODE REVIEW

File: components/Banner/examples/BannerTypicalUseExampleViewController.m [hunk 1]
```diff
@@ -90,8 +93,9 @@ @implementation BannerTypicalUseExampleViewController
 - (instancetype)init {
   self = [super init];
   if (self) {
-    self.colorScheme = [[MDCSemanticColorScheme alloc] init];
-    self.typographyScheme = [[MDCTypographyScheme alloc] init];
+    self.containerScheme = [[MDCContainerScheme alloc] init];
```
Comment (codeman7) [inline components/Banner/examples/BannerTypicalUseExampleViewController.m]: I believe within `init` we should be using the `ivar`.

**Review by codeman7 — APPROVED** [review]

File: components/Banner/examples/BannerTypicalUseExampleViewController.m (hunk 1 above)
Comment (fluxminds) [reply components/Banner/examples/BannerTypicalUseExampleViewController.m]: Addressed in 5361ac676f23c5a5b56c1e374032d65f049a8975.
