### PR TITLE
[BottomNavigation] Correct itemTitleFont behavior

### LINKED ISSUE #2734: [BottomNavigation] `itemTitleFont` defaults to nil
### Overview
The `itemTitleFont` is marked as `nonnull` in the headers, but returns nil by default. It should return whatever default font will be used.

### Reproduction steps
Create an `MDCBottomNavigationBar` and inspect its `itemTitleFont` property.

### Version number
43.1.0

### LINKED ISSUE #2735: [BottomNavigation] `itemTitleFont` is not applied to newly-added items
### Overview
BottomNavigation does not apply the `itemTitleFont` value to items added after the property is set.

### Reproduction steps
```objectivec
self.bottomNavBar.itemTitleFont = [UIFont preferredFontForTextStyle:UIFontTextStyleCaption1];
self.bottomNavBar.items = @[ item1, item2, item3, item4]; // These will remain with the system font
```

### Version number
43.1.0

### Related issues
#2734

### PR DESCRIPTION
**Pull request by romoore**
The `itemTitleFont` property was not defaulted to a non-nil value, breaking
the API header contract. It was also not being applied when the set of items
in the bar were changed.

Closes #2734
Closes #2735

### CODE REVIEW

File: components/BottomNavigation/tests/unit/BottomNavigationTests.m [hunk 1]
```diff
@@ -0,0 +1,85 @@
...
+  self.bottomNavBar = [[MDCBottomNavigationBar alloc] init];
+}
+
+- (void)tearDown {
+  self.bottomNavBar = nil;
+}
+
+- (void)testInit {
+  // When
+  MDCBottomNavigationBar *bar = [[MDCBottomNavigationBar alloc] init];
```
Comment (yarneo) [inline components/BottomNavigation/tests/unit/BottomNavigationTests.m:42]: maybe worth testing self.bottomNavBar for XCAssertNotNil, which is allocated in setUp, rather than creating another MDCBottomNavigationBar? Not sure it really makes a difference, but bringing it up for conciseness sake.

**Review by yarneo — APPROVED** [review]

File: components/BottomNavigation/tests/unit/BottomNavigationTests.m (hunk 1 above)
Comment (romoore) [reply components/BottomNavigation/tests/unit/BottomNavigationTests.m:42]: Agreed it's not the least amount of code to achieve the result. I felt it was OK to leave it separate in case we change to a different initializer in the future.

**Review by randallli — APPROVED** [review]

File: components/BottomNavigation/tests/unit/BottomNavigationTests.m [hunk 2]
```diff
@@ -0,0 +1,85 @@
...
+ distributed under the License is distributed on an "AS IS" BASIS,
+ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ See the License for the specific language governing permissions and
+ limitations under the License.
+ */
+
+#import <XCTest/XCTest.h>
+
+#import "MaterialBottomNavigation.h"
+#import "../../src/private/MDCBottomNavigationItemView.h"
```
Comment (jverkoey) [inline components/BottomNavigation/tests/unit/BottomNavigationTests.m:20]: This doesn’t seem ideal. Are you unable to reference the header using private/ as a prefix alone?

**Review by jverkoey — APPROVED** [review]
🥇  tests :)

File: components/BottomNavigation/tests/unit/BottomNavigationTests.m (hunk 2 above)
Comment (romoore) [reply components/BottomNavigation/tests/unit/BottomNavigationTests.m:20]: This is the structure we've chosen.  I didn't want to depend on the INCLUDE search path to find the correct file.

```
src/*
src/private/*
tests/unit/*
tests/earlgrey/*
examples/*
examples/supplemental/*
```

Comment (jverkoey) [reply components/BottomNavigation/tests/unit/BottomNavigationTests.m:20]: We are already depending on the include search path for our umbrella headers. I’m not sure what you mean by “this is the structure we’ve chosen” here.

This is the first example I’m aware of that makes use of relative import paths like this - are you sure we want to start encouraging this?

Comment (romoore) [reply components/BottomNavigation/tests/unit/BottomNavigationTests.m:20]: Xcode fails to find the file if I do

```objectivec
#import "private/MDCBottomNavigationItemView.h"
```

```
/Users/.../BottomNavigationTests.m:20:9: fatal error: 'private/MDCBottomNavigationItemView.h' file not found
#import "private/MDCBottomNavigationItemView.h"
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

```
