### PR TITLE
[Buttons] Fix dynamic type example.

### LINKED ISSUE #8855: [Catalog] Internal issue: b/144527189
This was filed as an internal issue. If you are a Googler, please visit [b/144527189](http://b/144527189) for more details.

---
#### Internal data
- Associated internal bug: [b/144527189](http://b/144527189)

### PR DESCRIPTION
**Pull request by codeman7**
This updates the buttons dynamic font example to use what we currently recommend for dynamic type support in MDCButton. This also updates the container scheme to be `@objc` so that Catalog by Conventions can inject the container scheme.

#### XS 

| Before | After |
| --- | --- |
|Simulator Screen Shot - iPhone 5 - 2019-11-18 at 14 23 58|Simulator Screen Shot - iPhone 5 - 2019-11-18 at 14 17 17|

#### XXXL

| Before | After |
| --- | --- |
|Simulator Screen Shot - iPhone 5 - 2019-11-18 at 14 23 45|Simulator Screen Shot - iPhone 5 - 2019-11-18 at 14 17 23|

Closes #8855

### CODE REVIEW

File: components/Buttons/examples/ButtonsDynamicTypeViewController.swift [hunk 1]
```diff
@@ -86,6 +79,13 @@ class ButtonsDynamicTypeViewController: UIViewController {
               options: .alignAllCenterX, metrics: nil, views: views))
   }
 
+  override func viewDidLayoutSubviews() {
+    super.viewDidLayoutSubviews()
+
+    let buttonFont = containerScheme.typographyScheme.button.mdc_scaledFont(for: view)
+    flatButtonDynamic.setTitleFont(buttonFont, for: .normal)
```
Comment (jverkoey) [inline components/Buttons/examples/ButtonsDynamicTypeViewController.swift]: Sanity checking here: I'd expect us to encourage setting `adjustsFontForContentSizeCategory` to YES after initializing the button rather than dynamically re-applying the font here. Can we do that instead here?

**Review by jverkoey — COMMENTED** [review]
One question about the recommendation being added here.

**Review by randallli — APPROVED** [review]

File: components/Buttons/examples/ButtonsDynamicTypeViewController.swift (hunk 1 above)
Comment (randallli) [reply components/Buttons/examples/ButtonsDynamicTypeViewController.swift]: +1.
should we remove the mdc_adjustsFontForContentSizeCategory calls too?

Comment (romoore) [reply components/Buttons/examples/ButtonsDynamicTypeViewController.swift]: I think the expectation is that in `viewDidLoad` the initial font is set using the `mdc_scaledFont(for:view)` call and that `mdc_adjustsFontForContentSizeCategory` is also set. After that, there should be no need to do anything in `viewDidLayoutSubviews` for Typography.

Comment (romoore) [reply components/Buttons/examples/ButtonsDynamicTypeViewController.swift]: We should not be setting `adjustsFontForContentSize` here since it has no effect on `MDCFontScaler` fonts.

Comment (randallli) [reply components/Buttons/examples/ButtonsDynamicTypeViewController.swift]: ok I think that I understand now.
echoing back to you: The 3 version of this is not ready yet so we have to use v2: mdc_adjustsFontForContentSizeCategory calls.

**Review by romoore — APPROVED** [review]
