### PR TITLE
[TextFields] Fixed issue: Placeholder label gets stuck in expanded state when switching between controls 

### LINKED ISSUE #3679: [TextFields] Placeholder label gets stuck in expanded state when switching between controls
Repro steps:

1. Open MDCCatalog
2. Open the TextFields main demo
3. Select a text field
4. Press tab to cycle through the text fields
5. Press shift-tab to cycle backwards
6. Repeat 4. and 5., cycling a couple times

Expected behavior:
Placeholders for non-focused text fields stay in their "resting" position within the text field.

Actual behavior:
Placeholders get "stuck" in their expanded position.

gif demonstrating the behavior:
rapid-bug

---
#### Internal data
- Associated internal bug: [b/117179031](http://b/117179031)

### PR DESCRIPTION
**Pull request by svallex**
## Steps to reproduce
Sometimes if the user taps or tabs quickly between multiple Text Fields on the same view, the floating placeholder remains stuck in the floating ("up") position.

## Expected Behavior
The order of operations when placeholder is animated down: 
1. Deactivating constraints
2. Animating down 
3. Clearing constraints.

The order of operations when placeholder is animated up:
1. Activating constraints 
2. Animating up.

## Actual Behavior
1. Deactivating constraints
2. Start animating down
3. Tap
4. Activating constraints
5. Start animating up
6. Clearing constraints.

So in the  "up" state, the placeholder ends up without constraints. As a result we see this bug.

## Screen capture of the behavior

|Before|After|
|---|---|
|beforefix|afterfix|

Fixes #3679

### CODE REVIEW

**Comment by andrewoverton** [comment]
Hi @svallex, thanks for the PR! Would you mind providing some before/after screenshots, or even better, gifs/videos?

**Comment by svallex** [comment]
@andrewoverton 
[Before fix](https://drive.google.com/open?id=1b1c4r-VfAHJSiifg4ghfEX0x8NBRya5W)

[After fix](https://drive.google.com/open?id=1Uu-9sjgoBWKlKhviSP_pNsOZzFNkzLZD)

**Comment by svallex** [comment]
Some explanations.

The order of operations when placeholder is animated down: Deactivating constraints -> Animating down -> Clearing constraints.
And for up animation: Activating constraints -> Animating up.

Sometimes if try to tap quickly this order is broken: Deactivating constraints -> Start animating down -> Tap -> Activating constraints -> Start animating up -> Clearing constraints.
So in up state placeholder is without constraints. As result we see this bug.

How to fix: add check for active constraints and clear only deactivated constraints.

**Comment by andrewoverton** [comment]
@svallex looks good to me! I'll approve and merge once all the CI stuff is green--looks like Clang Format is failing.

**Comment by svallex** [comment]
Fixed clang-format

**Comment by svallex** [comment]
Fixed problem with cla

File: components/TextFields/src/MDCTextInputControllerBase.m [hunk 1]
```diff
@@ -581,6 +581,11 @@ - (BOOL)needsUpdatePlaceholderAnimationConstraintsToUp {
 // itself. That means these constraints need go away. So, we can use the existence of them as a
 // way to check if the placeholder is floating up. See isplaceholderUp.
 - (void)cleanupPlaceholderAnimationConstraints {
+  if (self.placeholderAnimationConstraintLeading.active &&
```
Comment (romoore) [inline components/TextFields/src/MDCTextInputControllerBase.m:586]: Would you please add a small comment explaining why we would exit early under these conditions?

**Review by romoore — APPROVED** [review]
LGTM.

**Comment by romoore** [comment]
@svallex I tried to capture your comments (and converted your .mov files) in the summary. Please take a look and let me change anything you'd like. Either way, please let us know when you're happy with the summary.

**Comment by svallex** [comment]
@romoore thanks for edited summary, looks good

File: components/TextFields/src/MDCTextInputControllerBase.m (hunk 1 above)
Comment (svallex) [reply components/TextFields/src/MDCTextInputControllerBase.m:586]: Did you mean to add a comment to the code?

Comment (svallex) [reply components/TextFields/src/MDCTextInputControllerBase.m:586]: I can add to code something like this: "We need to clear only deactivated constraints and to prevent the clearing of active constraints."
It's OK?

Comment (romoore) [reply components/TextFields/src/MDCTextInputControllerBase.m:586]: Yep, that sounds good. Especially the second part. 👍

Comment (svallex) [reply components/TextFields/src/MDCTextInputControllerBase.m:586]: I added a comment

Comment (romoore) [reply components/TextFields/src/MDCTextInputControllerBase.m:586]: Awesome, looks good. I've retriggered the kokoro jobs to get the final set of approvals.
