### PR TITLE
[Ink] Add NSCoding support to MDCInkView/Layer

### LINKED ISSUE #2772: [Ink] Support encoding inkColor
### Overview
`MDCInkView` should fully support NSCoding, including its `inkColor` property. Without this property, archived objects that set custom ink color will fail to restore the same ink color.

### Reproduction steps
1. Create an `MDCInkView` and set the `inkColor` property to a non-default value
1. Archive and unarchive the ink view
1. Verify that the `inkColor` value of the unarchived object is equivalent to the original

### Version number
43.1.0

### PR DESCRIPTION
**Pull request by romoore**
Both MDCInkLayer (and MDCLegacyInkLayer) and MDCInkView should support
NSCoding methods since their superclasses conform to an NSCoding (or
NSSecureCoding) protocol.

Closes #2772

### CODE REVIEW

**Review by ajsecord — APPROVED** [review]

File: components/Ink/src/private/MDCInkLayer.m [hunk 1]
```diff
@@ -33,13 +41,25 @@
...
+}
+
 - (instancetype)initWithLayer:(id)layer {
   self = [super initWithLayer:layer];
   if (self) {
     _endAnimationDelay = 0;
     _finalRadius = 0;
     _initialRadius = 0;
-    _inkColor = [UIColor colorWithWhite:0 alpha:0.08f];
+    _inkColor = [UIColor colorWithWhite:0 alpha:(CGFloat)0.08];
```
Comment (yarneo) [inline components/Ink/src/private/MDCInkLayer.m:62]: Curious why you decided to cast instead? Also I noticed you are using this number more than once, maybe worth putting as a const at the top.

**Review by yarneo — APPROVED** [review]

File: components/Ink/src/private/MDCInkLayer.m (hunk 1 above)
Comment (romoore) [reply components/Ink/src/private/MDCInkLayer.m:62]: 0.08f and 0.08 are not equivalent on 64-bit architectures. 0.08 can't be represented perfectly in binary, so the colors are different.

Comment (yarneo) [reply components/Ink/src/private/MDCInkLayer.m:62]: ah this is interesting! Do we have other places where this could be a problem too? I am assuming we usually use the `f` approach

Comment (romoore) [reply components/Ink/src/private/MDCInkLayer.m:62]: We do have a lot of code that uses `1.f` or `0.3f` to suppress warnings. In general it's not a huge issue if the numbers aren't critical (watch out for floating point rounding errors!). In this case, it makes it easier to verify that the correct colors are in use.

Comment (ajsecord) [reply components/Ink/src/private/MDCInkLayer.m:62]: We usually use the `f` approach, since it's simple and happens to work. The most correct is `(CGFloat)0.08` because the compiler will keep the full 64 bits of precision in 64-bit mode. (If you want to play around with the floating-point representation there are lots of [calculators](https://www.h-schmidt.net/FloatConverter/IEEE754.html) available on the web.)

**However** the error between the two methods is irrelevant for color values, which typically only care about 8 bits anyway (the float gets converted to [0,255]. (Even deeper color spaces, like ones with 16-bit channels, won't be able to see this difference.)

Like all these borderline nitpicky issues, my rule is: they're fine if you want to write them, but don't do large refactors/search-and-replaces or insist that other people change their code—it's not worth the engineering time.

Comment (yarneo) [reply components/Ink/src/private/MDCInkLayer.m:62]: Awesome, thank you for the explanation!

Comment (ajsecord) [reply components/Ink/src/private/MDCInkLayer.m:62]: I occasionally get to use that PhD in computer graphics. 😉

**Review by ianegordon — CHANGES_REQUESTED** [review]
MDCInkLayerTests : testEncoding is failing for me locally and on kokoro.
Missing a commit / git push?

**Review by ianegordon — APPROVED** [review]

**Comment by ianegordon** [comment]
Please merge when CI is happy!
