### PR TITLE
[Catalog] Flat buttons have clear background

### LINKED ISSUE #2091: [Catalog] Flat buttons should have clear background
### Overview
Flat buttons in the catalog should demonstrate clear background in the .Normal and .Disabled states. 

screen shot 2017-10-05 at 9 53 19 pm

### Reproduction steps
1. Open MDC Catalog &rarr; Buttons &rarr; Demo
2. Note the background of the Disabled Flat button

#### Expected Result ####
Disabled Flat Buttons have clear background color

#### Observed Result ####
Disabled Flat Buttons have a dark background color

### Version number
35.2.0

### Operating system and device
Any/all

### Related issues
Internal issue b/64313748

### PR DESCRIPTION
**Pull request by romoore**
Even when disabled, flat button should keep a clear background.

### Before
screen shot 2017-10-05 at 9 53 19 pm

### After
screen shot 2017-10-05 at 9 57 59 pm

Closes #2091

### CODE REVIEW

**Comment by jverkoey** [comment]
Should this behavior be encoded in the MDCFlatButton internal application of the theme? I'm surprised that there's a background color difference between enabled/disabled modes.

**Comment by romoore** [comment]
@jverkoey UIAppearance just calls the same selector on the individual instances when they're added to a window.  There isn't a way to distinguish a UIAppearance-based assignment from any other without doing nasty runtime inspection.

**Comment by randallli** [comment]
Should all flat buttons be clear or is it just our catalog's style?

**Comment by randallli** [comment]
looks like all flat disabled buttons should be clear by default. So we should probably change it in the class init?

**Comment by romoore** [comment]
They are clear by default. I'm just fixing the theming we use in the catalog.

See [MDCFlatButton.m](https://github.com/material-components/material-components-ios/blob/develop/components/Buttons/src/MDCFlatButton.m#L26)

File: catalog/MDCCatalog/AppDelegate.swift [hunk 1]
```diff
@@ -63,6 +63,11 @@ class AppDelegate: UIResponder, UIApplicationDelegate {
     MDCTabBarColorThemer.apply(colorScheme, to: MDCTabBar.appearance())
     MDCTextFieldColorThemer.applyColorScheme(toAllTextInputControllerDefault: colorScheme)
 
+    do {
```
Comment (ianegordon) [inline catalog/MDCCatalog/AppDelegate.swift]: Drop the do {} wrapper and move next to MDCButtonColorThemer above.

**Review by ianegordon — CHANGES_REQUESTED** [review]

File: catalog/MDCCatalog/AppDelegate.swift (hunk 1 above)
Comment (romoore) [reply catalog/MDCCatalog/AppDelegate.swift]: Alright. I was trying to keep the extra colorScheme's scope limited.

**Comment by samnm** [comment]
To clarify, this just undoes some of the theming that the MDCButton themer did to all MDCButton instances.

**Review by ianegordon — APPROVED** [review]
