### PR TITLE
[BottomNavigation] Test cases when we reset the bottom navigation items array

### LINKED ISSUE #4429: [BottomNavigation] Issue with `setItems` call layout of items
Explicitly set items after they have been set, lays out all the items wrong.

iOS 11.4/iPhone X

### PR DESCRIPTION
**Pull request by codeman7**
Added an example to showcase when items are reset to an new array.

Fixed the bug when we reset items and they don't layout correctly.

After a reset, set the selected tab to Null to mirror UITabBar
https://developer.apple.com/documentation/uikit/uitabbar/1623453-selecteditem?language=objc

Added two test to check for selection being Null after a reset and frames not being zero after a reset.

Closes #4429

### CODE REVIEW

File: components/BottomNavigation/src/MDCBottomNavigationBar.m [hunk 1]
```diff
@@ -405,7 +405,7 @@ - (void)didCancelTouchesForButton:(UIButton *)button {
 #pragma mark - Setters
 
 - (void)setItems:(NSArray<UITabBarItem *> *)items {
-  if (_items == items) {
+  if ([_items isEqual:items]) {
```
Comment (ianegordon) [inline components/BottomNavigation/src/MDCBottomNavigationBar.m]: You likely want both so the const and nil case are handled:
if (items == _items || [_items isEqual:items])

**Review by ianegordon — APPROVED** [review]
Please consider comments before merge.

**Comment by ianegordon** [comment]
If you put "WIP" in the PR title, the WIP check will come up red, so people won't merge the PR before you are finished. (WIP = work in progress)

**Comment by romoore** [comment]
As a team member with merge access, nobody will merge your PRs unless you put the label [`PR:merge-when-approved`](https://github.com/material-components/material-components-ios/labels/PR%3Amerge-when-approved).  For contributors without merge access, we tend to merge their PRs if they're unresponsive (and it's ready to go) for a few days.

File: components/BottomNavigation/examples/BottomNavigationResetButtons.swift [hunk 2]
```diff
@@ -0,0 +1,129 @@
...
+ See the License for the specific language governing permissions and
+ limitations under the License.
+ */
+
+import Foundation
+import MaterialComponents
+
+class BottomNavigationResetExample: UIViewController {
+
+  var colorScheme = MDCSemanticColorScheme()
```
Comment (romoore) [inline components/BottomNavigation/examples/BottomNavigationResetButtons.swift]: Please add a `typographyScheme` property so we can support injecting styles.

File: components/BottomNavigation/examples/BottomNavigationResetButtons.swift [hunk 3]
```diff
@@ -0,0 +1,129 @@
...
+  let tabBarItem2 =
+    UITabBarItem(title: "Messages", image: UIImage(named: "Email"), tag: 1)
+  let tabBarItem3 =
+    UITabBarItem(title: "Favorites", image: UIImage(named: "Favorite"), tag: 2)
+  let tabBarItem4 = UITabBarItem(title: "Cake", image: UIImage(named: "Cake"), tag: 3)
+
+  let buttonOne = MDCButton()
+  let buttonTwo = MDCButton()
+
+  init() {
```
Comment (romoore) [inline components/BottomNavigation/examples/BottomNavigationResetButtons.swift:39]: Is this required for Swift? Isn't the superclass default behavior of `-init` to call `-initWithNibName:bundle:`?

File: components/BottomNavigation/examples/BottomNavigationResetButtons.swift [hunk 4]
```diff
@@ -0,0 +1,129 @@
...
+  func layoutBottomNavBar() {
+    let size = bottomNavBar.sizeThatFits(view.bounds.size)
+    let bottomNavBarFrame = CGRect(x: 0,
+                                   y: view.bounds.height - size.height,
+                                   width: size.width,
+                                   height: size.height)
+    bottomNavBar.frame = bottomNavBarFrame
+  }
+
+  override func viewWillLayoutSubviews() {
```
Comment (romoore) [inline components/BottomNavigation/examples/BottomNavigationResetButtons.swift:57]: Can this be accomplished with a resizing mask instead?

File: components/BottomNavigation/examples/BottomNavigationResetButtons.swift [hunk 5]
```diff
@@ -0,0 +1,129 @@
...
+  override func viewSafeAreaInsetsDidChange() {
+    super.viewSafeAreaInsetsDidChange()
+    layoutBottomNavBar()
+  }
+  #endif
+
+  override func viewDidLoad() {
+    super.viewDidLoad()
+
+    view.backgroundColor = .lightGray
```
Comment (romoore) [inline components/BottomNavigation/examples/BottomNavigationResetButtons.swift]: Please use `colorScheme.backgroundColor`

File: components/BottomNavigation/examples/BottomNavigationResetButtons.swift [hunk 6]
```diff
@@ -0,0 +1,129 @@
...
+    buttonTwo.frame.origin = CGPoint(x: view.center.x - (buttonTwo.frame.width / 2),
+                                      y: view.center.y + 16)
+    buttonTwo.addTarget(self, action: #selector(reorderTwo), for: .touchUpInside)
+    view.addSubview(buttonTwo)
+
+    MDCBottomNavigationBarColorThemer.applySemanticColorScheme(colorScheme,
+                                                               toBottomNavigation: bottomNavBar)
+  }
+
+  override func viewWillAppear(_ animated: Bool) {
```
Comment (romoore) [inline components/BottomNavigation/examples/BottomNavigationResetButtons.swift]: Instead of overriding `-viewWillAppear`, can you use `-catalogShouldHideNavigation` and return `true`?

File: components/BottomNavigation/examples/BottomNavigationResetButtons.swift [hunk 7]
```diff
@@ -0,0 +1,129 @@
...
+    self.navigationController?.setNavigationBarHidden(true, animated: animated)
+  }
+
+  @objc func reorderOne(_ button: UIButton) {
+    bottomNavBar.items = [tabBarItem2, tabBarItem3, tabBarItem1]
+  }
+
+  @objc func reorderTwo(_ button: UIButton) {
+    bottomNavBar.items = [tabBarItem3, tabBarItem1, tabBarItem2, tabBarItem4]
+    bottomNavBar.selectedItem = tabBarItem3
```
Comment (romoore) [inline components/BottomNavigation/examples/BottomNavigationResetButtons.swift]: Why does this method set the selected item but `reorderOne` does not?

File: components/BottomNavigation/examples/BottomNavigationResetButtons.swift [hunk 8]
```diff
@@ -0,0 +1,129 @@
...
+  }
+}
+
+// MARK: Catalog by convention
+extension BottomNavigationResetExample {
+  class func catalogBreadcrumbs() -> [String] {
+    return ["Bottom Navigation", "Bottom Navigation Reset (Swift)"]
```
Comment (romoore) [inline components/BottomNavigation/examples/BottomNavigationResetButtons.swift]: I'm not sure I understand the "reset" part of this. Isn't it a reorder/reassignment example?

File: components/BottomNavigation/examples/BottomNavigationResetButtons.swift [hunk 9]
```diff
@@ -0,0 +1,129 @@
...
+ distributed under the License is distributed on an "AS IS" BASIS,
+ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ See the License for the specific language governing permissions and
+ limitations under the License.
+ */
+
+import Foundation
+import MaterialComponents
+
+class BottomNavigationResetExample: UIViewController {
```
Comment (romoore) [inline components/BottomNavigation/examples/BottomNavigationResetButtons.swift]: Please consider a quick comment describing what this example demonstrates and why.

File: components/BottomNavigation/src/MDCBottomNavigationBar.m [hunk 10]
```diff
@@ -473,7 +473,11 @@ - (void)setItems:(NSArray<UITabBarItem *> *)items {
     [self.itemViews addObject:itemView];
     [self.containerView addSubview:itemView];
   }
+  self.selectedItem = self.items[0];
```
Comment (romoore) [inline components/BottomNavigation/src/MDCBottomNavigationBar.m]: Would this crash if `items` is set to `nil`?

File: components/BottomNavigation/src/MDCBottomNavigationBar.m [hunk 11]
```diff
@@ -473,7 +473,11 @@ - (void)setItems:(NSArray<UITabBarItem *> *)items {
...
   [self addObserversToTabBarItems];
+  self.selectedItem = NULL;
```
Comment (romoore) [inline components/BottomNavigation/src/MDCBottomNavigationBar.m]: Should this be `nil` instead of `NULL`?

File: components/BottomNavigation/src/MDCBottomNavigationBar.m [hunk 12]
```diff
@@ -473,7 +473,11 @@ - (void)setItems:(NSArray<UITabBarItem *> *)items {
...
+  [self setNeedsLayout];
+  [self setNeedsDisplay];
```
Comment (romoore) [inline components/BottomNavigation/src/MDCBottomNavigationBar.m]: Is this required? I don't see a `-drawRect` and I would expect `layoutSubviews` to be sufficient for updating the view.

File: components/BottomNavigation/tests/unit/BottomNavigationTests.m [hunk 13]
```diff
@@ -97,4 +97,17 @@ -(void)testItemReset {
   XCTAssertEqual(self.bottomNavBar.itemViews.count, tabsCount);
 }
 
+-(void)testSelectedItemAfterReset {
```
Comment (romoore) [inline components/BottomNavigation/tests/unit/BottomNavigationTests.m]: Can this check be added to the test above instead of a separate test?

**Review by romoore — DISMISSED** [review]

File: components/BottomNavigation/examples/BottomNavigationResetButtons.swift (hunk 7 above)
Comment (codeman7) [reply components/BottomNavigation/examples/BottomNavigationResetButtons.swift]: Just to showcase when we set a selected item after a reset vs when we just reset.

File: components/BottomNavigation/examples/BottomNavigationResetButtons.swift (hunk 3 above)
Comment (codeman7) [reply components/BottomNavigation/examples/BottomNavigationResetButtons.swift:39]: This is needed or a crash will occur.

Comment (romoore) [reply components/BottomNavigation/examples/BottomNavigationResetButtons.swift:39]: I don't get a crash when I try:

```objectivec
id bar = [[MDCBottomNavigationBar alloc] init];
```

I also see some of our example VCs don't reimplement `init` and don't crash.  Like [TextFieldOutlinedObjectiveCExample](https://github.com/material-components/material-components-ios/blob/develop/components/TextFields/examples/TextFieldOutlinedExample.m)

Is this a bug in CatalogByConvention?

File: components/BottomNavigation/examples/BottomNavigationResetButtons.swift (hunk 7 above)
Comment (romoore) [reply components/BottomNavigation/examples/BottomNavigationResetButtons.swift]: Ok. Could we perhaps name the method, `reorderItemsAndSetSelected` or something more descriptive?

File: components/BottomNavigation/examples/BottomNavigationResetButtons.swift (hunk 3 above)
Comment (codeman7) [reply components/BottomNavigation/examples/BottomNavigationResetButtons.swift:39]: I think it's only an issue with Swift

File: components/BottomNavigation/examples/BottomNavigationResetButtons.swift (hunk 5 above)
Comment (codeman7) [reply components/BottomNavigation/examples/BottomNavigationResetButtons.swift]: I don't believe UIViewController responds to this for it's background color.

File: components/BottomNavigation/examples/BottomNavigationResetButtons.swift [hunk 14]
```diff
@@ -0,0 +1,131 @@
...
+  @available(iOS 11, *)
+  override func viewSafeAreaInsetsDidChange() {
+    super.viewSafeAreaInsetsDidChange()
+    layoutBottomNavBar()
+  }
+  #endif
+
+  override func viewDidLoad() {
+    super.viewDidLoad()
+    view.backgroundColor = MDCPalette.grey.tint100
```
Comment (romoore) [inline components/BottomNavigation/examples/BottomNavigationResetButtons.swift]: Please use the color scheme

File: components/BottomNavigation/src/MDCBottomNavigationBar.m [hunk 15]
```diff
@@ -473,7 +473,9 @@ - (void)setItems:(NSArray<UITabBarItem *> *)items {
     [self.itemViews addObject:itemView];
     [self.containerView addSubview:itemView];
   }
+  self.selectedItem = nil;
```
Comment (romoore) [inline components/BottomNavigation/src/MDCBottomNavigationBar.m:476]: I believe this would be a change in behavior for clients. Does it make sense to check if the previous `selectedItem` is in the current `items` array and only deselect it if it's absent?

File: components/BottomNavigation/tests/unit/BottomNavigationTests.m [hunk 16]
```diff
@@ -97,4 +97,34 @@ -(void)testItemReset {
...
+  UITabBarItem *item3 = [[UITabBarItem alloc] initWithTitle:@"2" image:nil tag:2];
+  [self.bottomNavBar sizeToFit];
+  self.bottomNavBar.frame = CGRectMake(0, 0, 320, 56);
+  [self.bottomNavBar setNeedsLayout];
+
+  // When
+  self.bottomNavBar.items = @[item1, item2];
+  self.bottomNavBar.items = @[item1, item2, item3];
+  [self.bottomNavBar layoutIfNeeded];
+
```
Comment (romoore) [inline components/BottomNavigation/tests/unit/BottomNavigationTests.m:112]: Nit: Please add the `Then` block markers here and the other test.

File: components/BottomNavigation/tests/unit/BottomNavigationTests.m [hunk 17]
```diff
@@ -97,4 +97,34 @@ -(void)testItemReset {
...
 }
 
+-(void)testFramesAfterReset {
+  // Given
+  UITabBarItem *item1 = [[UITabBarItem alloc] initWithTitle:@"1" image:nil tag:0];
+  UITabBarItem *item2 = [[UITabBarItem alloc] initWithTitle:@"2" image:nil tag:1];
+  UITabBarItem *item3 = [[UITabBarItem alloc] initWithTitle:@"2" image:nil tag:2];
+  [self.bottomNavBar sizeToFit];
+  self.bottomNavBar.frame = CGRectMake(0, 0, 320, 56);
+  [self.bottomNavBar setNeedsLayout];
```
Comment (romoore) [inline components/BottomNavigation/tests/unit/BottomNavigationTests.m]: Is this necessary?

File: components/BottomNavigation/examples/BottomNavigationResetButtons.swift (hunk 4 above)
Comment (romoore) [reply components/BottomNavigation/examples/BottomNavigationResetButtons.swift:57]: Does the MDCBottomNavigationBar account for the safe area automatically in `sizeThatFits`?

**Review by romoore — CHANGES_REQUESTED** [review]

File: components/BottomNavigation/examples/BottomNavigationResetButtons.swift (hunk 3 above)
Comment (romoore) [reply components/BottomNavigation/examples/BottomNavigationResetButtons.swift:39]: Ack.

File: components/BottomNavigation/src/MDCBottomNavigationBar.m (hunk 15 above)
Comment (codeman7) [reply components/BottomNavigation/src/MDCBottomNavigationBar.m:476]: Without this line you get unexpected behavior, where you can't select the item that was previously selected and it doesn't show itself as selected. The default behavior for UITabBar is to reset to nil so that's why we have this.

Comment (romoore) [reply components/BottomNavigation/src/MDCBottomNavigationBar.m:476]: Ack.

**Review by romoore — APPROVED** [review]
LGTM!
