### PR TITLE
[Tabs] Fix `contentFrame` for item view.

### LINKED ISSUE #7781: [Tabs] MDCTabBarViewItemView miscalculates `contentFrame`
The `contentFrame` returned is the frame of the content view. However, that internal view is meant only for layout. At the time the MDCTabBarView is perform its own layout, the item views have not yet laid-out their internal subviews (but have received their `frame`). Relying on that subview's frame means a selection indicator that uses `contentFrame` (not the default indicator) cannot correctly compute its path.

|Expected Appearance|Actual Appearance|
|---|---|
|Simulator Screen Shot - iPhone X - 2019-07-02 at 23 57 11|Simulator Screen Shot - iPhone X - 2019-07-02 at 23 42 59|

### PR DESCRIPTION
**Pull request by romoore**
The content frame should be:

* `titleLabel` frame using its `intrinsicContentSize` if there is no image.
* `iconImageView` frame if there is no title text.
* `titleLabel` fitting size for width, a height that covers both the image and title view.

Closes #7781

### CODE REVIEW

**Review by mikefan1991 — APPROVED** [review]

File: components/Tabs/src/TabBarView/private/MDCTabBarViewItemView.m [hunk 1]
```diff
@@ -122,6 +131,17 @@ - (void)layoutSubviews {
...
 
+- (CGRect)contentFrameForTitleLabelInTextOnlyLayout {
+  CGRect contentFrame = UIEdgeInsetsInsetRect(self.bounds, kEdgeInsetsTextOnly);
+
+  CGSize contentSize = CGSizeMake(CGRectGetWidth(contentFrame), CGRectGetHeight(contentFrame));
+  CGSize labelWidthFitSize = [self.titleLabel sizeThatFits:contentSize];
+  CGSize labelSize =
+      CGSizeMake(labelWidthFitSize.width, MIN(contentSize.height, labelWidthFitSize.height));
+  return CGRectMake(CGRectGetMidX(contentFrame) - (labelWidthFitSize.width / 2),
+                    CGRectGetMidY(contentFrame), labelSize.width, labelSize.height);
```
Comment (codeman7) [inline components/Tabs/src/TabBarView/private/MDCTabBarViewItemView.m]: Why are we using the MidY and not the MinY?

File: components/Tabs/src/TabBarView/private/MDCTabBarViewItemView.m [hunk 2]
```diff
@@ -150,6 +182,29 @@ - (void)layoutSubviewsImageOnly {
...
+  CGSize availableIconSize = CGSizeMake(
+      contentSize.width, contentSize.height - kImageTitlePadding - labelSingleLineSize.height);
+
+  // Position the image, limiting it so that at least 1 line of text remains.
+  CGSize imageIntrinsicContentSize = self.iconImageView.intrinsicContentSize;
+  CGSize imageFinalSize =
+      CGSizeMake(MIN(imageIntrinsicContentSize.width, availableIconSize.width),
+                 MIN(imageIntrinsicContentSize.height, availableIconSize.height));
+
+  // Now position the label from the bottom.g
```
Comment (codeman7) [inline components/Tabs/src/TabBarView/private/MDCTabBarViewItemView.m]: Nit: Remove the extra _"g"_

File: components/Tabs/src/TabBarView/private/MDCTabBarViewItemView.m [hunk 3]
```diff
@@ -150,6 +182,29 @@ - (void)layoutSubviewsImageOnly {
       CGPointMake(CGRectGetMidX(self.contentView.bounds), CGRectGetMidY(self.contentView.bounds));
 }
 
+- (CGRect)contentFrameForTitleLabelInTextAndImageLayout {
+  CGRect contentFrame = UIEdgeInsetsInsetRect(self.bounds, kEdgeInsetsTextAndImage);
+
+  CGSize contentSize = CGSizeMake(CGRectGetWidth(contentFrame), CGRectGetHeight(contentFrame));
+  CGSize labelSingleLineSize = self.titleLabel.intrinsicContentSize;
+  CGSize availableIconSize = CGSizeMake(
+      contentSize.width, contentSize.height - kImageTitlePadding - labelSingleLineSize.height);
```
Comment (codeman7) [inline components/Tabs/src/TabBarView/private/MDCTabBarViewItemView.m]: Here and below its confusing for me to see (x - y - z) I think it would be cleaner if it was (x - (y + z)).

File: components/Tabs/tests/unit/TabBarView/MDCTabBarViewItemViewTests.m [hunk 4]
```diff
@@ -217,4 +217,70 @@ - (void)testSizeThatFitsForShortTitleExpectedImageLargerDimensionsLimitsHeight {
...
+  itemView.titleLabel.text = @"Favorites";
+  itemView.bounds = CGRectMake(0, 0, 90, 48);
+
+  // Then
+  // Grab the `contentFrame` before layout to be sure it's calculated correctly at any time.
+  CGRect contentFrame = itemView.contentFrame;
+  [itemView layoutIfNeeded];
+  XCTAssertFalse(
+      CGRectEqualToRect(contentFrame, CGRectZero),
+      @"The `contentFrame` of an item view must not return CGRectZero when a title is set.");
```
Comment (codeman7) [inline components/Tabs/tests/unit/TabBarView/MDCTabBarViewItemViewTests.m]: _Tip:_ @"(%@) is equal to (%@)", NSStringFromCGRect(contentFrame), NSStringFromCGRect(CGRectZero)

File: components/Tabs/tests/unit/TabBarView/MDCTabBarViewItemViewTests.m [hunk 5]
```diff
@@ -217,4 +217,70 @@ - (void)testSizeThatFitsForShortTitleExpectedImageLargerDimensionsLimitsHeight {
...
+  itemView.iconImageView.image = fakeImage(24, 24);
+  itemView.bounds = CGRectMake(0, 0, 90, 48);
+
+  // Then
+  // Grab the `contentFrame` before layout to be sure it's calculated correctly at any time.
+  CGRect contentFrame = itemView.contentFrame;
+  [itemView layoutIfNeeded];
+  XCTAssertFalse(
+      CGRectEqualToRect(contentFrame, CGRectZero),
+      @"The `contentFrame` of an item view must not return CGRectZero when an image is set.");
```
Comment (codeman7) [inline components/Tabs/tests/unit/TabBarView/MDCTabBarViewItemViewTests.m]: Same as above.

File: components/Tabs/tests/unit/TabBarView/MDCTabBarViewItemViewTests.m [hunk 6]
```diff
@@ -217,4 +217,70 @@ - (void)testSizeThatFitsForShortTitleExpectedImageLargerDimensionsLimitsHeight {
...
+  itemView.iconImageView.image = fakeImage(24, 24);
+  itemView.titleLabel.text = @"Favorites";
+  itemView.bounds = CGRectMake(0, 0, 90, 48);
+
+  // Then
+  // Grab the `contentFrame` before layout to be sure it's calculated correctly at any time.
+  CGRect contentFrame = itemView.contentFrame;
+  [itemView layoutIfNeeded];
+  XCTAssertFalse(CGRectEqualToRect(contentFrame, CGRectZero),
+                 @"The `contentFrame` of an item view must not return CGRectZero when a title and "
```
Comment (codeman7) [inline components/Tabs/tests/unit/TabBarView/MDCTabBarViewItemViewTests.m]: Same as above.

**Review by codeman7 — COMMENTED** [review]
Please address "Why are we using the MidY and not the MinY?" all others are nits.

File: components/Tabs/src/TabBarView/private/MDCTabBarViewItemView.m (hunk 1 above)
Comment (romoore) [reply components/Tabs/src/TabBarView/private/MDCTabBarViewItemView.m]: Oops, good catch. This should be `midY - labelSize.height / 2`

Comment (romoore) [reply components/Tabs/src/TabBarView/private/MDCTabBarViewItemView.m]: Fixed and added tests to make sure the contentFrame makes sense.

File: components/Tabs/src/TabBarView/private/MDCTabBarViewItemView.m (hunk 3 above)
Comment (romoore) [reply components/Tabs/src/TabBarView/private/MDCTabBarViewItemView.m]: Done throughout.

File: components/Tabs/src/TabBarView/private/MDCTabBarViewItemView.m (hunk 2 above)
Comment (romoore) [reply components/Tabs/src/TabBarView/private/MDCTabBarViewItemView.m]: Done.

File: components/Tabs/tests/unit/TabBarView/MDCTabBarViewItemViewTests.m (hunk 4 above)
Comment (romoore) [reply components/Tabs/tests/unit/TabBarView/MDCTabBarViewItemViewTests.m]: Done.

File: components/Tabs/tests/unit/TabBarView/MDCTabBarViewItemViewTests.m (hunk 5 above)
Comment (romoore) [reply components/Tabs/tests/unit/TabBarView/MDCTabBarViewItemViewTests.m]: Done.

File: components/Tabs/tests/unit/TabBarView/MDCTabBarViewItemViewTests.m (hunk 6 above)
Comment (romoore) [reply components/Tabs/tests/unit/TabBarView/MDCTabBarViewItemViewTests.m]: Done.

**Review by codeman7 — APPROVED** [review]
