### PR TITLE
[Math] Align frames to pixel boundaries

### LINKED ISSUE #1723: [NavigationBar] ButtonBarItems labels are not pixel-aligned, resulting in blurry text
### Overview
The UILabel in the MDCBarButtonItem is not pixel-aligned and can easily arrive on a non-pixel point location. This results in anti-aliased (blurry) text. 

**In the image below, "UPD1" and "Grid Example" are pixel-aligned, "UPD2" is not**
navbar-upd2_blurry

The issue seems to arrive from our attempts to align the baseline values of the NavigationBar's title label and the labels within any text BarButton items.

### Reproduction steps
Add a text button to a NavigationBar

### Version number
29.0.0

### Operating system and device
iPhone 5 (Simulator) iOS 10.3
iPhone 5S/iOS 10.3.2

### PR DESCRIPTION
**Pull request by romoore**
Adding a new function to realign a CGRect (frame) to pixel boundaries
based on the screen scale. After a review of the catalog, I'm updating
the areas where I found misaligned frames.

|Component|Before|After|
|------------|-------|-----|
|Slider | slider-blur|slider-pixel
|Feature Highlight|feature-blur|feature-pixel
|Navigation Bar (Buttons)|navbar_blur|navbar_pixel

Closes #1723

### CODE REVIEW

File: components/Slider/examples/SliderCompareExampleViewController.m [hunk 1]
```diff
@@ -17,6 +17,7 @@
 #import <UIKit/UIKit.h>
 
 #import "MaterialSlider.h"
+#import "MaterialMath.h"
```
Comment (ajsecord) [inline components/Slider/examples/SliderCompareExampleViewController.m]: Sort imports...

File: components/private/Math/src/MDCMath.h [hunk 2]
```diff
@@ -94,3 +94,14 @@ static inline CGFloat MDCSqrt(CGFloat value) {
   return sqrtf(value);
 #endif
 }
+
+static inline CGRect MDCRectIntegral(CGRect rect) {
```
Comment (ajsecord) [inline components/private/Math/src/MDCMath.h]: This isn't as obvious as just `MDCSqrt` or whatever, please document.

**Review by ajsecord — CHANGES_REQUESTED** [review]

File: components/private/Math/src/MDCMath.h [hunk 3]
```diff
@@ -94,3 +94,20 @@ static inline CGFloat MDCSqrt(CGFloat value) {
   return sqrtf(value);
 #endif
 }
+
+/**
+ Expand `rect' to the smallest rect containing it with integral origin and
+ size.
```
Comment (ajsecord) [inline components/private/Math/src/MDCMath.h]: Not really true. Can you please document the `scale` functionality? I'm assuming that this is meant to round to pixel boundaries?

**Review by ajsecord — CHANGES_REQUESTED** [review]

File: components/Slider/examples/SliderCompareExampleViewController.m (hunk 1 above)
Comment (romoore) [reply components/Slider/examples/SliderCompareExampleViewController.m]: Done

File: components/private/Math/src/MDCMath.h (hunk 3 above)
Comment (romoore) [reply components/private/Math/src/MDCMath.h]: Done.

**Comment by romoore** [comment]
While adding unit tests, I found the current approach does not match CGRectIntegral.

File: components/Buttons/examples/supplemental/ButtonsTypicalUseSupplemental.m [hunk 4]
```diff
@@ -130,7 +131,8 @@ - (void)layoutButtonsInRange:(NSRange)range around:(CGFloat)centerX {
     UILabel *label = self.labels[i];
 
     button.frame = CGRectOffset(button.frame, 0, verticalCenterY);
-    label.frame = CGRectOffset(label.frame, 0, verticalCenterY);
+    label.frame = MDCRectAlignToScale(CGRectOffset(label.frame, 0, verticalCenterY),
+                                      [[UIScreen mainScreen] scale]);
```
Comment (willlarche) [inline components/Buttons/examples/supplemental/ButtonsTypicalUseSupplemental.m]: scale is a property. Best to access with .

File: components/Buttons/src/MDCButton.m [hunk 5]
```diff
@@ -299,6 +299,7 @@ - (void)layoutSubviews {
   } else {
     _inkView.frame = self.bounds;
   }
+  self.titleLabel.frame = MDCRectAlignToScale(self.titleLabel.frame, [[UIScreen mainScreen] scale]);
```
Comment (willlarche) [inline components/Buttons/src/MDCButton.m]: Same about scale, tho I know it's inconsistent in the codebase. We can correct them as we go along or feel free to do a PR with a batch change. Same for bounds.

File: components/FeatureHighlight/examples/supplemental/FeatureHighlightExampleSupplemental.m [hunk 6]
```diff
@@ -74,8 +75,8 @@ - (void)viewDidLayoutSubviews {
   self.button.frame = frame;
 
   CGSize labelSize = [self.infoLabel sizeThatFits:self.view.frame.size];
-  self.infoLabel.frame = CGRectMake(self.view.frame.size.width / 2 - labelSize.width / 2, 20,
-                                    labelSize.width, labelSize.height);
+  self.infoLabel.frame = MDCRectAlignToScale(
+                CGRectMake(self.view.frame.size.width / 2 - labelSize.width / 2, 20, labelSize.width, labelSize.height), [[UIScreen mainScreen] scale]);
```
Comment (willlarche) [inline components/FeatureHighlight/examples/supplemental/FeatureHighlightExampleSupplemental.m]: Verify that this is the correct spacing with format_all

File: components/FeatureHighlight/src/private/MDCFeatureHighlightView+Private.m [hunk 7]
```diff
@@ -294,7 +294,7 @@ - (void)layoutSubviews {
     titlePos.y = _highlightPoint.y - kMDCFeatureHighlightInnerPadding - _innerRadius - textHeight;
   }
 
-  CGRect titleFrame = (CGRect){titlePos, titleSize};
+  CGRect titleFrame = MDCRectAlignToScale((CGRect){titlePos, titleSize}, [[UIScreen mainScreen] scale]);
```
Comment (willlarche) [inline components/FeatureHighlight/src/private/MDCFeatureHighlightView+Private.m]: .scale

**Review by willlarche — CHANGES_REQUESTED** [review]

File: components/private/ThumbTrack/src/MDCThumbTrack.m [hunk 8]
```diff
@@ -620,6 +620,9 @@ - (void)updateViewsMainIsAnimated:(BOOL)animated
     _valueLabel.textColor = [UIColor whiteColor];
     if ([_delegate respondsToSelector:@selector(thumbTrack:stringForValue:)]) {
       _valueLabel.text = [_delegate thumbTrack:self stringForValue:_value];
+      if (CGRectGetWidth(_valueLabel.frame) > 1) {
+        _valueLabel.frame = MDCRectAlignToScale(_valueLabel.frame, [[UIScreen mainScreen] scale]);
```
Comment (willlarche) [inline components/private/ThumbTrack/src/MDCThumbTrack.m]: .scale

File: components/private/Math/src/MDCMath.h [hunk 9]
```diff
@@ -94,3 +94,21 @@ static inline CGFloat MDCSqrt(CGFloat value) {
...
+ @see CGRectIntegral
+ */
+static inline CGRect MDCRectAlignToScale(CGRect rect, CGFloat scale) {
+  if (MDCCGFloatEqual(scale, 1)) {
+    return CGRectIntegral(rect);
+  }
+  CGPoint newOrigin = CGPointMake(MDCFloor(rect.origin.x * scale) / scale,
+                                  MDCFloor(rect.origin.y * scale) / scale);
+  CGSize adjustWidthHeight = CGSizeMake(rect.origin.x - newOrigin.x,
+                                         rect.origin.y - newOrigin.y);
```
Comment (willlarche) [inline components/private/Math/src/MDCMath.h]: alignment

**Review by willlarche — CHANGES_REQUESTED** [review]

File: components/Buttons/examples/supplemental/ButtonsTypicalUseSupplemental.m (hunk 4 above)
Comment (romoore) [reply components/Buttons/examples/supplemental/ButtonsTypicalUseSupplemental.m]: Done

File: components/Buttons/src/MDCButton.m (hunk 5 above)
Comment (romoore) [reply components/Buttons/src/MDCButton.m]: Done

File: components/FeatureHighlight/src/private/MDCFeatureHighlightView+Private.m (hunk 7 above)
Comment (romoore) [reply components/FeatureHighlight/src/private/MDCFeatureHighlightView+Private.m]: Done

File: components/FeatureHighlight/examples/supplemental/FeatureHighlightExampleSupplemental.m (hunk 6 above)
Comment (romoore) [reply components/FeatureHighlight/examples/supplemental/FeatureHighlightExampleSupplemental.m]: Done

File: components/private/Math/src/MDCMath.h (hunk 9 above)
Comment (romoore) [reply components/private/Math/src/MDCMath.h]: Done

File: components/private/ThumbTrack/src/MDCThumbTrack.m (hunk 8 above)
Comment (romoore) [reply components/private/ThumbTrack/src/MDCThumbTrack.m]: Done

**Review by willlarche — APPROVED** [review]

File: components/Buttons/examples/supplemental/ButtonsTypicalUseSupplemental.m [hunk 10]
```diff
@@ -130,7 +131,8 @@ - (void)layoutButtonsInRange:(NSRange)range around:(CGFloat)centerX {
     UILabel *label = self.labels[i];
 
     button.frame = CGRectOffset(button.frame, 0, verticalCenterY);
-    label.frame = CGRectOffset(label.frame, 0, verticalCenterY);
+    label.frame = MDCRectAlignToScale(CGRectOffset(label.frame, 0, verticalCenterY),
+                                      [UIScreen mainScreen].scale);
```
Comment (ianegordon) [inline components/Buttons/examples/supplemental/ButtonsTypicalUseSupplemental.m:135]: Note: [UIScreen mainScreen] is now a class property and could be accessed by UIScreen.mainScreen.
We should probably discuss whether we want to adopt class properties at our next weekly.

File: components/FeatureHighlight/src/private/MDCFeatureHighlightView+Private.m [hunk 11]
```diff
@@ -285,7 +286,7 @@ - (void)layoutSubviews {
 
   CGFloat leftTextBound = kMDCFeatureHighlightTextPadding;
   CGFloat rightTextBound = self.frame.size.width - MAX(titleSize.width, detailSize.width) -
-      kMDCFeatureHighlightTextPadding;
+                           kMDCFeatureHighlightTextPadding;
```
Comment (ianegordon) [inline components/FeatureHighlight/src/private/MDCFeatureHighlightView+Private.m]: nit: alignment.  I would expect a 4 character indent.

File: components/private/Math/src/MDCMath.h [hunk 12]
```diff
@@ -94,3 +94,20 @@ static inline CGFloat MDCSqrt(CGFloat value) {
...
+ Expand `rect' to the smallest rect containing it with pixel-aligned origin and size.
+
+ @see CGRectIntegral
+ */
+static inline CGRect MDCRectAlignToScale(CGRect rect, CGFloat scale) {
+  if (MDCCGFloatEqual(scale, 1)) {
+    return CGRectIntegral(rect);
+  }
+  CGPoint newOrigin =
+      CGPointMake(MDCFloor(rect.origin.x * scale) / scale, MDCFloor(rect.origin.y * scale) / scale);
```
Comment (ianegordon) [inline components/private/Math/src/MDCMath.h]: This currently only works with standardized rects.
We likely want
CGFloat xOffset = MDCFloor(CGRectGetXOffset(rect) * scale) / scale;
CGFloat yOffset = MDCFloor(CGRectGetYOffset(rect) * scale) / scale;

There is some additional logic around widths.

Prefer CGRect accessor macros over rect.origin or rect.size unless you have explicitly called CGRectStandardize()

**Review by ianegordon — CHANGES_REQUESTED** [review]

File: components/private/Math/tests/unit/MDCMathTests.m [hunk 13]
```diff
@@ -0,0 +1,52 @@
...
+@end
+
+@implementation MDCMathTests
+
+- (void)testMDCRectAlignScale {
+  // Given
+  CGRect misalignedRect = CGRectMake(0.45, 0.78, 1.01, 5.98);
+  CGRect alignedScale1Rect = CGRectMake(0, 0, 2, 7);
+  CGRect alignedScale2Rect = CGRectMake(0, 0.5, 1.5, 6.5);
+  CGRect alignedScale3Rect = CGRectMake(1.0 / 3.0, 2.0 / 3.0, 4.0 / 3.0, 19.0 / 3.0);
```
Comment (ianegordon) [inline components/private/Math/tests/unit/MDCMathTests.m:34]: Consider adding a test on a non-standardized CGRect.

CGRect nonstandardRect = CGRectMake (100.0, 100.0, -40, -20)

Ensure we are still fully enclosing the original rect, even if the height and/or width is negative.

File: components/Buttons/examples/supplemental/ButtonsTypicalUseSupplemental.m (hunk 10 above)
Comment (romoore) [reply components/Buttons/examples/supplemental/ButtonsTypicalUseSupplemental.m:135]: We may also want to consider avoiding `mainScreen` altogether and using [UIView.window.screen](https://developer.apple.com/documentation/uikit/uiwindow/1621597-screen) instead.

File: components/FeatureHighlight/src/private/MDCFeatureHighlightView+Private.m (hunk 11 above)
Comment (romoore) [reply components/FeatureHighlight/src/private/MDCFeatureHighlightView+Private.m]: Done

File: components/private/Math/src/MDCMath.h (hunk 12 above)
Comment (romoore) [reply components/private/Math/src/MDCMath.h]: Done

File: components/private/Math/tests/unit/MDCMathTests.m (hunk 13 above)
Comment (romoore) [reply components/private/Math/tests/unit/MDCMathTests.m:34]: Done

**Review by ianegordon — APPROVED** [review]

**Comment by ianegordon** [comment]
LGTM.  Please merge once Travis gives the OK.
