### PR TITLE
[BottomNavigation] Explicitly update label visibility after titleVisibility is set

### LINKED ISSUE #4628: [BottomNavigation] Setting to non-default `titleVisibility` does not take effect until selected item is changed
When configuring an MDCBottomNavigationBar to use `titleVisibility` of `.never`, the layout reflects that visibility but the titles of the initially-selected item is still present until another item is selected.

screen shot 2018-07-25 at 9 20 48 am

## Reproduction steps
1. Create an MDCBottomNavigationBar
2. Set `bar.titleVisibility = .never`

## Expected behavior
The bar is originally rendered with all titles hidden

## Actual behavior
The title of the selected item overlaps the image.

### PR DESCRIPTION
**Pull request by andrewoverton**
Closes #4628
jul-25-2018 12-47-33

### CODE REVIEW

**Review by romoore — COMMENTED** [review]
Code looks good, could you please add/update unit tests?

File: components/BottomNavigation/src/private/MDCBottomNavigationItemView.m [hunk 1]
```diff
@@ -221,6 +221,34 @@ - (void)centerLayoutAnimated:(BOOL)animated {
...
 }
 
+- (void)updateLabelVisibility {
+  if (self.selected) {
+    switch (self.titleVisibility) {
+      case MDCBottomNavigationBarTitleVisibilitySelected:
+        self.label.hidden = NO;
+        break;
+      case MDCBottomNavigationBarTitleVisibilityAlways:
+        self.label.hidden = NO;
```
Comment (yarneo) [inline components/BottomNavigation/src/private/MDCBottomNavigationItemView.m]: instead of `break` twice, would you be able to just put both cases one after the other?

File: components/BottomNavigation/src/private/MDCBottomNavigationItemView.m [hunk 2]
```diff
@@ -221,6 +221,34 @@ - (void)centerLayoutAnimated:(BOOL)animated {
...
+        break;
+      case MDCBottomNavigationBarTitleVisibilityNever:
+        self.label.hidden = YES;
+        break;
+    }
+  } else {
+    switch (self.titleVisibility) {
+      case MDCBottomNavigationBarTitleVisibilitySelected:
```
Comment (yarneo) [inline components/BottomNavigation/src/private/MDCBottomNavigationItemView.m:237]: same here

**Review by yarneo — APPROVED** [review]
LGTM % Nits
