### PR TITLE
[Tabs] Fix constraint crash in example.

### LINKED ISSUE #7009: [Tabs] Example crashes on Simulator with constraint violation
The Tabs example crashed when adding a "Star" to the view by tapping on the AppBar button.

```
2019-03-30 21:58:45.815 MDCCatalog[79668:9419151] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** +[NSLayoutConstraint constraintWithItem:attribute:relatedBy:toItem:attribute:multiplier:constant:]: A multiplier of 0 or a nil second item together with a location for the first attribute creates an illegal constraint of a location equal to a constant. Location attributes must be specified in pairs'
*** First throw call stack:
(
	0   CoreFoundation                      0x01c1f746 __exceptionPreprocess + 182
	1   libobjc.A.dylib                     0x018a8a97 objc_exception_throw + 44
	2   CoreFoundation                      0x01c1f66d +[NSException raise:format:] + 141
	3   Foundation                          0x0164e2d7 VerifyConstraintArguments + 191
	4   Foundation                          0x01481fb4 +[NSLayoutConstraint constraintWithItem:attribute:relatedBy:toItem:attribute:multiplier:constant:] + 393
	5   MaterialComponentsExamples          0x00b5b093 -[TabBarIconExample(Supplemental) addStarCentered:] + 1075
	6   MaterialComponentsExamples          0x00b56d61 -[TabBarIconExample incrementDidTouch:] + 145
	7   CoreFoundation                      0x01b0084d __invoking___ + 29
	8   CoreFoundation                      0x01b006f8 -[NSInvocation invoke] + 360
	9   CoreFoundation                      0x01b9932a -[NSInvocation invokeWithTarget:] + 74
	10  MaterialComponents                  0x005e50ea -[MDCButtonBar didTapButton:event:] + 2218
	11  libobjc.A.dylib                     0x018be7cd -[NSObject performSelector:withObject:withObject:] + 84
	12  UIKit                               0x01fdfa90 -[UIApplication sendAction:to:from:forEvent:] + 99
	13  UIKit                               0x01fdfa22 -[UIApplication sendAction:toTarget:fromSender:forEvent:] + 64
	14  UIKit                               0x0212018a -[UIControl sendAction:to:forEvent:] + 69
	15  UIKit                               0x021205a7 -[UIControl _sendActionsForEvents:withEvent:] + 598
	16  UIKit                               0x0211f811 -[UIControl touchesEnded:withEvent:] + 660
	17  MaterialComponents                  0x005d9f5c -[MDCButton touchesEnded:withEvent:] + 172
	18  UIKit                               0x02037cfa -[UIWindow _sendTouchesForEvent:] + 874
	19  UIKit                               0x020387d6 -[UIWindow sendEvent:] + 792
	20  MDCCatalog                          0x000b17c8 $S10MDCCatalog0A6WindowC9sendEventyySo7UIEventCF + 1160
	21  MDCCatalog                          0x000b1cad $S10MDCCatalog0A6WindowC9sendEventyySo7UIEventCFTo + 61
	22  UIKit                               0x01ff66d1 -[UIApplication sendEvent:] + 242
	23  UIKit                               0x02006b08 _UIApplicationHandleEventFromQueueEvent + 21484
	24  UIKit                               0x01fda337 _UIApplicationHandleEventQueue + 2300
	25  CoreFoundation                      0x01b4106f __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 15
	26  CoreFoundation                      0x01b36b7d __CFRunLoopDoSources0 + 253
	27  CoreFoundation                      0x01b360d8 __CFRunLoopRun + 952
	28  CoreFoundation                      0x01b35a5b CFRunLoopRunSpecific + 443
	29  CoreFoundation                      0x01b3588b CFRunLoopRunInMode + 123
	30  GraphicsServices                    0x059252c9 GSEventRunModal + 192
	31  GraphicsServices                    0x05925106 GSEventRun + 104
	32  UIKit                               0x01fde106 UIApplicationMain + 1526
	33  MDCCatalog                          0x000dbd9a main + 90
	34  libdyld.dylib                       0x04a39ac9 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

---
#### Internal data
- Associated internal bug: [b/129679561](http://b/129679561)

### PR DESCRIPTION
**Pull request by romoore**
When adding a Star, the example would crash because one of the two
x/y values would nearly always be 0. This was caused by converting a
double into an integer in an earlier PR.

Closes #7009

### CODE REVIEW

File: components/Tabs/examples/supplemental/TabBarIconExampleSupplemental.m [hunk 1]
```diff
@@ -234,8 +234,8 @@ - (void)addStarCentered:(BOOL)centered {
   [self.starPage addSubview:starView];
   [starView sizeToFit];
 
-  CGFloat x = centered ? 1 : (arc4random_uniform(199) + 1) / 100;  // 0 < x <=2
-  CGFloat y = centered ? 1 : (arc4random_uniform(199) + 1) / 100;  // 0 < y <=2
+  CGFloat x = centered ? 1 : (CGFloat)((arc4random_uniform(199) + 1) / 100.0);  // 0 < x <=2
+  CGFloat y = centered ? 1 : (CGFloat)((arc4random_uniform(199) + 1) / 100.0);  // 0 < y <=2
```
Comment (andrewoverton) [inline components/Tabs/examples/supplemental/TabBarIconExampleSupplemental.m:238]: I notice you're using this value between 0 and 2 as the multiplier and 0 as the constant with NSLayoutAttributeCenterX and NSLayoutAttributeCenterY. I understand how the multiplier is used for proportional constraints, but I don't understand its use right here. How does this value being 1 or 2 make a difference, and why is it random?

Comment (romoore) [reply components/Tabs/examples/supplemental/TabBarIconExampleSupplemental.m:238]: Here's an example:

```
Bounds = {0, 0, 100, 100}
x = {0.25}
y = {1.33}

Star position = {superview.center.x * 0.25, superview.center.y * 1.33}
Star position = {0.5 * 0.25, 0.5 * 1.33}
Star position = {0.125, .665}
```

Comment (romoore) [reply components/Tabs/examples/supplemental/TabBarIconExampleSupplemental.m:238]: It's random so the stars don't overlap? I guess the alternative would be a "grid" of stars, but I don't think there's any particular reason to choose one over the other.

Comment (andrewoverton) [reply components/Tabs/examples/supplemental/TabBarIconExampleSupplemental.m:238]: Huh okay, i didn't realize you could do that with the center attributes. And what are these stars for again? I just don't know

Comment (romoore) [reply components/Tabs/examples/supplemental/TabBarIconExampleSupplemental.m:238]: They're stars that appear in the example.

Simulator Screen Shot - iPhone 7 - 2019-04-03 at 10 30 42

Comment (andrewoverton) [reply components/Tabs/examples/supplemental/TabBarIconExampleSupplemental.m:238]: Oh I see haha. Cool.

**Review by andrewoverton — APPROVED** [review]
