### PR TITLE
[TextFields] Update announcement text for fields with a character limit

### LINKED ISSUE #7624: [TextFields] Character count limit repeatedly indicates that "zero characters are remaining"
## Repro steps

1. Open MDCDragons.
2. Open Kitchen Sink Text Fields example.
3. Focus the single line text field with a character count.
4. Type 49 characters.
5. Enable VoiceOver.
6. Type 5 more characters.

## Expected behavior

After the first character is typed, VoiceOver announces "0 characters remaining".
After the second character is typed, VoiceOver announces something to indicate that the text is overflowing even further.

## Actual behavior

VoiceOver announces "0 characters remaining" after every new character.

---
#### Internal data
- Associated internal bug: [b/135492412](http://b/135492412)

### PR DESCRIPTION
**Pull request by bryanoltman**
Updates the VoiceOver announcement for character-limited text fields from "X characters remaining" to "X of Y characters". 

Fixes #7624

### CODE REVIEW

**Comment by yarneo** [comment]
what does it say when there is an overflow?

**Comment by bryanoltman** [comment]
> what does it say when there is an overflow?

It doesn't alter its behavior. For a text field with a character limit of 25, it will say "26 of 25 characters", "27 of 25 characters", etc.

**Comment by yarneo** [comment]
curious to know what Apple does in this case, is there some precedence we can follow?

**Review by yarneo — APPROVED** [review]

**Comment by bryanoltman** [comment]
> curious to know what Apple does in this case, is there some precedence we can follow?

Apple does not support

**Comment by randallli** [comment]
next steps would be to localize this? https://nshipster.com/nslocalizedstring/

File: components/TextFields/src/MDCTextInputControllerBase.m [hunk 1]
```diff
@@ -1578,12 +1578,9 @@ - (void)textInputDidChange:(NSNotification *)note {
         [self.characterCounter characterCountForTextInput:self.textInput];
     NSString *announcementString;
     if (!announcementString.length) {
-      announcementString =
-          [NSString stringWithFormat:@"%lu characters remaining",
-                                     charactersForTextInput > self.characterCountMax
-                                         ? 0U
```
Comment (romoore) [inline components/TextFields/src/MDCTextInputControllerBase.m:1584]: So we're OK saying, "-3 of 5 characters"?

Comment (bryanoltman) [reply components/TextFields/src/MDCTextInputControllerBase.m:1584]: We were previously just repeating "0 characters remaining". The example you provided would be announced as "8 of 5 characters".

Comment (romoore) [reply components/TextFields/src/MDCTextInputControllerBase.m:1584]: Thanks, I was misreading the changed code. Should we update FullWidth as well?
