### PR TITLE
[Catalog] Fix collection view layout in MDCThemePickerViewController

### LINKED ISSUE #5143: [Catalog] Our catalog-wide theming UI is broken and unusable
When pressing on the Themes category through the menu, we are supposed to reach a screen with selectable colors. However the offsets are incorrect causing the UI to be hidden under the AppBar.
Also seems like the constraints for the collectionView itself are now wrong or just broken. Not sure if this is a product of the wrong offsetting or a separate issue.

Provided screenshots for iPhone 8 Plus:
screen shot 2018-09-17 at 11 20 38 am

iPhone X:
screen shot 2018-09-17 at 11 21 06 am

### PR DESCRIPTION
**Pull request by andrewoverton**
These changes fix the layout of MDCThemePickerViewController.
Closes #5143

### CODE REVIEW

File: catalog/MDCCatalog/MDCThemePickerViewController.swift [hunk 1]
```diff
@@ -111,68 +115,39 @@ class MDCThemePickerViewController: UIViewController, UICollectionViewDataSource
 
   override func viewDidLoad() {
     super.viewDidLoad()
+    title = "Material Palette-based themes"
+    view.backgroundColor = .white
```
Comment (codeman7) [inline catalog/MDCCatalog/MDCThemePickerViewController.swift]: _Tip_ `view.backgroundColor = AppTheme.globalTheme.colorScheme.backgroundColor`

File: catalog/MDCCatalog/MDCThemePickerViewController.swift [hunk 2]
```diff
@@ -111,68 +115,39 @@ class MDCThemePickerViewController: UIViewController, UICollectionViewDataSource
 
   override func viewDidLoad() {
     super.viewDidLoad()
+    title = "Material Palette-based themes"
```
Comment (codeman7) [inline catalog/MDCCatalog/MDCThemePickerViewController.swift]: _Tip_ New line after `super` call.

File: catalog/MDCCatalog/MDCThemePickerViewController.swift [hunk 3]
```diff
@@ -111,68 +115,39 @@ class MDCThemePickerViewController: UIViewController, UICollectionViewDataSource
...
-    view.addConstraint(NSLayoutConstraint(item: paletteTitle,
-                                          attribute: .left,
-                                          relatedBy: .equal,
-                                          toItem: self.view,
-                                          attribute: .left,
-                                          multiplier: 1.0,
-                                          constant: 16))
+  override func viewDidLayoutSubviews() {
+    super.viewDidLayoutSubviews()
+    positionCollectionView()
```
Comment (codeman7) [inline catalog/MDCCatalog/MDCThemePickerViewController.swift]: _Tip_ New line after super call

File: catalog/MDCCatalog/MDCThemePickerViewController.swift [hunk 4]
```diff
@@ -111,68 +115,39 @@ class MDCThemePickerViewController: UIViewController, UICollectionViewDataSource
...
-                                          toItem: nil,
-                                          attribute: .notAnAttribute,
-                                          multiplier: 1,
-                                          constant: numberOfRows * (cellSize + (cellSpacing * 2))))
-    view.backgroundColor = .white
+  }
+
+  func positionCollectionView() {
+    var originX = view.bounds.origin.x
+    let originY = view.bounds.origin.y
```
Comment (codeman7) [inline catalog/MDCCatalog/MDCThemePickerViewController.swift]: _Tip_ Get rid of this variable and just use `view.bounds.origin.y` when creating the frame.

**Review by codeman7 — APPROVED** [review]

File: catalog/MDCCatalog/MDCThemePickerViewController.swift (hunk 1 above)
Comment (andrewoverton) [reply catalog/MDCCatalog/MDCThemePickerViewController.swift]: Hmmm, `AppTheme.globalTheme.colorScheme.backgroundColor` is black, and the background color has been white up to this point. I'm not sure I'd want to change the behavior like that in this PR.

**Comment by andrewoverton** [comment]
Also, I forgot to put a screenshot: 
simulator screen shot - iphone x - 2018-09-19 at 09 56 22

File: catalog/MDCCatalog/MDCThemePickerViewController.swift (hunk 1 above)
Comment (codeman7) [reply catalog/MDCCatalog/MDCThemePickerViewController.swift]: Yeah I don't think we want black, I wonder why it isn't always white???

Comment (andrewoverton) [reply catalog/MDCCatalog/MDCThemePickerViewController.swift]: I think with catalog we just specify black as the theme's background color on app launch
