### PR TITLE
[Collections] Add StylingDelegate methods to control separator display

### LINKED ISSUE #1406: [Collections]
### Overview
When the background is hidden on the header or a cell in a collection view, a thin bar is displayed in the item.
For example if you remove the background of the header in a collection, there is a line above the item like in this screenshot (Header/Footer example in the catalog with header background hidden).
simulator screen shot may 9 2017 11 55 21 am

### Reproduction steps
 - Hide the background for the headers in CollectionsHeaderFooterExample.m in the catalog
 - Open the example
 - Look at the separation of the header and the section
 - An unexpected line is displayed

### Version number
 - 23.0.2

### PR DESCRIPTION
**Pull request by gambard**
Adds methods to MDCCollectionViewStylingDelegate, allowing the delegate to control the display of the separator on cells, header and footer.

Closes #1406

### CODE REVIEW

File: components/Collections/src/MDCCollectionViewStylingDelegate.h [hunk 1]
```diff
@@ -90,6 +90,38 @@
...
+
+/**
+ Asks the delegate whether the specified footer should hide its separator.
+
+ @param collectionView The collection view.
+ @param section The collection view section.
+ @return If the footer separator should be hidden at the specified section.
+ */
+- (BOOL)collectionView:(nonnull UICollectionView *)collectionView
+    shouldHideFooterSeparatorForSection:(NSInteger)section;
```
Comment (gambard) [inline components/Collections/src/MDCCollectionViewStylingDelegate.h:123]: I am not sure a footer can have a separator but in case, I think it is better to have this method.

File: components/Collections/src/MDCCollectionViewFlowLayout.m [hunk 2]
```diff
@@ -531,8 +531,8 @@ - (void)updateCellStateMaskWithAttribute:(MDCCollectionViewLayoutAttributes *)at
           (id<MDCCollectionViewEditingDelegate>)self.collectionView.dataSource;
 
       // Check if delegate can select during editing.
-      if ([editingDelegate respondsToSelector:@selector(collectionView:
-                                                  canSelectItemDuringEditingAtIndexPath:)]) {
+      if ([editingDelegate respondsToSelector:@selector
+                           (collectionView:canSelectItemDuringEditingAtIndexPath:)]) {
```
Comment (romoore) [inline components/Collections/src/MDCCollectionViewFlowLayout.m:535]: This looks like the automatic formatter, do we normally break-up the @selector from the method name?

File: components/Collections/src/private/MDCCollectionViewStyler.m [hunk 3]
```diff
@@ -246,6 +246,35 @@ - (void)setCellStyle:(MDCCollectionViewCellStyle)cellStyle {
...
+      [attr.representedElementKind isEqualToString:UICollectionElementKindSectionHeader];
+  BOOL isSectionFooter =
+      [attr.representedElementKind isEqualToString:UICollectionElementKindSectionFooter];
+  BOOL isCell = attr.representedElementCategory == UICollectionElementCategoryCell;
+  if (isSectionHeader && [self.delegate respondsToSelector:@selector
+                                        (collectionView:shouldHideHeaderSeparatorForSection:)]) {
+    shouldHideSeparator = [self.delegate collectionView:_collectionView
+                    shouldHideHeaderSeparatorForSection:indexPath.section];
+  }
+  if (isSectionFooter && [self.delegate respondsToSelector:@selector
```
Comment (romoore) [inline components/Collections/src/private/MDCCollectionViewStyler.m]: Can the same indexPath be a header/footer/cell simultaneously?  If not, it may be better to if/else-if on the cell type first, then have nested conditionals for `respondsToSelector:` inside each.  Placing the `isCell` condition first seems like the primary case and so might be incrementally faster.

File: components/Collections/examples/CollectionsCellSeparatorExample.m [hunk 4]
```diff
@@ -80,4 +85,44 @@ - (UICollectionViewCell *)collectionView:(UICollectionView *)collectionView
...
+  if (section == 3 || section == 4) {
+    return CGSizeMake(collectionView.bounds.size.width, MDCCellDefaultOneLineHeight);
+  }
+  return CGSizeZero;
+}
+
+#pragma mark - <MDCCollectionViewStylingDelegate>
+
+- (BOOL)collectionView:(UICollectionView *)collectionView
+    shouldHideItemSeparatorAtIndexPath:(NSIndexPath *)indexPath {
```
Comment (romoore) [inline components/Collections/examples/CollectionsCellSeparatorExample.m:119]: Please indent the second line 4 spaces (align with the "L" in `BOOL`) since we cannot align the colons.

File: components/Collections/examples/CollectionsCellSeparatorExample.m [hunk 5]
```diff
@@ -80,4 +85,44 @@ - (UICollectionViewCell *)collectionView:(UICollectionView *)collectionView
...
+  return indexPath.section == 3;
+}
+
+- (BOOL)collectionView:(UICollectionView *)collectionView
+    shouldHideHeaderSeparatorForSection:(NSInteger)section {
```
Comment (romoore) [inline components/Collections/examples/CollectionsCellSeparatorExample.m:124]: Please indent 4 spaces here as well

File: components/Collections/src/MDCCollectionViewStyling.h [hunk 6]
```diff
@@ -142,6 +142,16 @@ typedef NS_ENUM(NSUInteger, MDCCollectionViewCellLayoutType) {
...
 
+/**
+ Returns whether the separator should be hidden for the cell with this layout attributes, determined
+ by the cell position and type.
+
+ @param attr The cell's layout attributes.
+ @return Whether the separtor should be hidden.
+ */
+- (BOOL)shouldHideSeparatorForCellLayoutAttributes:
+        (nonnull MDCCollectionViewLayoutAttributes *)attr;
```
Comment (romoore) [inline components/Collections/src/MDCCollectionViewStyling.h:155]: This looks like it was indented a bit too much (more than 4 spaces).

File: components/Collections/src/private/MDCCollectionViewStyler.m [hunk 7]
```diff
@@ -246,6 +246,35 @@ - (void)setCellStyle:(MDCCollectionViewCellStyle)cellStyle {
   _cellStyle = cellStyle;
 }
 
+- (BOOL)shouldHideSeparatorForCellLayoutAttributes:(MDCCollectionViewLayoutAttributes *)attr {
+  BOOL shouldHideSeparator = self.shouldHideSeparators;
+  if (!self.delegate)
+    return shouldHideSeparator;
```
Comment (romoore) [inline components/Collections/src/private/MDCCollectionViewStyler.m]: Please add curly braces  (`{}`) to surround the expression following the conditional (`if`)

**Review by romoore — CHANGES_REQUESTED** [review]
A few small comments, and I would like to see Unit Tests added to the styler to verify the behavior with and without a styling delegate.

**Comment by romoore** [comment]
Keeping myself assigned so I can track this issue.

File: components/Collections/examples/CollectionsCellSeparatorExample.m (hunk 5 above)
Comment (gambard) [reply components/Collections/examples/CollectionsCellSeparatorExample.m:124]: Same.

File: components/Collections/examples/CollectionsCellSeparatorExample.m (hunk 4 above)
Comment (gambard) [reply components/Collections/examples/CollectionsCellSeparatorExample.m:119]: I am already using a 4 space indentation, and this is what clang-format is giving. It also seems consistent with the rest of the methods.

File: components/Collections/src/MDCCollectionViewFlowLayout.m (hunk 2 above)
Comment (gambard) [reply components/Collections/src/MDCCollectionViewFlowLayout.m:535]: I don't know. This is indeed the clang-format result.

File: components/Collections/src/MDCCollectionViewStyling.h (hunk 6 above)
Comment (gambard) [reply components/Collections/src/MDCCollectionViewStyling.h:155]: Auto-formatter.

File: components/Collections/src/private/MDCCollectionViewStyler.m (hunk 7 above)
Comment (gambard) [reply components/Collections/src/private/MDCCollectionViewStyler.m]: Done.

File: components/Collections/src/private/MDCCollectionViewStyler.m (hunk 3 above)
Comment (gambard) [reply components/Collections/src/private/MDCCollectionViewStyler.m]: The same indexPath can be a header/footer/cell, but an attribute is only one of them.
Done.

**Review by gambard — COMMENTED** [review]
Thanks, PTAL.

File: components/Collections/examples/CollectionsCellSeparatorExample.m (hunk 4 above)
Comment (romoore) [reply components/Collections/examples/CollectionsCellSeparatorExample.m:119]: You're right. I misremembered the indentation rules from the style guide. Sorry!

**Comment by romoore** [comment]
Source looks good, could you please add unit tests?   I think `shouldHideSeparatorForCellLayoutAttributes:` in `MDCCollectionViewStyler.h` looks fairly testable.  Testing `updateAttribute:` in `MDCCollectionViewFlowLayout` would be great if you could as well.

**Comment by gambard** [comment]
Tests added for shouldHideSeparatorForCellLayoutAttributes.

**Comment by gambard** [comment]
I think testing updateAttribute would be too complex for this CL.

File: components/Collections/tests/unit/CollectionsStylerTests.m [hunk 8]
```diff
@@ -0,0 +1,136 @@
...
+                         collectionViewLayout:[[UICollectionViewFlowLayout alloc] init]];
+  MDCCollectionViewStyler* styler =
+      [[MDCCollectionViewStyler alloc] initWithCollectionView:collectionView];
+  styler.delegate = nil;
+
+  // When
+  styler.shouldHideSeparators = YES;
+
+  // Then
+  XCTAssertTrue([styler shouldHideSeparatorForCellLayoutAttributes:cell01()]);
```
Comment (romoore) [inline components/Collections/tests/unit/CollectionsStylerTests.m]: Please verify all 6 cases in each test, I think it makes it clearer that all cells are configured by the property.

File: components/Collections/src/MDCCollectionViewStyling.h [hunk 9]
```diff
@@ -142,6 +142,16 @@ typedef NS_ENUM(NSUInteger, MDCCollectionViewCellLayoutType) {
 /* Whether to hide the cell separators. Defaults to NO. */
 @property(nonatomic) BOOL shouldHideSeparators;
 
+/**
+ Returns whether the separator should be hidden for the cell with this layout attributes, determined
+ by the cell position and type.
```
Comment (romoore) [inline components/Collections/src/MDCCollectionViewStyling.h:147]: ~~Please add a comment to mention that setting `shouldHideSeparators` to `NO` should cause this method to always return `NO`.~~

Please add a comment that this method may override the `shouldHideSeparators` property depending on which delegate methods are implemented.

**Review by romoore — CHANGES_REQUESTED** [review]
Very minor feedback on tests.

File: components/Collections/tests/unit/CollectionsStylerTests.m (hunk 8 above)
Comment (gambard) [reply components/Collections/tests/unit/CollectionsStylerTests.m]: Done.

File: components/Collections/src/MDCCollectionViewStyling.h (hunk 9 above)
Comment (gambard) [reply components/Collections/src/MDCCollectionViewStyling.h:147]: Done.

**Review by romoore — APPROVED** [review]
