### PR TITLE
[Buttons] Fix a11y issues in Buttons (Content Edge Insets) example 

### LINKED ISSUE #8831: [Catalog] Internal issue: b/144514801
This was filed as an internal issue. If you are a Googler, please visit [b/144514801](http://b/144514801) for more details.

---
#### Internal data
- Associated internal bug: [b/144514801](http://b/144514801)

### PR DESCRIPTION
**Pull request by yarneo**
In this PR we are fixing the non-accessible colors that were caused due to the container scheme being nil, as init isn't being called with a Storyboard, but rather initWithCode.

Secondly, now the FAB has a good a11y label, so it can be presented correctly when focused.

Before:
Simulator Screen Shot - iPhone 7 - 2019-11-15 at 09 53 25

After:
Simulator Screen Shot - iPhone 7 - 2019-11-15 at 09 52 50

Closes #8831

### CODE REVIEW

File: components/Buttons/examples/ButtonsContentEdgeInsetsExample.m [hunk 1]
```diff
@@ -41,8 +41,9 @@ + (NSDictionary *)catalogMetadata {
 
 #pragma mark - UIViewController
 
-- (id)init {
-  self = [super init];
+- (instancetype)initWithCoder:(NSCoder *)coder
```
Comment (jverkoey) [inline components/Buttons/examples/ButtonsContentEdgeInsetsExample.m]: Our team norm is to implement all designated initializers and call a `common<#ClassName#>Initializer` method; this will reduce the likelihood of similar errors in the future. I believe we should be able to get by with just implementing initWithNibName:... and initWithCoder:

File: components/Buttons/examples/ButtonsContentEdgeInsetsExample.m [hunk 2]
```diff
@@ -41,8 +41,9 @@ + (NSDictionary *)catalogMetadata {
...
+{
```
Comment (jverkoey) [inline components/Buttons/examples/ButtonsContentEdgeInsetsExample.m]: Nit: clang formatting here.

File: components/Buttons/examples/ButtonsContentEdgeInsetsExample.m [hunk 3]
```diff
@@ -60,6 +61,7 @@ - (void)viewDidLoad {
   [self.floatingActionButton setContentEdgeInsets:UIEdgeInsetsMake(40, 40, 0, 0)
                                          forShape:MDCFloatingButtonShapeDefault
                                            inMode:MDCFloatingButtonModeNormal];
+  self.floatingActionButton.accessibilityLabel = @"Floating Button";
```
Comment (jverkoey) [inline components/Buttons/examples/ButtonsContentEdgeInsetsExample.m]: We're all over the place with our accessibility labels, but I believe we should try to align on using "Sentence case" rather than "Title Case".

**Review by jverkoey — APPROVED** [review]

File: components/Buttons/examples/ButtonsContentEdgeInsetsExample.m [hunk 4]
```diff
@@ -41,14 +41,25 @@ + (NSDictionary *)catalogMetadata {
 
 #pragma mark - UIViewController
 
-- (id)init {
-  self = [super init];
+- (instancetype)initWithCoder:(NSCoder *)coder {
+  self = [super initWithCoder:coder];
```
Comment (jverkoey) [inline components/Buttons/examples/ButtonsContentEdgeInsetsExample.m:45]: Missing `[self commonButtonContentEdgeInsetsExampleInitializer];` here.

**Review by jverkoey — APPROVED** [review]
