### PR TITLE
[Ink] Fix demo being clipped by safe area issue (#384)

### LINKED ISSUE #384: Catalog in landscape iPhone 4S: Ink demo doesn't fit in either portrait or landscape
simulator screen shot apr 18 2016 12 20 18 pm

### PR DESCRIPTION
**Pull request by fluxminds**
closes #384.

Changes:
Add a container subview to make the layout easier and aware of the safeArea.

Before:
simulator screen shot - iphone 5 - 2018-08-27 at 12 14 13
simulator screen shot - iphone 5 - 2018-08-27 at 12 14 15

After:
simulator screen shot - iphone 5 - 2018-08-27 at 12 07 07
simulator screen shot - iphone 5 - 2018-08-27 at 12 07 08

### CODE REVIEW

File: components/Ink/examples/supplemental/InkTypicalUseSupplemental.m [hunk 1]
```diff
@@ -130,19 +130,36 @@ - (void)setupExampleViews {
 }
 
 - (void)viewWillLayoutSubviews {
+#if defined(__IPHONE_11_0) && (__IPHONE_OS_VERSION_MAX_ALLOWED >= __IPHONE_11_0)
```
Comment (jverkoey) [inline components/Ink/examples/supplemental/InkTypicalUseSupplemental.m]: I think we don't need these `#if defined(__IPHONE_11_0) && (__IPHONE_OS_VERSION_MAX_ALLOWED >= __IPHONE_11_0)` guards anymore.

**Review by jverkoey — APPROVED** [review]

File: components/Ink/examples/supplemental/InkTypicalUseSupplemental.m (hunk 1 above)
Comment (fluxminds) [reply components/Ink/examples/supplemental/InkTypicalUseSupplemental.m]: Oh Thanks! I will remove it before merging. Is it because we deprecated Xcode8?

Comment (romoore) [reply components/Ink/examples/supplemental/InkTypicalUseSupplemental.m]: Yep, that's the reason.

Comment (fluxminds) [reply components/Ink/examples/supplemental/InkTypicalUseSupplemental.m]: Cool. Thanks!
