### PR TITLE
[FeatureHighlight] Fix crash when backgrounding and re-opening app.

### LINKED ISSUE #4791: Internal issue: b/112592084
This is an internal issue. If you are a Googler, please visit [b/112592084](http://b/112592084) for more details.

### PR DESCRIPTION
**Pull request by andrewoverton**
Closes #4791 

This PR (#4796) closes issue #4791, which was related to a crash that resulted from a fix to an internal client bug where the layout of the feature highlight was incorrect after rotations.

The approach taken was to revert the change that resulted in the crash and add a safeguard against incorrect layout by applying the positioning code both in the animation block (which will be sufficient for most cases) as well as after (which will be sufficient for cases where the frames we rely on in the positioning code are incorrect during the animation.)

### CODE REVIEW

File: components/FeatureHighlight/src/private/MDCFeatureHighlightAnimationController.m [hunk 1]
```diff
@@ -66,26 +67,38 @@ - (void)animateTransition:(id<UIViewControllerContextTransitioning>)transitionCo
...
-      completion:^(__unused BOOL finished) {
-        // If we're dismissing, remove the highlight view from the hierarchy
-        if (!self.presenting) {
-          [fromView removeFromSuperview];
-        }
-        [transitionContext completeTransition:YES];
-      }];
+
+  BOOL presenting = self.presenting;
+  void (^animations)(void) = ^void(void) {
```
Comment (ianegordon) [inline components/FeatureHighlight/src/private/MDCFeatureHighlightAnimationController.m]: To avoid context switching, if your block is short, consider placing it inline, as it was before this change.
Capturing BOOL presenting outside of the blocks to avoid referencing self is probably a good idea.

File: components/FeatureHighlight/src/MDCFeatureHighlightViewController.m [hunk 2]
```diff
@@ -169,15 +169,26 @@ - (void)viewWillTransitionToSize:(CGSize)size
        withTransitionCoordinator:(id<UIViewControllerTransitionCoordinator>)coordinator {
   [super viewWillTransitionToSize:size withTransitionCoordinator:coordinator];
   UIViewController *presenter = self.presentingViewController;
-  UIViewController *presentingViewController = self;
+  UIViewController *presentedViewController = self;
   [self dismissViewControllerAnimated:NO completion:nil];
```
Comment (ianegordon) [inline components/FeatureHighlight/src/MDCFeatureHighlightViewController.m]: I'm not sure I follow.
Do we want to dismiss then immediately present self to re-display the feature highlight based on the new size?
Why aren't we just moving the center of the featureHightlightView?

**Review by ianegordon — DISMISSED** [review]

File: components/FeatureHighlight/src/MDCFeatureHighlightViewController.m (hunk 2 above)
Comment (andrewoverton) [reply components/FeatureHighlight/src/MDCFeatureHighlightViewController.m]: Hmm, so the person who reported the bug thinks that it was introduced in e91de06. That commit appears to replace code that sounds _similar_ to what you're describing with this current dismiss/present again strategy. I was assuming that was done for a good reason, but it's possible it wasn't.

File: components/FeatureHighlight/src/private/MDCFeatureHighlightAnimationController.m (hunk 1 above)
Comment (andrewoverton) [reply components/FeatureHighlight/src/private/MDCFeatureHighlightAnimationController.m]: I figured that because the code in both the `animations` and `completion` blocks could be called in two different places depending on whether the app was backgrounded or not it made sense to DRY them out into block variables.

File: components/FeatureHighlight/src/MDCFeatureHighlightViewController.m (hunk 2 above)
Comment (jverkoey) [reply components/FeatureHighlight/src/MDCFeatureHighlightViewController.m]: The background on that change, if I recall correctly, was that there were animation glitches caused by attempting to animate the frame (i.e. the frame of the "source view" changes).

That being said, I agree with @ianegordon that it's likely in our best interest long-term to explore whether we can properly re-animate the frame.

**Comment by jverkoey** [comment]
Can you go more into detail on the root cause analysis that indicated that a `dispatch_after` was required? `dispatch_after`, like KVO, is regarded as a last-ditch effort to fix a bug — typically something in Apple's frameworks that we can't get around. When we use these types of APIs it's important that we document why it's necessary so that if Apple fixes the bug down the road we can remove the patch code.

**Comment by andrewoverton** [comment]
@jverkoey, yeah, dispatch_after isn't great. With just 67f14c8 there the crashing code was executed maybe 15% of the time? Really did just seem to be a timing issue. In most cases after the dismissal the presentedViewController/presentingViewController properties were nil, and in some they weren't. I don't know how much I'd be able to diagnose it further... I could try if you want, or we could reconsider the original issue, [b/79933393](http://b/79933393), addressed with #4300. Even the person who filed the bug wasn't sure it was a bug in FeatureHighlight. I can't reproduce the original bug, and neither could Mohammed. We could consider reverting?

**Comment by andrewoverton** [comment]
@jverkoey, I may not have been sufficiently clear about the different types of crashes that I was seeing while working on this. The crash that #4791 was filed for occurs because when the app is backgrounded animations and their completion blocks are stopped, resulting in several attempts to present the same view controller when the app is foregrounded again, which leads to an exception being thrown.

The occasional crash occurring after 67f14c8 was different. That one occurred rarely and randomly when the value for [`presenter.presentedViewController`](https://github.com/material-components/material-components-ios/pull/4796/commits/f9b9921e683622898f8e53f4bc8dff533e563c20#diff-e3cf594bf779e56a8adf1a448a3d32caR178) failed to be updated in time following a dismissal. This is the one I believed to be a race condition. That was a more opaque crash without any helpful error message.

The [_original_ bug](http://b/79933393), which I couldn't reproduce, was about improper layout. Mohammed's interpretation of it, which he laid out on the bug, was that both we and the client were using `-viewWillTransitionToSize:withTransitionCoordinator:`, and that we were relying on frames in 
 that method that they were changing in their implementation of it. What my most recent commit, 6da1473bb60fae7a37b46110e419109e7b994dc3, does is applies the same positioning code both during the animation AND after, when the frames will presumably be reliable, thereby avoiding the layout glitch _and_ the crashing fix for it. Hopefully~

The fix I opened the PR with seemed like a pretty safe bet--no crashing, would unlikely affect the edge case reported in b/79933393--but it had the dispatch_after and app state check, which are gross. 
This fix doesn't have any gross stuff, addresses the crash in #4791, and I am pretty sure should fix the original issue, although again, I couldn't reproduce it.

**Review by jverkoey — APPROVED** [review]
As discussed offline, if we can explore an API that clients can invoke to let us know when the target frame has changed then I think we may be able to avoid the "snap" fix that this PR implements.

That being said, this fix resolves the crash and I'd prefer that we proceed with this and then iterate on a better explicit approach to changing the frame during rotation.

**Comment by jverkoey** [comment]
@andrewoverton Please add a note to the PR description indicating that this PR does fix the crash, but it introduces a potential "snap" effect at the end of the rotation animation.

**Comment by romoore** [comment]
Could you please post a gif of the animation? I think it's worth capturing how (in)significant it may be.

**Comment by andrewoverton** [comment]
This gif is going very slowly for me but it gets the point across...

feature_highlight
