### PR TITLE
[PageControl] Fix bad indicator state when changing numberOfPages.

### LINKED ISSUE #1996: [PageControl] Incorrect indicator on current page when changing numberOfPages.
image

I changed the [PageControlTypicalUseExample.swift](https://github.com/material-components/material-components-ios/blob/develop/components/PageControl/examples/PageControlTypicalUseExample.swift) to the following to remove a page after some time. As you can see, page 0 has an active marker and there is no marker at all for the real active page 1

```diff
diff --git a/components/PageControl/examples/PageControlTypicalUseExample.swift b/components/PageControl/examples/PageControlTypicalUseExample.swift
index b57637ccea..994422bc21 100644
--- a/components/PageControl/examples/PageControlTypicalUseExample.swift
+++ b/components/PageControl/examples/PageControlTypicalUseExample.swift
@@ -41,11 +41,10 @@ class PageControlSwiftExampleViewController: UIViewController, UIScrollViewDeleg
     scrollView.autoresizingMask = [.flexibleWidth, .flexibleHeight]
     scrollView.delegate = self
     scrollView.isPagingEnabled = true
-    scrollView.contentSize = CGSize(width: view.bounds.width * CGFloat(pageColors.count),
-                                    height: view.bounds.height)
     scrollView.showsHorizontalScrollIndicator = false
     view.addSubview(scrollView)

+    var lastPage: UIView?
     // Add pages to scrollView.
     for (i, pageColor) in pageColors.enumerated() {
       let pageFrame: CGRect = self.view.bounds.offsetBy(dx: CGFloat(i) * view.bounds.width, dy: 0)
@@ -58,18 +57,32 @@ class PageControlSwiftExampleViewController: UIViewController, UIScrollViewDeleg
       page.autoresizingMask = [.flexibleTopMargin, .flexibleBottomMargin]
       scrollView.addSubview(page)
       pages.add(page)
+      lastPage = page
     }

     pageControl.numberOfPages = pageColors.count

-    let pageControlSize = pageControl.sizeThatFits(view.bounds.size)
-    pageControl.frame = CGRect(x: 0,
-                               y: view.bounds.height - pageControlSize.height,
-                               width: view.bounds.width,
-                               height: pageControlSize.height)
-    pageControl.addTarget(self, action: #selector(didChangePage), for: .valueChanged)
-    pageControl.autoresizingMask = [.flexibleTopMargin, .flexibleWidth]
+    let resizePageControl = {
+      self.scrollView.contentSize =
+          CGSize(width: self.view.bounds.width * CGFloat(self.pageControl.numberOfPages),
+                 height: self.view.bounds.height)
+      let pageControlSize = self.pageControl.sizeThatFits(self.view.bounds.size)
+      self.pageControl.frame = CGRect(x: 0,
+                                 y: self.view.bounds.height - pageControlSize.height,
+                                 width: self.view.bounds.width,
+                                 height: pageControlSize.height)
+      self.pageControl.addTarget(self, action: #selector(self.didChangePage), for: .valueChanged)
+      self.pageControl.autoresizingMask = [.flexibleTopMargin, .flexibleWidth]
+    }
+    resizePageControl()
+
     view.addSubview(pageControl)
+    pageControl.currentPage = 1
+    DispatchQueue.main.async {
+      lastPage!.removeFromSuperview()
+      self.pageControl.numberOfPages -= 1
+      resizePageControl()
+    }
   }

   // MARK: - Frame changes
```

### PR DESCRIPTION
**Pull request by kolodny**
Fixes #1996

### CODE REVIEW

File: components/PageControl/src/MDCPageControl.m [hunk 1]
```diff
@@ -483,6 +483,11 @@ - (void)resetControl {
   _animatedIndicator = [[MDCPageControlIndicator alloc] initWithCenter:center radius:radius];
   [_containerView.layer addSublayer:_animatedIndicator];
 
+  // Move indicator to new position.
+  CGPoint point = [_indicatorPositions[_currentPage] CGPointValue];
+  [_animatedIndicator updateIndicatorTransformX:point.x - kPageControlIndicatorRadius];
```
Comment (ianegordon) [inline components/PageControl/src/MDCPageControl.m]: We are creating the _animatedIndicator just above.
Can we move this point calculation above and determine a proper center for:
```
_animatedIndicator = [[MDCPageControlIndicator alloc] initWithCenter:center radius:radius];
```
We may still need [_trackLayer resetAtPoint:].

**Review by ianegordon — CHANGES_REQUESTED** [review]

File: components/PageControl/src/MDCPageControl.m (hunk 1 above)
Comment (kolodny) [reply components/PageControl/src/MDCPageControl.m]: Done. `[_trackLayer resetAtPoint:]` didn't appear to be needed.

**Review by randallli — APPROVED** [review]

**Review by ianegordon — APPROVED** [review]
