### PR TITLE
[ShapeLibrary] Make the new CornerTreatment initializers use concrete types

### LINKED ISSUE #5063: [ShapeLibrary] Make the MDCCornerTreatment initializer API type-safe
initWithCornerType:andSize: should be broken up into separate initializers with concrete types.

https://github.com/material-components/material-components-ios/blob/4ed9fd09cea5567265e3e6c226331d81fef31cd7/components/private/ShapeLibrary/src/MDCCornerTreatment%2BCornerTypeInitalizer.h#L23-L27

### PR DESCRIPTION
**Pull request by yarneo**
This PR changes the recent addition of convenience initializers of MDCCornerTreatments to become a certain instance subclass to use concrete types rather than a generic NSNumber with parsing. This resolves #5063

### CODE REVIEW

**Review by jverkoey — APPROVED** [review]

File: components/private/ShapeLibrary/src/MDCCornerTreatment+CornerTypeInitalizer.h [hunk 1]
```diff
@@ -14,14 +14,30 @@
...
+ */
++ (MDCCornerTreatment *)cornerWithCut:(CGFloat)value;
+
+/**
+ Initialize and return an MDCCornerTreatment as an MDCCurvedCornerTreatment.
+
+ @param value The size to set the curved corner to.
+ @return an MDCCurvedCornerTreatment.
+ */
++ (MDCCornerTreatment *)cornerWithCurve:(CGSize)value;
```
Comment (jverkoey) [inline components/private/ShapeLibrary/src/MDCCornerTreatment+CornerTypeInitalizer.h]: Should we be returning the documented types here? E.g. `MDCCurvedCornerTreatment`?

Comment (yarneo) [reply components/private/ShapeLibrary/src/MDCCornerTreatment+CornerTypeInitalizer.h]: I was following the class cluster convention similar to how NSNumber allows initialization with different APIs without exposing the subclasses. In this case the subclasses didn't need exposing, but because these subclasses aren't internal and can be exposed, I updated it to return the concrete type.

**Comment by jverkoey** [comment]
Ahh, I see. Do we need these APIs if the underlying types are public?

**Comment by yarneo** [comment]
We don't *need* these APIs. They provide better encapsulation and cleaner init of the different corner types. They also allow our users to see what available corners can be initialized from the corner API rather than looking up the files to see what corner types subclass it.

**Comment by jverkoey** [comment]
Got it! Thanks for clarifying.
