### PR TITLE
[Feature highlight] Accessibility fixes

### LINKED ISSUE #782: MDCFeatureHighlight accessibility

### PR DESCRIPTION
**Pull request by samnm**
This change allows the highlightedView to be accessed with voiceover and also adds a 'double tap to dismiss' accessibility hint to the title of the feature highlight.

Closes #782

### CODE REVIEW

File: components/FeatureHighlight/src/private/MDCFeatureHighlightView.m [hunk 1]
```diff
@@ -20,6 +20,8 @@
 #import "MDFTextAccessibility.h"
 #import "MaterialTypography.h"
 
+NSString *const MDCFeatureHighlightViewTitleA11yHint = @"Double-tap to dismiss.";
```
Comment (ianegordon) [inline components/FeatureHighlight/src/private/MDCFeatureHighlightView.m]: Wrap in NSLocalizedString so we can (eventually) pull this out for l10n.

**Comment by ianegordon** [comment]
When you dismiss the feature highlight, the original view should still be highlighted.

Repro:
MDCCatalog -> Feature Highlight -> Demo
Navigate to the GO! button
Double tap to invoke the button's action
Double tap to dismiss the feature highlight
The Navigation - Back button is selected instead of the GO! button.

**Review by ianegordon — CHANGES_REQUESTED** [review]

**Comment by samnm** [comment]
> When you dismiss the feature highlight, the original view should still be highlighted.

Is this the standard? Dialogs doesn't do this, and I'm not sure how you would implement it.

File: components/FeatureHighlight/src/private/MDCFeatureHighlightView.m (hunk 1 above)
Comment (samnm) [reply components/FeatureHighlight/src/private/MDCFeatureHighlightView.m]: Done.

File: components/FeatureHighlight/src/private/MDCFeatureHighlightView.m [hunk 2]
```diff
@@ -76,6 +78,7 @@ - (instancetype)initWithFrame:(CGRect)frame {
     _titleLabel.textAlignment = NSTextAlignmentNatural;
     _titleLabel.lineBreakMode = NSLineBreakByTruncatingTail;
     _titleLabel.numberOfLines = 0;
+    _titleLabel.accessibilityHint = NSLocalizedString(MDCFeatureHighlightViewTitleA11yHint, nil);
```
Comment (ianegordon) [inline components/FeatureHighlight/src/private/MDCFeatureHighlightView.m]: This will fail as it will try and load from the mainBundle, see MDCPageControl for an example of how to load from a local .bundle.

**Review by ianegordon — CHANGES_REQUESTED** [review]

**Comment by ianegordon** [comment]
Lets push on the state after the feature has been rejected.  I'll open an issue to investigate.

**Comment by samnm** [comment]
Updated to load the accessibility hint from a bundle.

**Comment by ianegordon** [comment]
Tested on an iPhone 7.
Please rebase before merge.
LGTM.

**Review by ianegordon — APPROVED** [review]
