### PR TITLE
[TextFields] Fixes bug: multiline having ambiguous height in the text view

### LINKED ISSUE #2352: [TextFields] Filled multiline height is wrong when empty and minimumLines == 0

### PR DESCRIPTION
**Pull request by willlarche**
Closes #2352

### CODE REVIEW

**Comment by willlarche** [comment]
Closes #2467

File: components/TextFields/src/private/MDCIntrinsicHeightTextView.m [hunk 1]
```diff
@@ -0,0 +1,32 @@
...
+
+@implementation MDCIntrinsicHeightTextView
+
+/**
+ When a value in the CGSize of intrinsicContentSize is -1, it's considered undefined. For the
+ MDCMultilineTextField, we want this to always be defined so our layouts are not ambiguous.
+ */
+- (CGSize)intrinsicContentSize {
+  CGSize size = [super intrinsicContentSize];
+  if (size.height == -1) {
```
Comment (ianegordon) [inline components/TextFields/src/private/MDCIntrinsicHeightTextView.m]: Is -1 the same as UIViewNoIntrinsicMetric?
If so, prefer UIViewNoIntrinsicMetric.
If not, do we also need special handling of UIViewNoIntrinsicMetric?

File: components/TextFields/src/MDCMultilineTextField.m [hunk 2]
```diff
@@ -88,12 +92,11 @@ - (instancetype)initWithCoder:(NSCoder *)aDecoder {
...
-      [self setupTextView];
-    } else if (!_textView) {
-      // It's expected that this will be created by the fundament above. This is a catch.
-      _textView = [[UITextView alloc] initWithFrame:CGRectZero];
-      [self setupTextView];
     }
+    if (!_textView) {
+      _textView = [[MDCIntrinsicHeightTextView alloc] initWithFrame:CGRectZero];
+    }
+    [self setupTextView];
```
Comment (ianegordon) [inline components/TextFields/src/MDCMultilineTextField.m]: Do we want to replace existing UITextViews with IntrinsicHeight versions?
if (!_textView || ![_textView isKindOf:[MDCIntrinsicHeightTextView class]]) {
  _textView = [[MDCIntrinsicHeightTextView alloc] initWithFrame:CGRectZero];
}

Comment (ianegordon) [reply components/TextFields/src/MDCMultilineTextField.m]: setupTextView will overwrite a bunch of properties that may already be encoded.  Is this acceptable?  If so, consider adding a comment that mentioning this and that it is intentional.

File: components/TextFields/src/MDCMultilineTextField.m [hunk 3]
```diff
@@ -685,22 +707,17 @@ - (void)setTextInsetsMode:(MDCTextInputTextInsetsMode)textInsetsMode {
...
 
 - (void)setTextView:(UITextView *)textView {
   if (![_textView isEqual:textView]) {
     [_textView removeFromSuperview];
     _textView = textView;
-    if (textView) {
-      [self setupTextView];
-      [self setupUnderlineConstraints];
-    }
+    [self textViewSafetyCheck];
```
Comment (ianegordon) [inline components/TextFields/src/MDCMultilineTextField.m]: Can we avoid this check here by requiring an MDCIntrinsicHeightTextView as the parameter / property?

File: components/TextFields/src/MDCMultilineTextField.m [hunk 4]
```diff
@@ -233,6 +236,25 @@ - (void)setupTextView {
   self.textView.opaque = NO;
 }
 
+// It's possible we've been passed a text view that's not our special class. We can handle that.
+// It's also something we guarantee to always be there. So, if it's nil, we make a new one.
+- (void)textViewSafetyCheck {
```
Comment (ianegordon) [inline components/TextFields/src/MDCMultilineTextField.m]: Naming is hard.
Consider: 
- (void)promoteToMDCIntrinsicTextView

File: components/TextFields/src/MDCMultilineTextField.m [hunk 5]
```diff
@@ -233,6 +236,25 @@ - (void)setupTextView {
...
+  // We expect users of Interface Builder to put a UITextView in the view. When that happens,
+  // we swap it out for one of our special text views and bring the existing text over.
+  NSString *existingText = _textView.text;
```
Comment (ianegordon) [inline components/TextFields/src/MDCMultilineTextField.m]: Do we care about any other state?

font?
textColor?
textAlignment?
etc.

File: components/TextFields/src/MDCMultilineTextField.m [hunk 6]
```diff
@@ -75,6 +76,9 @@ @implementation MDCMultilineTextField
 - (instancetype)initWithFrame:(CGRect)frame {
   self = [super initWithFrame:frame];
   if (self) {
+    _textView = [[MDCIntrinsicHeightTextView alloc] initWithFrame:CGRectZero];
+    [self setupTextView];
```
Comment (ianegordon) [inline components/TextFields/src/MDCMultilineTextField.m:80]: [self setupTextView] is in both init* functions.  Move to commonInit?

File: components/TextFields/src/MDCMultilineTextField.m [hunk 7]
```diff
@@ -685,22 +707,17 @@ - (void)setTextInsetsMode:(MDCTextInputTextInsetsMode)textInsetsMode {
 }
 
 - (UITextView *)textView {
-  if (!_textView) {
-    _textView = [[UITextView alloc] initWithFrame:CGRectZero];
-    [self setupTextView];
-    [self setupUnderlineConstraints];
-  }
+  [self textViewSafetyCheck];
```
Comment (ianegordon) [inline components/TextFields/src/MDCMultilineTextField.m]: The previous implementation lazy-init'd out textView.
Do we no longer need to do this?  (textViewSafetyCheck does not lazy-init)

File: components/TextFields/src/MDCMultilineTextField.m [hunk 8]
```diff
@@ -685,22 +707,17 @@ - (void)setTextInsetsMode:(MDCTextInputTextInsetsMode)textInsetsMode {
...
   return _textView;
 }
 
 - (void)setTextView:(UITextView *)textView {
```
Comment (ianegordon) [inline components/TextFields/src/MDCMultilineTextField.m]: Add a comment explaining the magic here.  Perhaps something along the lines of:
We silently replace the textView with an MDCIntrinsicHeightTextView version because x, y and z.

I can see people getting confused when they assume that the textView they are setting here end up NOT being the textView in the component. :/

**Review by ianegordon — DISMISSED** [review]

File: components/TextFields/src/MDCMultilineTextField.m (hunk 6 above)
Comment (willlarche) [reply components/TextFields/src/MDCMultilineTextField.m:80]: This one cannot be moved. It is a dependency for the fundament which is a dependency for the commonInit. I will document that.

File: components/TextFields/src/MDCMultilineTextField.m (hunk 4 above)
Comment (willlarche) [reply components/TextFields/src/MDCMultilineTextField.m]: It's hard because it also makes sure that it isn't nil.

File: components/TextFields/src/MDCMultilineTextField.m (hunk 5 above)
Comment (willlarche) [reply components/TextFields/src/MDCMultilineTextField.m]: I was a little torn about those because of all the styling we apply. But I think you're right. The MDCMultilineTextField element is supposed to be as dumb as possible and that should include respecting whatever is set on its junk.

File: components/TextFields/src/MDCMultilineTextField.m (hunk 7 above)
Comment (willlarche) [reply components/TextFields/src/MDCMultilineTextField.m]: Yes it does.
`  if (!_textView) {
    _textView = [[MDCIntrinsicHeightTextView alloc] initWithFrame:CGRectZero];
`

File: components/TextFields/src/MDCMultilineTextField.m (hunk 3 above)
Comment (willlarche) [reply components/TextFields/src/MDCMultilineTextField.m]: We could but we were trying to keep that fact private so people just see UITextView in the API instead of a class they have never heard of.

File: components/TextFields/src/private/MDCIntrinsicHeightTextView.m (hunk 1 above)
Comment (willlarche) [reply components/TextFields/src/private/MDCIntrinsicHeightTextView.m]: Correcting.

File: components/TextFields/src/MDCMultilineTextField.m (hunk 8 above)
Comment (willlarche) [reply components/TextFields/src/MDCMultilineTextField.m]: Done.

File: components/TextFields/src/MDCMultilineTextField.m (hunk 5 above)
Comment (willlarche) [reply components/TextFields/src/MDCMultilineTextField.m]: Ugh. This isn't gonna work. I'm going to enforce they use my special class and be very verbose with instructions and asserts. This looks terrible!

File: components/TextFields/src/MDCMultilineTextField.m (hunk 2 above)
Comment (willlarche) [reply components/TextFields/src/MDCMultilineTextField.m]: Added the comment.

**Comment by willlarche** [comment]
Approach of hidden class was creating NUTS code. We'll just have to enforce it. That's not too crazy. PTAL

File: components/TextFields/src/MDCMultilineTextField.m (hunk 6 above)
Comment (ianegordon) [reply components/TextFields/src/MDCMultilineTextField.m:80]: SGTM.

**Review by ianegordon — APPROVED** [review]

**Comment by ianegordon** [comment]
Thank you @willlarche !
