### PR TITLE
[Chips] Add support for custom touch target

### LINKED ISSUE #3513: [Chips] Support custom hit areas
### Overview
Chips are only 36 points high (by default) and therefore fail to meet accessibility guidelines (48 x 48 point target) for touch target size. 

### Version number
54.11.1

### PR DESCRIPTION
**Pull request by romoore**
Chips are small and so need support for custom touch target sizes. Following
the lead of MDCButton, a new property, `-hitAreaInsets` is added that clients
can use to support larger touch targets.

Closes #3513
Internal issue b/77728916

### CODE REVIEW

File: components/Chips/examples/ChipsInputExampleViewController.m [hunk 1]
```diff
@@ -35,6 +35,7 @@ - (void)viewDidLoad {
   _chipField = [[MDCChipField alloc] initWithFrame:CGRectZero];
   _chipField.delegate = self;
   _chipField.textField.placeholderLabel.text = @"This is a chip field.";
+  _chipField.chipHeight = 48;
```
Comment (yarneo) [inline components/Chips/examples/ChipsInputExampleViewController.m]: is this part of the other PR?

File: components/Chips/examples/ChipsInputExampleViewController.m [hunk 2]
```diff
@@ -60,7 +61,9 @@ - (void)chipField:(MDCChipField *)chipField didAddChip:(MDCChipView *)chip {
     [chip setBorderWidth:0 forState:UIControlStateNormal];
     [MDCChipViewColorThemer applySemanticColorScheme:self.colorScheme toChipView:chip];
   }
-
+  [chip sizeToFit];
+  CGFloat chipVerticalInset = MIN(0, (CGRectGetHeight(chip.bounds) - 48) / 2);
```
Comment (yarneo) [inline components/Chips/examples/ChipsInputExampleViewController.m:65]: 48 -> `chipField.chipHeight`

File: components/Chips/src/MDCChipView.m [hunk 3]
```diff
@@ -568,6 +570,13 @@ - (void)updateState {
   [self updateTitleColor];
 }
 
+#pragma mark - Custom touch handling
+
+- (BOOL)pointInside:(CGPoint)point withEvent:(__unused UIEvent *)event {
+  CGRect hitAreaRect = UIEdgeInsetsInsetRect(CGRectStandardize(self.bounds), self.hitAreaInsets);
```
Comment (yarneo) [inline components/Chips/src/MDCChipView.m:576]: is there a reason we need `CGRectStandardize`? will the values of the bounds itself be negative?

File: components/Chips/examples/ChipsInputExampleViewController.m (hunk 2 above)
Comment (romoore) [reply components/Chips/examples/ChipsInputExampleViewController.m:65]: This is actually the touch target dimension (edge) size. Even if in the example the `chipHeight` is 72, we should keep the touch targets to 48 points (or the size of the frame).

File: components/Chips/src/MDCChipView.m (hunk 3 above)
Comment (romoore) [reply components/Chips/src/MDCChipView.m:576]: Bounds can be negative, especially with Autolayout. The general recommendation on the team has been to standardize `bounds` and `rect` before manipulating them. Since `UIEdgeInsetsInsetRect` will not standardize a CGRect first, it's best to standardize before applying the insets.

File: components/Chips/examples/ChipsInputExampleViewController.m (hunk 1 above)
Comment (romoore) [reply components/Chips/examples/ChipsInputExampleViewController.m]: Yeah, they were both the same work and I split them up. Each needed this change to demonstrate their effect.

File: components/Chips/src/MDCChipView.m (hunk 3 above)
Comment (yarneo) [reply components/Chips/src/MDCChipView.m:576]: On the same note; food for thought: do we want to keep a minimum hit area rect size, or at least have it not become negative? As an example, a chip size of (20,20) with a hitAreaInset of (25,10) will make our chip have a negative hitAreaRect.

**Review by yarneo — APPROVED** [review]

**Comment by romoore** [comment]
I think given that this is a very specific property that clients will only be setting "if they know what they're doing", we should probably let them live with the consequences. They might have a good reason for a super-tiny touch target, and there are technically exceptions for things like elements on the edge of the screen.
