### PR TITLE
[Dialogs] Fix incorrect vertical layout for uppercase buttons

### LINKED ISSUE #8434: [Dialogs] Internal issue: b/137070719
This was filed as an internal issue. If you are a Googler, please visit [b/137070719](http://b/137070719) for more details.

---
#### Internal data
- Associated internal bug: [b/137070719](http://b/137070719)

### PR DESCRIPTION
**Pull request by galiak11**
# Description

Making sure layout subviews calculates content size based on the available size, not based on the size of the previous layout calculations. This fixes an issue in which the dialog unexpectedly changed vertical vs horizontal actions layout after the first layout pass (see issue #8434 - b/137070719).

## Before
Actions are laid out vertically - when loaded for the first time, and horizontally thereafter (for instance: after orientation changed, app is sent to the background, etc):

dialog - actions - uppercase - BEFORE

## After
Actions are laid out horizontally on all layout passes - including the first:

dialog - actions - uppercase - AFTER

## Issues
Closes #8434.
b/137070719, cl/299735842

### CODE REVIEW

File: components/Dialogs/src/MDCAlertController.m [hunk 1]
```diff
@@ -563,7 +563,7 @@ - (void)viewWillLayoutSubviews {
   if (CGRectGetWidth(self.view.bounds) != _previousLayoutSize.width ||
       CGRectGetHeight(self.view.bounds) != _previousLayoutSize.height) {
     CGSize currentPreferredContentSize = self.preferredContentSize;
-    CGSize contentSize = CGRectStandardize(self.alertView.bounds).size;
+    CGSize contentSize = CGRectInfinite.size;
```
Comment (jverkoey) [inline components/Dialogs/src/MDCAlertController.m:630]: Does the calculated preferred size eventually get constrained to the viewport's bounds? If so, then this change LGTM, otherwise I'd expect some consideration for the viewport bounds to be added as part of this PR.

**Review by jverkoey — COMMENTED** [review]
Please add either a unit test or a snapshot test (preferably), or an example that can be used to test this change.

**Review by jverkoey — DISMISSED** [review]
Marking changes requested for snapshot test.

File: components/Dialogs/src/MDCAlertController.m (hunk 1 above)
Comment (galiak11) [reply components/Dialogs/src/MDCAlertController.m:630]: This only determines the preferredContentSize, which can be larger than the viewport. The actual bounds are determined by the presentation controller, and that's where the bounds are constrained in case the preferredContentSize is too large.

**Comment by galiak11** [comment]
Snapshot test ready for review - https://github.com/material-components/material-components-ios/pull/9875

Affected snapshot test was added to this PR. Please re-review.

**Review by yarneo — APPROVED** [review]
