### PR TITLE
[Tabs] Support Fixed Clustered layout when Justified won't fit.

### LINKED ISSUE #7821: [Tabs] Internal issue: b/137078489
This was filed as an internal issue. If you are a Googler, please visit [b/137078489](http://b/137078489) for more details.

---
#### Internal data
- Associated internal bug: [b/137078489](http://b/137078489)

### PR DESCRIPTION
**Pull request by romoore**
By default, `MDCTabBarView` attempts to use a Justified Fixed layout. However, if the
individual item views would be too wide (beyond their maximum of 360 points),
Justified looks bad.  Instead, the layout should switch to a "Clustered Fixed"
style. In this style, each item is the same width (the widest item), but the
items are centered at the middle of the bar.

## Layout Examples
|Environment|Effect|Original|New|
|---|---|---|---|
|iPad Landscape 1.0 * screen width|Changed|old-landscape-1 0-justified|new-landscape-1 0-clustered|
|iPad Landscape 0.66 * screen width|Same|old-landscape-0 66-justified|new-landscape-0 66-justified|
|iPad Landscape 0.5 * screen width|Same|old-landscape-0 5-scrollable|new-landscape-0 5-scrollable|
|iPad Landscape 0.33 * screen width|Same|old-landscape-0 33-scrollable|new-landscape-0 33-scrollable|
|iPad Portrait 1.0 * screen width|Changed|old-portrait-1 0-justified|new-portrait-1 0-clustered|
|iPad Portrait 0.6 * screen width|Same|old-portrait-0 6-scrollable|new-portrait-0 6-scrollable|

Closes #7821

### CODE REVIEW

File: components/Tabs/src/TabBarView/MDCTabBarView.m [hunk 1]
```diff
@@ -51,6 +54,26 @@
 static NSString *const kAccessibilityIdentifierKeyPath = @"accessibilityIdentifier";
 static NSString *const kAccessibilityTraitsKeyPath = @"accessibilityTraits";
 
+/** The internal layout styles of the tab bar. */
+typedef NS_ENUM(NSUInteger, MDCTabBarViewInternalLayoutStyle) {
```
Comment (codeman7) [inline components/Tabs/src/TabBarView/MDCTabBarView.m:58]: How do you feel about dropping the work `internal` from the enum name? My thoughts are its in a `.m` and not exposed so as a developer I should know it's internal, I could be swayed otherwise though, I'd love to hear your thoughts.

File: components/Tabs/src/TabBarView/MDCTabBarView.m [hunk 2]
```diff
@@ -51,6 +54,26 @@
...
+
+  /** Items are laid-out from leading to trailing and sized to their intrinsic content size. */
+  MDCTabBarViewInternalLayoutStyleScrollable = 0,
+  /**
```
Comment (codeman7) [inline components/Tabs/src/TabBarView/MDCTabBarView.m:63]: Nit: New line here or remove the extra line in the other documenation for the enum types.

File: components/Tabs/src/TabBarView/MDCTabBarView.m [hunk 3]
```diff
@@ -51,6 +54,26 @@
...
+   Items are equally-sized where each of the items receives an equal portion of the bar's width.
+   For example, if there are 3 items and the bar is 360 points wide, each item receives 120 points
+   in width.
+   */
+  MDCTabBarViewInternalLayoutStyleFixedJustified = 1,
+
+  /**
+   Items are equally-sized where each of the items is the width of the widest item. The items are
```
Comment (codeman7) [inline components/Tabs/src/TabBarView/MDCTabBarView.m:71]: Would the items be scrollable?

File: components/Tabs/src/TabBarView/MDCTabBarView.m [hunk 4]
```diff
@@ -60,7 +83,7 @@ @interface MDCTabBarView ()
 @property(nonnull, nonatomic, strong) UIView *bottomDividerView;
 
 /** @c YES if the items are laid-out in a justified style. */
-@property(nonatomic, readonly) BOOL isJustifiedLayoutStyle;
+@property(nonatomic, readonly) BOOL isScrollableLayoutStyle;
```
Comment (codeman7) [inline components/Tabs/src/TabBarView/MDCTabBarView.m:87]: Please update the documenation.

File: components/Tabs/src/TabBarView/MDCTabBarView.m [hunk 5]
```diff
@@ -567,10 +600,23 @@ - (void)layoutSubviews {
...
+}
+
+- (MDCTabBarViewInternalLayoutStyle)layoutStyle {
+  CGSize availableSize = [self availableSizeForSubviewLayout];
+  CGFloat requiredWidthForJustifiedLayout = [self intrinsicContentSizeForJustifiedLayout].width;
+  if (availableSize.width < requiredWidthForJustifiedLayout) {
+    return MDCTabBarViewInternalLayoutStyleScrollable;
+  }
+  if (self.items.count == 0) {
+    return MDCTabBarViewInternalLayoutStyleFixedJustified;
```
Comment (codeman7) [inline components/Tabs/src/TabBarView/MDCTabBarView.m]: Should this be the first thing to check in this method to remove any calculations and just return if there are no items.

File: components/Tabs/src/TabBarView/MDCTabBarView.m [hunk 6]
```diff
@@ -594,6 +640,29 @@ - (void)layoutSubviewsForJustifiedLayout {
...
+  BOOL isRTL =
+      self.mdf_effectiveUserInterfaceLayoutDirection == UIUserInterfaceLayoutDirectionRightToLeft;
+
+  CGSize contentSize = [self availableSizeForSubviewLayout];
+  CGFloat itemViewWidth = [self estimatedItemViewSizeForClusteredFixedLayout].width;
+  CGFloat totalRequiredWidth = itemViewWidth * self.items.count;
+  CGFloat itemViewOriginX = (contentSize.width - totalRequiredWidth) / 2;
+  CGFloat itemViewOriginY = 0;
+  CGFloat itemViewHeight = contentSize.height;
+  NSEnumerator<UIView *> *itemViewEnumerator =
```
Comment (codeman7) [inline components/Tabs/src/TabBarView/MDCTabBarView.m:659]: Love this 😄 !

File: components/Tabs/src/TabBarView/MDCTabBarView.m [hunk 7]
```diff
@@ -714,6 +812,20 @@ - (CGSize)expectedSizeForView:(UIView *)view {
   return expectedItemSize;
 }
 
+- (CGSize)estimatedItemViewSizeForClusteredFixedLayout {
+  CGSize largestSize = CGSizeZero;
+  for (UIView *view in self.itemViews) {
+    CGSize intrinsicContentSize = view.intrinsicContentSize;
+    if (intrinsicContentSize.width > largestSize.width) {
```
Comment (codeman7) [inline components/Tabs/src/TabBarView/MDCTabBarView.m]: Personally I think this would be more _readable_ to me if we used `largestWidth` and `largestHeight` for all the comparisons then at the end did `CGSizeMake(largestWidth, largestHeight)`. Just an idea, I'll leave it up to you, if you think this is better feel free to resolve.

**Review by codeman7 — APPROVED** [review]

**Review by leonmz — APPROVED** [review]

File: components/Tabs/src/TabBarView/MDCTabBarView.m (hunk 1 above)
Comment (romoore) [reply components/Tabs/src/TabBarView/MDCTabBarView.m:58]: I intended to mark this as intentionally not usable externally. At some point we might have a set of external layout concepts, but they should be separate from these. If you prefer to drop `internal` and then rename it later to avoid naming conflicts, I can do that too.  Since this isn't a "Tip:" I'll leave it up to you.

File: components/Tabs/src/TabBarView/MDCTabBarView.m (hunk 2 above)
Comment (romoore) [reply components/Tabs/src/TabBarView/MDCTabBarView.m:63]: Done

File: components/Tabs/src/TabBarView/MDCTabBarView.m (hunk 3 above)
Comment (romoore) [reply components/Tabs/src/TabBarView/MDCTabBarView.m:71]: They would not be. Documented.

File: components/Tabs/src/TabBarView/MDCTabBarView.m (hunk 4 above)
Comment (romoore) [reply components/Tabs/src/TabBarView/MDCTabBarView.m:87]: Done.

File: components/Tabs/src/TabBarView/MDCTabBarView.m (hunk 5 above)
Comment (romoore) [reply components/Tabs/src/TabBarView/MDCTabBarView.m]: Done.

File: components/Tabs/src/TabBarView/MDCTabBarView.m (hunk 7 above)
Comment (romoore) [reply components/Tabs/src/TabBarView/MDCTabBarView.m]: Done.
