### PR TITLE
[BottomSheet] Add respondsToSelector check in BottomSheet accessibility escape

### LINKED ISSUE #7569: [BottomSheet] MDCBottomSheetController accessibility escape can crash if delegate doesn't implement optional method
MDCBottomSheetController assumes its delegate implements the optional method `-bottomSheetControllerDidDismissBottomSheet:` in its `-accessibilityPerformEscape` method. 

1. Open the BottomSheetTypicalUseExample in VoiceOver.
2. Perform the two finger "Z" gesture.

## Expected behavior

The BottomSheet dismisses without issue.

## Actual behavior

The app crashes.

---
#### Internal data
- Associated internal bug: [b/135176883](http://b/135176883)

### PR DESCRIPTION
**Pull request by andrewoverton**
This PR fixes a crash by adding a respondsToSelector check to the BottomSheet accessibility escape.

Closes #7569.

### CODE REVIEW

File: components/BottomSheet/src/MDCBottomSheetController.m [hunk 1]
```diff
@@ -93,7 +93,11 @@ - (BOOL)accessibilityPerformEscape {
   [self
       dismissViewControllerAnimated:YES
                          completion:^{
-                           [weakSelf.delegate bottomSheetControllerDidDismissBottomSheet:weakSelf];
+                           if ([weakSelf.delegate respondsToSelector:@selector
```
Comment (romoore) [inline components/BottomSheet/src/MDCBottomSheetController.m]: Please capture `weakSelf.delegate` into a variable so it doesn't [disappear/change between the if and the use](https://github.com/stephanemoore/archives/blob/master/objc/pitfalls/tocttou.md).

**Review by romoore — APPROVED** [review]

File: components/BottomSheet/src/MDCBottomSheetController.m [hunk 2]
```diff
@@ -93,7 +93,12 @@ - (BOOL)accessibilityPerformEscape {
   [self
       dismissViewControllerAnimated:YES
                          completion:^{
-                           [weakSelf.delegate bottomSheetControllerDidDismissBottomSheet:weakSelf];
+                           __strong __typeof(weakSelf) strongSelf = weakSelf;
```
Comment (romoore) [inline components/BottomSheet/src/MDCBottomSheetController.m]: This is a good improvement (switching to `__typeof`), but our team's convention is to avoid `typeof` and  `__typeof` whenever possible. We prefer to use explicitly-typed pointers in these circumstances.  I think in this case it's acceptable to use a pointer of type `MDCBottomSheetController *` explicitly.

If there's a specific reason not to use an explicit pointer type in this case, I think it's worth adding a comment to explain to future maintainers.
