### PR TITLE
[Buttons] Fix storyboard backgroundColor assignment

### LINKED ISSUE #1686: [Buttons] Interface Builder background color is not longer working as expected
From an internal client:

We use Interface Builder for a few screens, and it looks like MDCButtons on those screens don't have the correct background color set anymore when loading the .xib files. I suspect it was a recent MDCButton change in the last few weeks, but I had a look through CS and couldn't figure out the suspect CL.

### PR DESCRIPTION
**Pull request by samnm**
[Before](https://user-images.githubusercontent.com/1251373/28644517-e2fda6f0-7227-11e7-8752-63fc60072abb.png)/[After](https://user-images.githubusercontent.com/1251373/28644523-e95d55f4-7227-11e7-8b0c-83618f6e410b.png)

Closes #1686.

### CODE REVIEW

**Comment by ianegordon** [comment]
I've reached out to an internal team for verification of the fix.

**Comment by ianegordon** [comment]
Awaiting response from an internal team.

File: components/Buttons/src/MDCButton.m [hunk 1]
```diff
@@ -207,18 +213,20 @@ - (void)commonMDCButtonInit {
...
   _uppercaseTitle = YES;
   _userElevations = [NSMutableDictionary dictionary];
-  _backgroundColors = [NSMutableDictionary dictionary];
   _accessibilityLabelForState = [NSMutableDictionary dictionary];
 
-  _backgroundColors[@(UIControlStateNormal)] = MDCColorFromRGB(MDCButtonDefaultBackgroundColor);
+  if (!_backgroundColors) {
+    // _backgroundColors may have already been initialized by setting the backgroundColor setter.
+    _backgroundColors = [NSMutableDictionary dictionary];
+    _backgroundColors[@(UIControlStateNormal)] = MDCColorFromRGB(MDCButtonDefaultBackgroundColor);
```
Comment (ianegordon) [inline components/Buttons/src/MDCButton.m:221]: Should this be:
```
if (!_backgroundColor) {
  _backgroundColors = [NSMutableDictionary dictionary];
}
_backgroundColors[@(UIConrolStateNormal)] = MDCColorFromRGB(MDCColor);
```

Do we not need to [self updateBackgroundColor] as we are below?

**Review by ianegordon — CHANGES_REQUESTED** [review]

File: components/Buttons/src/MDCButton.m (hunk 1 above)
Comment (samnm) [reply components/Buttons/src/MDCButton.m:221]: [self updateBackgroundColor] is called at the end of both initializers.

We don't want to always write to the Normal backgroundColor because we might already have a value there, so we only write to it if the dictionary is uninitialized.

Comment (ianegordon) [reply components/Buttons/src/MDCButton.m:221]: SGTM

**Review by ianegordon — APPROVED** [review]
