### PR TITLE
[TextFields] Adding .placeholderText to controllers

### LINKED ISSUE #2121: [TextFields] Floating label in MDCTextInputControllerLegacyDefault is sometimes indented.
### Overview
Occasionally, the floating label for the placeholder is showing as indented.  I believe this happens with both the MDCTextInputControllerDefault & MDCTextInputControllerLegacyDefault.  It appears to be related to setting the MDCTextField's text programatically.

### Reproduction steps
 Set both the placeholder & text programatically. The floating label will be indented (both when field is active & inactive).
image

### Version number
 35.3.0

### Operating system and device
iOS 10.3 iPhone 7 Plus (simulator)

### PR DESCRIPTION
**Pull request by willlarche**
Closes #2121

### CODE REVIEW

File: components/TextFields/src/MDCTextInputControllerDefault.m [hunk 1]
```diff
@@ -1052,6 +1064,17 @@ + (void)setNormalColorDefault:(UIColor *)normalColorDefault {
       normalColorDefault ? normalColorDefault : MDCTextInputDefaultNormalUnderlineColorDefault();
 }
 
+- (NSString *)placeholderText {
+  return _textInput.placeholder;
+}
+
+- (void)setPlaceholderText:(NSString *)placeholderText {
+  _textInput.placeholder = placeholderText;
```
Comment (ianegordon) [inline components/TextFields/src/MDCTextInputControllerDefault.m]: _textInput.placeholder = [placeholderText copy] ?

Comment (ianegordon) [inline components/TextFields/src/MDCTextInputControllerDefault.m]: Consider checking equality before updating the placeholder animation constraints since that could kickoff animation.
if (_textInput.placeholder && [_textInput.placeholder isEqualString:placeholderText]) {
  return;
}

File: components/TextFields/src/MDCTextInputControllerFullWidth.m [hunk 2]
```diff
@@ -611,6 +611,14 @@ + (UIColor *)normalColorDefault {
   return [UIColor clearColor];
 }
 
+- (NSString *)placeholderText {
+  return _textInput.placeholder;
+}
+
+- (void)setPlaceholderText:(NSString *)placeholderText {
+  _textInput.placeholder = placeholderText;
```
Comment (ianegordon) [inline components/TextFields/src/MDCTextInputControllerFullWidth.m]: _textInput.placeholder = [placeholderText copy] ?

File: components/TextFields/src/MDCTextInputControllerLegacyDefault.m [hunk 3]
```diff
@@ -514,62 +515,72 @@ - (void)movePlaceholderToUp:(BOOL)isToUp {
...
       }];
 }
 
+- (void)updatePlaceholderAnimationConstraints:(BOOL)isToUp {
+  if (isToUp) {
+    CGPoint destination = [self placeholderFloatingPosition];
+
+    if (!self.placeholderAnimationConstraintLeading) {
+      self.placeholderAnimationConstraintLeading =
+      [NSLayoutConstraint constraintWithItem:self.textInput.placeholderLabel
```
Comment (ianegordon) [inline components/TextFields/src/MDCTextInputControllerLegacyDefault.m:548]: nit: Indent + 4 here and below.

File: components/TextFields/src/MDCTextInputControllerLegacyDefault.m [hunk 4]
```diff
@@ -991,6 +1002,17 @@ + (void)setNormalColorDefault:(UIColor *)normalColorDefault {
                             : MDCTextInputControllerLegacyDefaultNormalUnderlineColorDefault();
 }
 
+- (NSString *)placeholderText {
+  return _textInput.placeholder;
+}
+
+- (void)setPlaceholderText:(NSString *)placeholderText {
+  _textInput.placeholder = placeholderText;
```
Comment (ianegordon) [inline components/TextFields/src/MDCTextInputControllerLegacyDefault.m]: copy ?

Comment (ianegordon) [inline components/TextFields/src/MDCTextInputControllerLegacyDefault.m]: Consider checking for equality with a quick exit to avoid updatePlaceholderAnimationConstraints:

**Review by ianegordon — CHANGES_REQUESTED** [review]
Some minor things.

File: components/TextFields/src/MDCTextInputControllerDefault.m (hunk 1 above)
Comment (willlarche) [reply components/TextFields/src/MDCTextInputControllerDefault.m]: So this one actually doesn't kick off an animation. It just sets the constants and activation of the constraints. But I'll put that equality thing in there to avoid a non-trivial calculation that's a part of that.

Comment (willlarche) [reply components/TextFields/src/MDCTextInputControllerDefault.m]: Done

File: components/TextFields/src/MDCTextInputControllerFullWidth.m (hunk 2 above)
Comment (willlarche) [reply components/TextFields/src/MDCTextInputControllerFullWidth.m]: Done

File: components/TextFields/src/MDCTextInputControllerLegacyDefault.m (hunk 3 above)
Comment (willlarche) [reply components/TextFields/src/MDCTextInputControllerLegacyDefault.m:548]: Done

File: components/TextFields/src/MDCTextInputControllerLegacyDefault.m (hunk 4 above)
Comment (willlarche) [reply components/TextFields/src/MDCTextInputControllerLegacyDefault.m]: Done

Comment (willlarche) [reply components/TextFields/src/MDCTextInputControllerLegacyDefault.m]: Done

**Comment by willlarche** [comment]
Ready for re-review.

**Comment by willlarche** [comment]
Actually, NOW it's ready for re-review.

**Review by ianegordon — APPROVED** [review]

**Comment by ianegordon** [comment]
LGTM, please merge when Travis is happy.
