### PR TITLE
[Catalog] Fix Banner positioning in example for iOS 10

### LINKED ISSUE #8825: [Catalog] Internal issue: b/144499698
This was filed as an internal issue. If you are a Googler, please visit [b/144499698](http://b/144499698) for more details.

---
#### Internal data
- Associated internal bug: [b/144499698](http://b/144499698)

### PR DESCRIPTION
**Pull request by bryanoltman**
The typical use banner example now accounts for the app and status bars on iOS 10.

Fixes #8825 

Before:
before

After:
after

### CODE REVIEW

**Comment by jverkoey** [comment]
Please add a before/after screenshot.

File: components/Banner/examples/BannerTypicalUseExampleViewController.m [hunk 1]
```diff
@@ -168,12 +170,20 @@ - (void)viewWillLayoutSubviews {
...
-    topAreaInset = self.view.safeAreaInsets.top;
+    yOrigin = self.view.safeAreaInsets.top;
+  } else {
+    if ([self.parentViewController isKindOfClass:[MDCAppBarContainerViewController class]]) {
+      MDCAppBarContainerViewController *containerViewController =
+          (MDCAppBarContainerViewController *)self.parentViewController;
+      UIApplication *safeApplication = [UIApplication mdc_safeSharedApplication];
+      yOrigin = CGRectGetMaxY(containerViewController.appBarViewController.navigationBar.frame) +
+                CGRectGetHeight(safeApplication.statusBarFrame);
+    }
```
Comment (jverkoey) [inline components/Banner/examples/BannerTypicalUseExampleViewController.m]: Pre-iOS 11 you should be able to make use of self.topLayoutGuide to achieve this same effect without relying on assumptions about the AppBar.

Comment (bryanoltman) [reply components/Banner/examples/BannerTypicalUseExampleViewController.m]: Good call! I knew there was a pre-iOS 11 API for that, but all my guesses about its name were wrong :)

**Review by jverkoey — APPROVED** [review]
