### PR TITLE
[Chips] Do not include insets in MDCChipField placeholder width if there is no placeholder

### LINKED ISSUE #9846: [Chips] MDCChipField pushes text field to new line with no text or placeholder
To reproduce:

1. Create an MDCChipField without a placeholder text value
2. Set contentEdgeInsets to insets with a large `.right` value
3. Add a chip view that is narrow enough to move the text field to the next line.

Actual behavior:
Text field is moved to the next line

Expected behavior:
Because there is no placeholder or text, the text field and placeholder should only require the minimum 44pt width.

---
#### Internal data
- Associated internal bug: [b/150883538](http://b/150883538)

### PR DESCRIPTION
**Pull request by bryanoltman**
Adds logic to MDCChipField to exit early when calculating placeholder label width if there is no placeholder text. 

Fixes #9846

### CODE REVIEW

File: components/Chips/src/MDCChipField.m [hunk 1]
```diff
@@ -778,6 +778,11 @@ - (CGFloat)placeholderDesiredWidth {
   if (!self.showPlaceholderWithChips && self.chips.count > 0) {
     placeholder = nil;
   }
+
+  if (!placeholder || [placeholder isEqualToString:@""]) {
```
Comment (andrewoverton) [inline components/Chips/src/MDCChipField.m]: I always prefer the ol' `if (placeholder.length > 0)` or I guess in this case `if (placeholder.length <= 0)`, but I guess this is fine

**Review by andrewoverton — APPROVED** [review]

File: components/Chips/src/MDCChipField.m (hunk 1 above)
Comment (bryanoltman) [reply components/Chips/src/MDCChipField.m]: Nice! Done.
