### PR TITLE
[Slider]Fix accessibilityIncrement for discrete sliders

### LINKED ISSUE #3040: [Slider] Discrete Slider increment/decrement should match discreteValues
### Overview
When numberOfDiscreteValues is non-zero, the MDCSlider should use these as the step value in `accessibilityIncrement` and `accessibilityDecrement`.  If the number of discrete values is fewer than 8, then VoiceOver users cannot modify the slider value by swiping up or down.

### Reproduction steps
```objectivec
- (void)testAccessibilityIncrementDiscreteSlider {
  for (NSUInteger i = 2; i < 20; ++i) {
    // Given
    self.slider.numberOfDiscreteValues = i;
    self.slider.minimumValue = 0;
    self.slider.maximumValue = 1;
    self.slider.value = self.slider.minimumValue;

    // When
    [self.slider accessibilityIncrement];

    // Then
    CGFloat stepValue = (self.slider.maximumValue - self.slider.minimumValue) /
        (self.slider.numberOfDiscreteValues - 1);
    CGFloat expectedValue = self.slider.minimumValue + stepValue;
    XCTAssertEqualWithAccuracy(self.slider.value, expectedValue, 0.0001,
                               @"A slider with (%lu) discrete values should have a step value of '%.3f'.",
                               (unsigned long)self.slider.numberOfDiscreteValues, stepValue);
  }
}
```

### Version number
46.0.0

### PR DESCRIPTION
**Pull request by jmdetloff**
closes #3040

### CODE REVIEW

**Review by romoore — APPROVED** [review]
LGTM!  Love that unit test!

File: components/Slider/src/MDCSlider.m [hunk 1]
```diff
@@ -445,7 +445,11 @@ - (UIAccessibilityTraits)accessibilityTraits {
 - (void)accessibilityIncrement {
   if (self.enabled) {
     CGFloat range = self.maximumValue - self.minimumValue;
-    CGFloat newValue = self.value + kSliderAccessibilityIncrement * range;
+    CGFloat adjustmentAmount = kSliderAccessibilityIncrement * range;
+    if (self.numberOfDiscreteValues > 0) {
```
Comment (romoore) [inline components/Slider/src/MDCSlider.m]: Ah, might want to change this to `> 1` to avoid divide-by-zero.

**Comment by romoore** [comment]
Could you also provide more detail in the commit summary when you merge? Since it's our canonical history, it's nice to have the "why" in the comments to go along with the "what" in our diffs. :)
