### PR TITLE
[Dialogs] Fix button hit areas to match accessibility

### LINKED ISSUE #3664: [Dialogs] Alert button hit areas need to be at least 48 pt tall
They are currently 33 points tall.

### LINKED ISSUE #4659: [Catalog] Dialog button hit areas need to be at least 48 pt tall
They are currently 36 points tall.

Related to #3664

---
#### Internal data
- Associated internal bug: [b/117178379](http://b/117178379)

### PR DESCRIPTION
**Pull request by codeman7**
Update buttons within Dialog to have a minimum 48x48 touch area. 

Also, update example to make sure in an case where there is a large number of buttons, make sure that their is enough room in the scroll view. 

Closes #3664

### CODE REVIEW

**Comment by romoore** [comment]
This doesn't look like it's updating the Dialogs examples in the catalog. Did you reference #4659 by mistake?

File: components/Dialogs/src/private/MDCAlertControllerView+Private.m [hunk 1]
```diff
@@ -353,8 +355,22 @@ - (CGSize)calculateActionsSizeThatFitsWidth:(CGFloat)boundingWidth {
 - (void)layoutSubviews {
   [super layoutSubviews];
 
-  for (UIButton *button in self.actionButtons) {
+  for (MDCFlatButton *button in self.actionButtons) {
```
Comment (romoore) [inline components/Dialogs/src/private/MDCAlertControllerView+Private.m]: Since MDCFlatButton is scheduled for deprecation, do you want to make this an `MDCButton *` cast instead?

**Review by romoore — APPROVED** [review]
Looks good pending the reference to catalog Dialogs example.

**Review by ianegordon — APPROVED** [review]
LGTM.
Please test and document the results in this PR that hit areas should *not* overlap in a standard alert, then one at XS and XXXL with Dynamic Type enabled.

**Comment by codeman7** [comment]
Dynamic type small 
screen shot 2018-08-03 at 1 35 44 pm


Dynamic type large
screen shot 2018-08-03 at 1 37 22 pm

Overpopulated
screen shot 2018-08-03 at 1 39 15 pm
