### PR TITLE
[BottomNavigation] Fix delayed ink ripple

### LINKED ISSUE #4586: [BottomNavigation] On iPod Touch using MDCBottomNavigationBar, selection ink feels delayed in showing up
## Description

This seems to be a difference between MDCBottomNavigationBar and MDCTabBar. When selecting an item on MDCBottomNavigationBar, the ink feels like it is delayed in showing up. This becomes especially pronounced if instead of a tap a user perform a tap and hold at which point the ink doesn't show up for ~2 seconds.

On the other hand, in the MDCTabBar the ink in both the tap and long press scenario seems to show up immediately.

## Reproduction steps

1. Go to MDCDragons catalog app on an iPod touch 6th gen
2. Open Bottom Navigation -> Bottom Navigation
3. Select an item in tab bar, and then press and hold an item in tab bar.
4. Go back and then select Tab Bar -> Bottom Navigation
5. Complete same as step 3

## Expected behavior

Both step 3 and step 5 produce same latency on ink showing up.

## Actual behavior

In step 3 the ink feels much slower to show up

## Platform (please complete the following information)

 - Device: iPod Touch 6th Generation
 - OS: iOS 11.3

YouTube links which show the difference:
 
Press and hold behavior: https://youtu.be/UWc2zuMX7cI
Tapping behavior: https://youtu.be/h7CVkgCYJZw

### PR DESCRIPTION
**Pull request by romoore**
Ink ripple animations were being delayed. It appears that the root cause is
somewhere in how UIButton forwards `UIControlEventTouchDown`. Migrating to
MDCInkTouchController fixed the issue.

Closes #4586

### CODE REVIEW

File: components/BottomNavigation/src/MDCBottomNavigationBar.m [hunk 1]
```diff
@@ -469,6 +473,9 @@ - (void)setItems:(NSArray<UITabBarItem *> *)items {
     itemView.contentInsets = self.itemsContentInsets;
     itemView.contentVerticalMargin = self.itemsContentVerticalMargin;
     itemView.contentHorizontalMargin = self.itemsContentHorizontalMargin;
+    MDCInkTouchController *controller = [[MDCInkTouchController alloc] initWithView:itemView];
+    controller.delegate = self;
+    [self.inkControllers  addObject:controller];
```
Comment (jverkoey) [inline components/BottomNavigation/src/MDCBottomNavigationBar.m]: [stylenit] extra space

File: components/BottomNavigation/src/MDCBottomNavigationBar.m [hunk 2]
```diff
@@ -653,4 +651,11 @@ + (NSString *)bundlePathWithName:(NSString *)bundleName {
   return [resourcePath stringByAppendingPathComponent:bundleName];
 }
 
+#pragma mark - MDCInkTouchControllerDelegate methods
+
+- (MDCInkView *)inkTouchController:(MDCInkTouchController *)inkTouchController
+            inkViewAtTouchLocation:(CGPoint)location {
+  return ((MDCBottomNavigationItemView *)inkTouchController.view).inkView;
```
Comment (jverkoey) [inline components/BottomNavigation/src/MDCBottomNavigationBar.m]: Can/should we verify that inkTouchController.view == MDCBottomNavigationItemView?

**Review by jverkoey — APPROVED** [review]
LGTM overall - huzzah!

File: components/BottomNavigation/src/MDCBottomNavigationBar.m (hunk 1 above)
Comment (romoore) [reply components/BottomNavigation/src/MDCBottomNavigationBar.m]: Done

File: components/BottomNavigation/src/MDCBottomNavigationBar.m (hunk 2 above)
Comment (romoore) [reply components/BottomNavigation/src/MDCBottomNavigationBar.m]: Done

**Review by andrewoverton — APPROVED** [review]

**Comment by romoore** [comment]
Ink ripple animations were being delayed. It appears that the root cause is
somewhere in how UIButton forwards `UIControlEventTouchDown`. Migrating to
MDCInkTouchController fixed the issue.

Closes #4586
