### PR TITLE
[Dialogs] Removing enableAdjustableInsets and fixed-insets calculations.

### LINKED ISSUE #9785: [Dialogs] Removing enableAdjustableInsets and fixed-insets calculations.
This was filed as an internal issue. If you are a Googler, please visit [b/150085275](http://b/150085275) for more details.

---
#### Internal data
- Associated internal bug: [b/150085275](http://b/150085275)

### PR DESCRIPTION
**Pull request by galiak11**
# Description
The enableAdjustableInsets flag supported both adjustable-insets and fixed-insets calculations. This CL removes the flag and the old fixed-insets calculations, which were governed by a few private MDCxxx constants (that were also being removed in this CL).

This maintains backward compatibility of all insets, so no breaking changes are expected.

## Issue
Closes #9785 
b/150085275, cl/298842050

### CODE REVIEW

File: components/Dialogs/src/private/MDCAlertControllerView+Private.m [hunk 1]
```diff
@@ -397,21 +389,19 @@ - (void)setEnableRippleBehavior:(BOOL)enableRippleBehavior {
 
 - (CGSize)actionFittingSizeInHorizontalLayout {
   CGSize size = CGSizeZero;
-  UIEdgeInsets insets = self.enableAdjustableInsets ? self.actionsInsets : MDCDialogActionsInsets;
   NSArray<MDCButton *> *buttons = self.actionManager.buttonsInActionOrder;
   if (0 < buttons.count) {
     CGFloat maxButtonHeight = MDCDialogActionButtonMinimumHeight;
-    size.width = insets.left + insets.right;
+    size.width = self.actionsInsets.left + self.actionsInsets.right;
```
Comment (fluxminds) [inline components/Dialogs/src/private/MDCAlertControllerView+Private.m:395]: Is self.actionInsets guaranteed to have a value?

**Review by fluxminds — CHANGES_REQUESTED** [review]
Are we now only allowing adjustable insets? How are default values set?

File: components/Dialogs/src/private/MDCAlertControllerView+Private.m (hunk 1 above)
Comment (galiak11) [reply components/Dialogs/src/private/MDCAlertControllerView+Private.m:395]: Yes. It is initialized in initWithFrame, together with all other values. Also, because it is a 
UIEdgeInsets, it cannot be nil. In the worst case scenario its value would be UIEdgeInsetsZero.

Comment (fluxminds) [reply components/Dialogs/src/private/MDCAlertControllerView+Private.m:395]: I am not worried of the value being nil. My concern is originally we had those constant values set for insets, and since they have been removed, how do we set the initial value for actionsInsets?

Comment (fluxminds) [reply components/Dialogs/src/private/MDCAlertControllerView+Private.m:395]: When I was searching "actionsInsets =" it doesn't seem it was set a default value.

**Review by fluxminds — CHANGES_REQUESTED** [review]
Left some comments.

File: components/Dialogs/src/private/MDCAlertControllerView+Private.m (hunk 1 above)
Comment (galiak11) [reply components/Dialogs/src/private/MDCAlertControllerView+Private.m:395]: The value of self.actionsInsets was not modified in this PR. It already existed in the file, so you many need to expand all the file or open it in RAW mode.
The assignment "self.actionsInsets = UIEdgeInsetsMake(8.0f, 8.0f, 8.0f, 8.0f);" is in the initWithFrame: method.

Comment (fluxminds) [reply components/Dialogs/src/private/MDCAlertControllerView+Private.m:395]: I see. I was surprised to see MDCDialogActionsInsets was not used there. Thanks for pointing it out.

**Review by fluxminds — APPROVED** [review]
