### PR TITLE
[FeatureHighlight] Shown views can receive taps

### LINKED ISSUE #1888: [Feature Highlight] Taps ignored in shown view when highlight is visible
### Overview
"Showing" a view along with Feature Highlight that has a gesture recognizer (like a button with an action) prevents actions from triggering on the presented view.  It looks like the pan gesture recognizer is cancelling taps that it does not accept.

### Reproduction steps
Create a new MDCButton with an action and have Feature Highlight show that view.  For example, in FeatureHighlightTypicalUseViewController.m

```objectivec
- (void)didTapButton:(id)sender {
  MDCFloatingButton *fab = [MDCFloatingButton floatingButtonWithShape:MDCFloatingButtonShapeDefault];
  [fab setImage:[UIImage imageNamed:@"Plus"] forState:UIControlStateNormal];
  [fab sizeToFit];
  fab.backgroundColor = UIColor.orangeColor;
  [fab addTarget:self action:@selector(fabDidTap:) forControlEvents:UIControlEventTouchUpInside];
  fab.center = _button.center;

  MDCFeatureHighlightViewController *vc = [[MDCFeatureHighlightViewController alloc] initWithHighlightedView:_button andShowView:fab completion:nil];

  vc.titleText = @"Hey this is a multiline title for the Feature Highlight";
  vc.bodyText = @"This is the description of the feature highlight view controller.";
  [self presentViewController:vc animated:YES completion:nil];
}

- (void)fabDidTap:(id)sender {
  NSLog(@"Fab tapped");
}
```

### Version number
31.0.0&ndash;33.0.0

### Operating system and device
All iPhone/iPads that were tested

### PR DESCRIPTION
**Pull request by romoore**
Shown views with gesture recognizers or shown buttons with actions
should be able to receive taps while Feature Highlight is active.

Closes #1888

### CODE REVIEW

**Review by garrettmurray — APPROVED** [review]

**Comment by samnm** [comment]
I chatted briefly with Rob about this offline, but its worth mentioning Feature Highlight is intended to be used by providing a completion block. The completion block specifies whether the user accepted or dismissed the highlight. I think it's worth landing the functional change here so that buttons still can have a pressed state, but clients shouldn't be listening to touches on the button as a way to dismiss the feature highlight.

**Comment by garrettmurray** [comment]
@samnm Just a note: Without the change to the gesture recognizer, the completion block doesn't fire. The gesture rec is stealing the taps and not passing them through. But still noted that we should be using the completion block in general, so thanks.

File: components/FeatureHighlight/examples/FeatureHighlightShownViewExample.m [hunk 1]
```diff
@@ -0,0 +1,51 @@
...
+  MDCFeatureHighlightViewController *vc =
+      [[MDCFeatureHighlightViewController alloc] initWithHighlightedView:_button
+                                                             andShowView:fab
+                                                              completion:^(BOOL accepted) {
+                                                                if (accepted) {
+                                                                  [self fabDidTap:fab];
+                                                                }
+                                                              }];
+
+  [fab addTarget:vc action:@selector(acceptFeature) forControlEvents:UIControlEventTouchUpInside];
```
Comment (samnm) [inline components/FeatureHighlight/examples/FeatureHighlightShownViewExample.m]: Since we're adding `panRecognizer.cancelsTouchesInView = NO;`, we should also be listening for this control event inside MDCFeatureHighlightView. Clients shouldn't have to do anything extra like this to get Feature Highlight to work.

**Review by samnm — CHANGES_REQUESTED** [review]
@garrettmurray ah yeah that is definitely a bug then.

Rob, if we set `cancelsTouchesInView = NO` and bake in the shownView TouchUpInside listening then we should be good.

**Review by samnm — APPROVED** [review]

**Comment by romoore** [comment]
OK to merge once Travis gets off its duff.
