### PR TITLE
[AppBar] Fix app bar's top constraint that is buggy on iOS 11.0

### LINKED ISSUE #2096: [AppBar] Catalog examples cannot tap Bar Buttons
### Overview
The AppBar examples (except for Storyboard) have non-tappable buttons in the NavBar/Flexible Header view.  If you scroll the AppBar so that it goes up (toward the Status Bar), the buttons become tappable.

Some views have the navigation elements in the wrong position.

simulator screen shot - iphone se - 2017-10-06 at 02 51 52

### Reproduction steps
1. Open MDC Catalog &rarr; App Bar &rarr; Demo
2. Tap on the Back button in the App Bar

#### Expected Result
View Controller is popped

#### Actual Result
No effect

### Version number
35.2.0

### Operating system and device
iPhone SE/iOS 11.0 (Simulator), Xcode 9 (GM)

### PR DESCRIPTION
**Pull request by chuga**
The app bar's safe area is incorrectly set on iOS 11.0 by the OS. This is now fixed on 11.1, but until we can depend on that being the min iOS 11 version, we have to use this workaround -_-

Fixes #2096

### CODE REVIEW

File: components/AppBar/src/MDCAppBar.m [hunk 1]
```diff
@@ -308,22 +310,25 @@ - (void)viewDidLoad {
...
-                               attribute:NSLayoutAttributeTop
-                              multiplier:1
-                                constant:kPreIOS11StatusBarHeight].active = YES;
-#if defined(__IPHONE_11_0) && (__IPHONE_OS_VERSION_MAX_ALLOWED >= __IPHONE_11_0)
+    // We only get the actual status bar height if we're on iOS 11, because previously we were not
+    // adjusting the header height to make it smaller when the status bar is hidden.
+    // Note: We should switch to using self.view.safeAreaLayoutGuide.topAnchor once 11.1 is
+    // the min iOS 11 we support. 11.0 has a bug where the Safe Area is incorrectly calculated for
+    // this view.
+    topMargin = [UIApplication mdc_safeSharedApplication].statusBarFrame.size.height;
```
Comment (romoore) [inline components/AppBar/src/MDCAppBar.m]: Nit: I think it's better to use the maxY of the status Bar in case its frame does not start at 0?  The maxY is the offset into the window where the headerStackView should start.

```objectivec
CGRectGetMaxY([UIApplication mdc_safeSharedApplication].statusBarFrame)
```

File: components/AppBar/src/MDCAppBar.m [hunk 2]
```diff
@@ -343,6 +348,19 @@ - (void)viewWillAppear:(BOOL)animated {
...
 
+- (void)viewWillLayoutSubviews {
+  [super viewWillLayoutSubviews];
+
+#if defined(__IPHONE_11_0) && (__IPHONE_OS_VERSION_MAX_ALLOWED >= __IPHONE_11_0)
+  if (@available(iOS 11.0, *)) {
+    // We only get the actual status bar height if we're on iOS 11, because previously we were not
+    // adjusting the header height to make it smaller when the status bar is hidden.
+    _verticalConstraint.constant =
+        [UIApplication mdc_safeSharedApplication].statusBarFrame.size.height;
```
Comment (romoore) [inline components/AppBar/src/MDCAppBar.m]: Same suggestion here

**Review by romoore — APPROVED** [review]

File: components/AppBar/src/MDCAppBar.m (hunk 1 above)
Comment (chuga) [reply components/AppBar/src/MDCAppBar.m]: Done (even though I've never seen a status bar frame that doesn't start at 0 :shrug:

File: components/AppBar/src/MDCAppBar.m (hunk 2 above)
Comment (chuga) [reply components/AppBar/src/MDCAppBar.m]: Done
