### PR TITLE
[Warnings Fix] Block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior.

### LINKED ISSUE #2932: Block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior
After treating warnings as errors, building the project is failing due to the following warning in many cases:
Block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior.
Investigate and fix all such warnings.

### PR DESCRIPTION
**Pull request by mohammadcazig**
Using self./self-> in order to explicitly mention self in the block. 

Fixes  #2932

### CODE REVIEW

File: components/BottomAppBar/src/MDCBottomAppBarView.m [hunk 1]
```diff
@@ -325,8 +325,8 @@ - (void)setFloatingButtonElevation:(MDCBottomAppBarFloatingButtonElevation)float
     [_floatingButton setElevation:1 forState:UIControlStateNormal];
     dispatch_after(dispatch_time(DISPATCH_TIME_NOW, kMDCButtonAnimationDuration * NSEC_PER_MSEC),
                    dispatch_get_main_queue(), ^{
-                     [self insertSubview:_floatingButton atIndex:subViewIndex];
-                     [_floatingButton setElevation:elevation forState:UIControlStateNormal];
+                     [self insertSubview:self.floatingButton atIndex:subViewIndex];
```
Comment (romoore) [inline components/BottomAppBar/src/MDCBottomAppBarView.m:328]: Please make this a weak reference. If the view is no longer retained, we shouldn't keep it around just to do these animations.

File: components/Collections/src/private/MDCCollectionInfoBarView.m [hunk 2]
```diff
@@ -232,17 +232,17 @@ - (void)dismissAnimated:(BOOL)animated {
       delay:0
       options:UIViewAnimationOptionCurveEaseIn
       animations:^{
-        _backgroundView.transform = CGAffineTransformMakeTranslation(0, _backgroundTransformY);
+        self.backgroundView.transform = CGAffineTransformMakeTranslation(0, self->_backgroundTransformY);
```
Comment (romoore) [inline components/Collections/src/private/MDCCollectionInfoBarView.m]: Nit/Formatting: This looks like it's over 100 columns. Please break it into 2 lines.

File: components/NavigationBar/src/MDCNavigationBar.m [hunk 3]
```diff
@@ -453,7 +453,7 @@ - (void)observeValueForKeyPath:(NSString *)keyPath
   if (context == kKVOContextMDCNavigationBar) {
     void (^mainThreadWork)(void) = ^{
       @synchronized(self->_observedNavigationItemLock) {
-        if (object != _observedNavigationItem) {
+        if (object != self->_observedNavigationItem) {
```
Comment (romoore) [inline components/NavigationBar/src/MDCNavigationBar.m:456]: Should this be made weak to avoid keeping the the navigationBar around if it's no longer retained otherwise?

File: components/PageControl/src/MDCPageControl.m [hunk 4]
```diff
@@ -173,7 +173,7 @@ - (void)setCurrentPage:(NSInteger)currentPage
       // destination.
       dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(duration * NSEC_PER_SEC)),
                      dispatch_get_main_queue(), ^{
-                       [_trackLayer removeTrackTowardsPoint:shouldReverse ? startPoint : endPoint
+                       [self->_trackLayer removeTrackTowardsPoint:shouldReverse ? startPoint : endPoint
```
Comment (romoore) [inline components/PageControl/src/MDCPageControl.m:176]: I think this should be made weak, since the view may no longer be retained.

File: components/PageControl/src/MDCPageControl.m [hunk 5]
```diff
@@ -269,11 +269,11 @@ - (void)scrollViewDidScroll:(UIScrollView *)scrollView {
                      NSInteger currentPage = [self scrolledPageNumber:scrollView];
                      [self setCurrentPage:currentPage animated:YES duration:animation.duration];
 
-                     CGFloat transformX = scrolledPercentage * _trackLength;
-                     [_animatedIndicator updateIndicatorTransformX:transformX
-                                                          animated:YES
-                                                          duration:animation.duration
-                                               mediaTimingFunction:animation.timingFunction];
+                     CGFloat transformX = scrolledPercentage * self->_trackLength;
+                     [self->_animatedIndicator updateIndicatorTransformX:transformX
```
Comment (romoore) [inline components/PageControl/src/MDCPageControl.m:273]: Same question about making self weak here.

**Review by romoore — COMMENTED** [review]
Please consider breaking this up into PRs focused on individual (or small numbers of) components.

**Comment by ianegordon** [comment]
We should definitely weakify where appropriate, but this is already a big change to silence the warning (without actually changing the code).
Recommend we land this and weakify in another PR.

**Review by ianegordon — APPROVED** [review]

**Comment by romoore** [comment]
Please open a backlog issue to investigate the weakification candidates.

**Comment by mohammadcazig** [comment]
I have made an issue to address the weak/strong reference issue. #2934

File: components/Collections/src/private/MDCCollectionInfoBarView.m (hunk 2 above)
Comment (mohammadcazig) [reply components/Collections/src/private/MDCCollectionInfoBarView.m]: done.

**Review by romoore — APPROVED** [review]

**Comment by mohammadcazig** [comment]
Kokoro did not succeed, because it's not working properly but travis has passed.
