### PR TITLE
[Cards] Fix shadow elevation values for outlined cards

### LINKED ISSUE #6045: [Cards] Outlined themed Card variant should not have an elevation
The outlined themed card displays an elevation when it should not according to [the Material Guidelines article for Cards](https://material.io/design/components/cards.html#card-collections).

### Steps to reproduce
```objc
[self.card applyOutlinedThemeWithScheme:self.containerScheme];
```

### Expected Result
Note the outlined border and no shadow:
screen shot 2018-12-18 at 11 57 38 am

### Actual Result
Note the outline AND shadow:
testoutlinedthemedcard_11_2 2x

---
#### Internal data
- Associated internal bug: [b/121194302](http://b/121194302)

### PR DESCRIPTION
**Pull request by rami-a**
### Context
After adding snapshot tests for Cards, we noticed that the outlined variant had elevation when it was not supposed to.

### The problem
Cards shadow elevation values were not correct

### The fix
Update the values, update the unit tests, and update the snapshot goldens.

### Related bugs
Closes #6045

### CODE REVIEW

File: components/Cards/tests/unit/CardsMaterialThemingTests.swift [hunk 1]
```diff
@@ -99,11 +99,10 @@ class CardsMaterialThemingTests: XCTestCase {
...
 
     // Test remaining properties
-    XCTAssertEqual(card.borderWidth(for: .normal), 1, accuracy: 0.001)
-    XCTAssertEqual(card.borderWidth(for: .selected), 1, accuracy: 0.001)
-    XCTAssertEqual(card.borderWidth(for: .highlighted), 1, accuracy: 0.001)
-    XCTAssertEqual(card.borderWidth(for: .disabled), 1, accuracy: 0.001)
-    XCTAssertEqual(card.shadowElevation(for: .highlighted), ShadowElevation(rawValue: 4))
+    [UIControlState.normal, .highlighted, .selected, .disabled].forEach {
+      XCTAssertEqual(card.shadowElevation(for: $0), ShadowElevation.none)
+      XCTAssertEqual(card.borderWidth(for: $0), 1, accuracy: 0.001)
```
Comment (jverkoey) [inline components/Cards/tests/unit/CardsMaterialThemingTests.swift]: Add the `$0` to the assertion message please; this will let us know which state failed in case one of these assertions fails.

**Review by jverkoey — APPROVED** [review]
Yay snapshot tests!

File: components/Cards/tests/unit/CardsMaterialThemingTests.swift (hunk 1 above)
Comment (rami-a) [reply components/Cards/tests/unit/CardsMaterialThemingTests.swift]: Done
