### PR TITLE
[NavigationBar] Allow flexible height/insets in MDCNavigationBar

### LINKED ISSUE #253: Button Bar's height can't be configured
The Button Bar's height is fixed to either 56 or 64 depending on the device. This reduces the ability to use the button bar in situations other than typical navigation or tool bars.

Open questions:

Should we infer the height from the buttons?
Should we not change the height and expect the owner to enforce it?

I'm leaning towards the latter.

### LINKED ISSUE #2793: Wrong vertical alignment of bar buttons in MDCAppBar when using custom height
When using MDCAppBar with a custom minimumHeight set on the MDCFlexibleHeaderView, bar buttons have incorrect vertical alignment because the MDCNavigationBar still uses the default height of 56. The button bar is added to the MDCNavigationBar, which has a height of 56. The buttons are later vertically aligned to be in the middle.

This is because sizeThatFits: on MDCNavigationBar uses a hardcoded value.

### PR DESCRIPTION
**Pull request by AlimoRabbani**
This is a roll-forward for #2974, with fixes for the internal issues. We now have an API, and only change the behavior when the API is used. That API should be mainlined when all clients adopt the new behavior.

[titleLabel with titleView with useFlexibleTopBottomInsets=YES](https://user-images.githubusercontent.com/2232489/38525318-c7890406-3c1f-11e8-81f3-b72afee2dd71.png)
[titleLabel with titleView with useFlexibleTopBottomInsets=YES](https://user-images.githubusercontent.com/2232489/38525320-c7a32570-3c1f-11e8-9e46-e232307a5a0a.png)

[titleLabel with titleView with useFlexibleTopBottomInsets=NO (current behavior)](https://user-images.githubusercontent.com/2232489/38525261-9bf7b2f6-3c1f-11e8-9942-048c139e6163.png)
[titleLabel with titleView with useFlexibleTopBottomInsets=NO (current behavior)](https://user-images.githubusercontent.com/2232489/38525286-b150692c-3c1f-11e8-94b3-167d75393870.png)

[titleView with useFlexibleTopBottomInsets=NO (current behavior)](https://user-images.githubusercontent.com/2232489/38525208-72545e4a-3c1f-11e8-8e5e-eb9b3457c8b3.png)
[titleView with useFlexibleTopBottomInsets=YES](https://user-images.githubusercontent.com/2232489/38525209-725f4012-3c1f-11e8-838d-f6872a760931.png)

Internal testing done in cl/192612758.

closes #2793
closes #253

### CODE REVIEW

File: components/NavigationBar/src/MDCNavigationBar.m [hunk 1]
```diff
@@ -405,14 +421,12 @@ - (void)layoutSubviews {
...
-
-  CGFloat height = ([self usePadInsets] ? kNavigationBarPadDefaultHeight : kNavigationBarDefaultHeight);
-  return CGSizeMake(UIViewNoIntrinsicMetric, height);
+  CGFloat maxHeight =
+      [self usePadInsets] ? kNavigationBarPadDefaultHeight : kNavigationBarDefaultHeight;
+  CGFloat minHeight = kNavigationBarMinHeight;
+  CGFloat height =
+      self.useFlexibleTopBottomInsets ? MIN(MAX(size.height, minHeight), maxHeight) : maxHeight;
+  return CGSizeMake(size.width, height);
 }
```
Comment (jverkoey) [inline components/NavigationBar/src/MDCNavigationBar.m:430]: I've been under the impression that we had to implement intrinsicContentSize in order to support auto layout. Will removing this API break autolayout for clients?

**Review by jverkoey — APPROVED** [review]
lgtm pending question about autolayout.

File: components/NavigationBar/src/MDCNavigationBar.m (hunk 1 above)
Comment (AlimoRabbani) [reply components/NavigationBar/src/MDCNavigationBar.m:430]: I'm not sure if it really breaks autolayout, and I can't find details on why it was added in https://github.com/material-components/material-components-ios/commit/c5cf080b3e2fc5cfd40357901d39f3ea3db04beb

I'll keep it here just to be safe.

**Comment by AlimoRabbani** [comment]
Added back intrinsicContentSize.

**Comment by AlimoRabbani** [comment]
Do we need to force run a kokoro build on this?

**Comment by AlimoRabbani** [comment]
Internal testing of this was done in cl/192612758.
