### PR TITLE
[AppBar] Initial frame wrong in MDCAppBarViewController for iPad split screen

### LINKED ISSUE #5479: Internal issue: b/118126496
This was filed as an internal issue. If you are a Googler, please visit [b/118126496](http://b/118126496) for more details.

---
#### Internal data
- Associated internal bug: [b/118126496](http://b/118126496)

### PR DESCRIPTION
**Pull request by rami-a**
### Context
When the migration from MDCAppBar to MDCAppBarViewController occurred, a small piece of code was left out, specifically in `addSubviewsToParent`.
### The problem
When running the catalog app in split screen on iPad and viewing the examples for MDCAppBarViewController, the App Bar is not sized correctly and overflows outside of the bounds.
### The fix
Re-add the frame width modifying logic from `addSubviewsToParent` into `didMoveToParentViewController:parent` for MDCAppBarViewController.
### Related bugs
closes #5479, b/118126496

### Screenshots
| Before | After |
| - | - |
|before|after|

### CODE REVIEW

File: components/AppBar/src/MDCAppBarViewController.m [hunk 1]
```diff
@@ -246,6 +246,10 @@ - (void)didMoveToParentViewController:(UIViewController *)parent {
   [super didMoveToParentViewController:parent];
 
   [self.navigationBar observeNavigationItem:parent.navigationItem];
+
+  CGRect frame = self.view.frame;
+  frame.size.width = parent.view.bounds.size.width;
```
Comment (ianegordon) [inline components/AppBar/src/MDCAppBarViewController.m]: We need to use CGRectGetWidth() if we are using non-standardized CGRects.

**Review by ianegordon — CHANGES_REQUESTED** [review]

File: components/AppBar/src/MDCAppBarViewController.m (hunk 1 above)
Comment (rami-a) [reply components/AppBar/src/MDCAppBarViewController.m]: Done

**Review by ianegordon — APPROVED** [review]
