### PR TITLE
[BottomSheet] Mark init unavailable

### LINKED ISSUE #8109: [BottomSheet] Initializing with `init` causes a crash
MDCBottomSheetController does not allow me to initialize with the `init` method but that method is not marked unavailable. If I initialize with that method in `viewDidLoad` my app crashes.

Screen Shot 2019-07-29 at 7 00 45 AM

### PR DESCRIPTION
**Pull request by codeman7**
Currently the MDCBottomSheet controller does not mark its `init` method as unavailable but the contentViewController is marked as `readonly` so clients would have to _initialize_ with a contentViewController. If the contentViewController is `nil` then when `addChildViewController` is called in `viewDidLoad` this causes a crash as you cannot pass `nil` to an array.

Closes #8109

### CODE REVIEW

File: components/BottomSheet/src/MDCBottomSheetController.h [hunk 1]
```diff
@@ -110,6 +110,8 @@
  */
 @property(nonatomic, assign) MDCShadowElevation elevation;
 
+- (nonnull instancetype)init NS_DEPRECATED_IOS(9_0, 9_0, "Use initWithContentViewController:");
```
Comment (romoore) [inline components/BottomSheet/src/MDCBottomSheetController.h]: Shouldn't this be `NS_UNAVAILABLE`?

Comment (romoore) [inline components/BottomSheet/src/MDCBottomSheetController.h]: You mention in the PR summary that there's a potential crash. Unless you mark `init` is unavailable, please add guards to `viewDidLoad` to prevent the crash.

**Review by romoore — CHANGES_REQUESTED** [review]

**Comment by romoore** [comment]
Please file an Issue for this crash/bug and link to it from the PR summary.

File: components/BottomSheet/src/MDCBottomSheetController.h (hunk 1 above)
Comment (codeman7) [reply components/BottomSheet/src/MDCBottomSheetController.h]: After checking internally nobody is using this. But, there is a chance clients are using it via CocoaPods, I think it is better to do deprecated this week and unavailable next what do you think?

Comment (codeman7) [reply components/BottomSheet/src/MDCBottomSheetController.h]: Updated.

Comment (romoore) [reply components/BottomSheet/src/MDCBottomSheetController.h]: My understanding is that it always caused a crash in any client that used it.  In that case this is a bug fix and not a breaking change. 

If I've misunderstood the issue, please try to make the referenced Issue and/or PR summary a bit more explicit about the crash conditions.

Comment (codeman7) [reply components/BottomSheet/src/MDCBottomSheetController.h]: If a client never calls `viewDidLoad` then the crash wouldn't occur. For instance if they were using the `init` in a test file.

```objc
- (void)testFoo {
  MDCBottomSheetController *bottomSheet = [[MDCBottomSheetController alloc] init];

  bottomSheet.elevation = 5;

  XCTAssertEqualWithAccuracy(bottomSheet.elevation, 5, 0.001);
}
```

That would not cause a crash but if they were using it in production to present a bottom sheet then the crash would occur.

Comment (romoore) [reply components/BottomSheet/src/MDCBottomSheetController.h]: I think it's fair to assume that being unable to use `init` in production meant that nobody was using it.  I think we should mark `-init` unavailable and consider this to be a non-breaking bug fix PR.  Is that OK with you?

Comment (codeman7) [reply components/BottomSheet/src/MDCBottomSheetController.h]: Done

**Review by romoore — APPROVED** [review]
