### PR TITLE
[ActionSheet] Try to fix MaterialComponentsAlpha

### LINKED ISSUE #5380: Could not build Objective-C module 'MaterialComponentsAlpha'
Then I trying to integrate Both MaterialComponents and MaterialComponentsAlpha to my swift project I am getting this error **"Could not build Objective-C module 'MaterialComponentsAlpha' "** , 

I tried creating bridge header and Imported <MaterialComponentsAlpha> but It didn't work and it is throughs error "MaterialComponentsAlpha file didnt find" .

The given below is my pod file.

```ruby
target 'MaterialDesign' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MaterialDesign
  pod 'MaterialComponents'
  pod 'MaterialComponentsAlpha', :git => 'https://github.com/material-components/material-components-ios.git'
end
```

how to use both MaterialComponentsAlpha and MaterialComponents in the swift project.

---
#### Internal data
- Associated internal bug: [b/117594919](http://b/117594919)

### PR DESCRIPTION
**Pull request by andrewoverton**
With these changes I'm able to create a project with `MaterialComponentsAlpha` in its Podile and import `MaterialComponentsAlpha.MaterialActionSheet` into a Swift file in said project without getting the "Could not build Objective-C module" error message.
 
`@import MaterialComponents.MaterialTypographyScheme;` and `#import <MaterialComponents/MaterialTypographyScheme.h>` both seem to work. With the `#import` statement you can jump to the definition, and with the `@import` statement you can't, which is a little weird!

This change also brings the number of validation errors from running `pod lib lint MaterialComponentsAlpha.podspec` from 6 down to 1. I haven't figured out how to get rid of the last one, which is a little concerning, and suggests that this may not be a complete fix? Hmmm. The compilation errors seem to be fixed though!

Closes #5380. Maybe.

### CODE REVIEW

**Review by codeman7 — APPROVED** [review]
If the team like this approach I am all for it! Why not use the #import instead of @import it sounds like #import was better?

File: components/ActionSheet/src/ActionSheetThemer/MDCActionSheetScheme.h [hunk 1]
```diff
@@ -12,8 +12,8 @@
 // See the License for the specific language governing permissions and
 // limitations under the License.
 
-#import "MaterialColorScheme.h"
-#import "MaterialTypographyScheme.h"
+@import MaterialComponents.MaterialColorScheme;
```
Comment (romoore) [inline components/ActionSheet/src/ActionSheetThemer/MDCActionSheetScheme.h]: Please make sure that this compiles and links using the internal build systems. Although we don't expect any clients to use Alpha components directly, we would want to catch build errors early in development and should expect Alpha components to build using our internal tooling.

**Review by ianegordon — APPROVED** [review]
LGTM.
Please add a note that this is 'Risky' with some comments to our release engineer that they may need to update our internal tools to mimic the kokoro changes in this PR.
(I don't think this is actually Risky, but we do want to grab their attention)

**Comment by jverkoey** [comment]
@andrewoverton you can help test this by mirroring this internally and running a test. [go/mdc-ios-test-pull-requests-internally](http://go/mdc-ios-test-pull-requests-internally)

**Comment by andrewoverton** [comment]
@jverkoey, thanks for the tip. I think [cl/219365016](http://cl/219365016) should make it all ok :/

**Comment by andrewoverton** [comment]
Uh oh @jverkoey.. The .kokoro script makes the imports work with bazel, and then converts them back. The regex added in this PR adds a comment to the temporary/intermediate imports it generates so there aren't a bunch of false positive matches in the reverse conversion. This works fine. However, if you create a PR from internal code using internal tools there are no such comments to prevent false positives and you end up with a giant PR with like hundreds of files changed: #5576. So, this approach needs some rethinking!

**Review by romoore — DISMISSED** [review]
Marking as needing changes just so the "Big Green Button" isn't shown.

**Comment by andrewoverton** [comment]
I found a way to avoid the false positives. It's a little less lightweight, but it'll do for now. If you're a googler check out [cl/220325160](http://cl/220325160) 🌚

**Review by romoore — APPROVED** [review]
