### PR TITLE
[Collections] Use image cache for selection icons

### LINKED ISSUE #1637: [Collections] Improve MDCCollectionViewCell scrolling performance by using imageNamed:
### Overview
Scrolling MDCCollectionViewCell results in a slow-down due to the use of -imageWithContentsOfFile:`. This is causing the Catalog to render only about 25-30 frames per second on an iPad 4 Mini/iOS 10.3.2.  Image loading for *selected state* icons is approximately 30% of the main thread CPU time.

By changing to `-imageNamed:inBundle:compatibleWithTraitCollection:` we can nearly eliminate this loading time and increase FPS ~~to over 50~~ (not always this high).

### Reproduction steps
1. Modify CollectionCellsTextExample.m to populate several thousand cells
1. Scroll rapidly while running instruments (Core Animation)

### Version number
26.0.0

### Operating system and device
iPad 4 Mini/iOS 10.3.2

### Related issues
#1606

### PR DESCRIPTION
**Pull request by romoore**
The selected/unselected state icons are reloaded from disk on every
prepareForReuse call.  Using the cache-backed `-imageNamed` family of
methods in UIImage reduces the overhead required to reload those images.

Closes #1637

### CODE REVIEW

File: components/CollectionCells/src/MDCCollectionViewCell.m [hunk 1]
```diff
@@ -424,16 +424,32 @@ - (void)updateInterfaceForEditing {
...
+
 - (void)setSelected:(BOOL)selected {
   [super setSelected:selected];
   if (selected) {
     _editingSelectorImageView.image =
-        [UIImage imageWithContentsOfFile:[MDCIcons pathFor_ic_check_circle]];
+                  [UIImage imageNamed:@"ic_check_circle"
+                             inBundle:[MDCCollectionViewCell
+                                          bundleWithName:@"MaterialIcons_ic_check_circle"]
+        compatibleWithTraitCollection:nil];
```
Comment (samnm) [inline components/CollectionCells/src/MDCCollectionViewCell.m]: As discussed offline, this should probably be moved in to the MDCIcon+\<Name\> generated by sync_icons.sh.

**Review by samnm — CHANGES_REQUESTED** [review]

File: components/CollectionCells/src/MDCCollectionViewCell.m [hunk 2]
```diff
@@ -424,16 +424,32 @@ - (void)updateInterfaceForEditing {
 
 #pragma mark - Selecting
 
++ (NSBundle *)bundleWithName:(NSString *)bundleName {
```
Comment (ianegordon) [inline components/CollectionCells/src/MDCCollectionViewCell.m]: Ideally we expose this in MDCIcons.  I would add a TODO here noting that.

Consider a bit more context on the method name, perhaps:
- bundleWithIconName:(NSString *)iconName

Naming is hard.

File: components/CollectionCells/src/MDCCollectionViewCell.m [hunk 3]
```diff
@@ -424,16 +424,32 @@ - (void)updateInterfaceForEditing {
...
+
+  return bundle;
+}
+
 - (void)setSelected:(BOOL)selected {
   [super setSelected:selected];
   if (selected) {
     _editingSelectorImageView.image =
-        [UIImage imageWithContentsOfFile:[MDCIcons pathFor_ic_check_circle]];
+                  [UIImage imageNamed:@"ic_check_circle"
```
Comment (ianegordon) [inline components/CollectionCells/src/MDCCollectionViewCell.m]: formatting.

File: components/CollectionCells/src/MDCCollectionViewCell.m [hunk 4]
```diff
@@ -424,16 +424,32 @@ - (void)updateInterfaceForEditing {
...
+        compatibleWithTraitCollection:nil];
     _editingSelectorImageView.tintColor = self.editingSelectorColor;
     self.accessibilityTraits |= UIAccessibilityTraitSelected;
   } else {
     _editingSelectorImageView.image =
-        [UIImage imageWithContentsOfFile:[MDCIcons pathFor_ic_radio_button_unchecked]];
+    [UIImage imageNamed:@"ic_radio_button_unchecked"
+               inBundle:[MDCCollectionViewCell
+                         bundleWithName:@"MaterialIcons_ic_radio_button_unchecked"]
+compatibleWithTraitCollection:nil];
```
Comment (ianegordon) [inline components/CollectionCells/src/MDCCollectionViewCell.m]: Formatting.
Since compatibleWIthTraitCollection: won't fit, align the ':' for the other parameters, then indent this one 4 space past the original "[UIImage imageName:..."

**Review by ianegordon — CHANGES_REQUESTED** [review]

File: components/private/Icons/src/MDCIcons.h [hunk 5]
```diff
@@ -20,7 +20,8 @@
  The MDCIcons class is designed to be extended by adding individual icon extensions to a project.
 
  Individual icons can be accessed by importing their MaterialIcons+<icon_name>.h header and calling
- [MDCIcons pathFor_<icon_name>] to get the icon's file system path.
+ [MDCIcons pathFor_<icon_name>] to get the icon's file system path or calling
```
Comment (ianegordon) [inline components/private/Icons/src/MDCIcons.h:23]: s/pathor/path or/

File: components/private/Icons/src/MDCIcons+BundleLoader.h [hunk 6]
```diff
@@ -20,12 +20,15 @@
  The MDCIcons class is designed to be extended by adding individual icon extensions to a project.
 
  Individual icons can be accessed by importing their MaterialIcons+<icon_name>.h header and calling
- [MDCIcons pathFor_<icon_name>] to get the icon's file system path.
+ [MDCIcons pathFor_<icon_name>] to get the icon's file system pathor calling
```
Comment (ianegordon) [inline components/private/Icons/src/MDCIcons+BundleLoader.h]: s/pathor/path or/

File: scripts/sync_icons.sh [hunk 7]
```diff
@@ -230,6 +236,12 @@ __attribute__((visibility("default")))
   return [self pathForIconName:kIconName withBundleName:kBundleName];
 }
 
++ (nullable UIImage *)imageFor_$icon_name {
+  NSBundle *bundle = [self bundleNamed:kBundleName];
+  return [UIImage imageNamed:kIconName inBundle:bundle
+             compatibleWithTraitCollection:nil];
```
Comment (ianegordon) [inline scripts/sync_icons.sh]: If you line break in the middle of a method call, all parameters must be on their own line.
Or, to put it another way:
```
return [UIImage imageNamed:kIconName
                  inBundle:bundle
    compatibleWithTraitCollection:nil];
```

Note that compatible won't fit if you try and align colons, so it is indented 4 spaces.

**Review by ianegordon — CHANGES_REQUESTED** [review]

File: components/private/Icons/src/MDCIcons.h (hunk 5 above)
Comment (romoore) [reply components/private/Icons/src/MDCIcons.h:23]: I don't see the "pathor" here, I don't think this file had the paste bug.

File: components/private/Icons/src/MDCIcons+BundleLoader.h (hunk 6 above)
Comment (romoore) [reply components/private/Icons/src/MDCIcons+BundleLoader.h]: Done

File: scripts/sync_icons.sh (hunk 7 above)
Comment (romoore) [reply scripts/sync_icons.sh]: Done

**Review by ianegordon — APPROVED** [review]

**Comment by ianegordon** [comment]
Waiting for Travis, but local testing was successful.
ic_arrow_back continued to have the manually added switch between the old and new style as expected.
LGTM.

File: components/private/Icons/icons/ic_check/src/MaterialIcons+ic_check.h [hunk 8]
```diff
@@ -29,4 +29,10 @@
  */
 + (nonnull NSString *)pathFor_ic_check;
 
+/*
+ Returns the image for the ic_check image contained in
+ MaterialIcons_ic_check.bundle.
+ */
++ (nullable UIImage *)imageFor_ic_check;
```
Comment (samnm) [inline components/private/Icons/icons/ic_check/src/MaterialIcons+ic_check.h:36]: These files are autogenerated by sync_icons.sh. Did you look in to updating sync_icons with the imageFor method?

Comment (samnm) [reply components/private/Icons/icons/ic_check/src/MaterialIcons+ic_check.h:36]: Oh, you did. LGTM.

**Review by samnm — APPROVED** [review]
