### PR TITLE
[NavigationBar] Improve centering when barButtonItems are asymmetric

### LINKED ISSUE #1662: [AppBar] App bar centering does not account for unevenly-sized BarButton items
### Overview
The AppBar does not correctly determine how much center space is available to it when the left and right BarButtonItems are of different widths.   It also attempts to center the title no matter how much space is available after the BarButtonItems are layed-out.  This appears to deviate from UINavigationBar.

#### UINavigationBar default behavior
uinavigation-behavior

### Reproduction steps
1. Open the MDCCatalog app on a narrow-width device (iPhone 4s/iPhone 5)
1. Navigate to "Collections"
1. Navigate to "Grid Example"
1. Note the overlap of the ellipsis in the title and the "UPDATE STYLE" right bar button item

#### AppBar visual bug in Collections/Grid Example
grid-example-overlap

### Version number
27.0.0

### Operating system and device
iOS 10.3.1 (Simulator) iPhone 5 (Simulator)

### PR DESCRIPTION
**Pull request by romoore**
Adjusting the NavigationBar layout computation to determine if there is sufficient space in the center of the navigation bar before adjusting the Title frame.

**Original RTL Behavior**
navbar-center-orig

**Updated RTL Behavior**
navbar-center-final

Closes #1662, #1650

### CODE REVIEW

File: components/NavigationBar/src/MDCNavigationBar.m [hunk 1]
```diff
@@ -466,19 +466,46 @@ - (CGRect)mdc_frameAlignedVertically:(CGRect)frame
...
+        titleLeftInset = textInsets.right;
+        titleRightInset = textInsets.left;
       }
-      if (minX <= xOrigin) {
+
+      CGFloat midX = CGRectGetMidX(self.bounds);
+      CGFloat leftMidSpaceX = midX - CGRectGetMaxX(leftButtonBar.frame) - titleLeftInset;
+      CGFloat rightMidSpaceX = CGRectGetMinX(rightButtonBar.frame) - midX - titleRightInset;
+      CGFloat halfFrameWidth = CGRectGetWidth(frame) / 2;
+      if (leftMidSpaceX >= halfFrameWidth && rightMidSpaceX >= halfFrameWidth) {
```
Comment (ianegordon) [inline components/NavigationBar/src/MDCNavigationBar.m]: This is a bit tricky to follow.
Can we add a one line comment above this if?  Something along the lines of the following, which is a guess:
// If left button bar and right button bar will overlap the title shrink the title's frame

**Review by ianegordon — CHANGES_REQUESTED** [review]

**Review by ianegordon — APPROVED** [review]

**Comment by ianegordon** [comment]
Please address comment before merge.

File: components/NavigationBar/src/MDCNavigationBar.m (hunk 1 above)
Comment (romoore) [reply components/NavigationBar/src/MDCNavigationBar.m]: Done
