### PR TITLE
[FlexibleHeader] Clear the shadow opacity when a nil trackingScrollView is set.

### LINKED ISSUE #5281: [FlexibleHeader] Incorrect shadow after clearing trackingScrollView
When trackingScrollView on MDCFlexibleHeaderView is explicitly set to nil, an incorrect shadow is shown, there should be no shadow, similar to when trackingScrollView is not set.

## Reproduction steps
in MDCDragons, add the following to FlexibleHeaderTypicalUseViewController:

- (void)viewDidAppear:(BOOL)animated {
  [super viewDidAppear:animated];
  self.fhvc.headerView.trackingScrollView = nil;
}

Run the app and open FlexibleHeader->FlexibleHeader.

## Expected behavior
No shadow, even though contentInset.top is set to 0 and the scrollView content is hidden behind the app bar.

## Actual behavior
Observe a shadow is added.

## Additional context
This behavior was originally added in https://github.com/material-components/material-components-ios/commit/5ddf405c43ca2abb700877b8fbbf995e2ed422c1, but I'm not sure why.

---
#### Internal data
- Associated internal bug: [b/117293175](http://b/117293175)

### PR DESCRIPTION
**Pull request by AlimoRabbani**
Fixes #5281

### CODE REVIEW

File: components/FlexibleHeader/src/MDCFlexibleHeaderView.m [hunk 1]
```diff
@@ -1465,8 +1459,8 @@ - (void)setTrackingScrollView:(UIScrollView *)trackingScrollView {
     }
 
     // When the tracking scroll view is cleared we need a shadow update.
-    if (!self.trackingScrollView) {
-      [self fhv_accumulatorDidChange];
+    if (!_trackingScrollView) {
+      self.layer.shadowOpacity = 0;
```
Comment (jverkoey) [inline components/FlexibleHeader/src/MDCFlexibleHeaderView.m:1463]: Hah. This was a funny bit of logic. Thank you for flattening.

**Review by jverkoey — APPROVED** [review]
