### PR TITLE
[AppBar] Make MDCNavigationBar and MDCButtonBar size dynamically

### LINKED ISSUE #253: Button Bar's height can't be configured
The Button Bar's height is fixed to either 56 or 64 depending on the device. This reduces the ability to use the button bar in situations other than typical navigation or tool bars.

Open questions:

Should we infer the height from the buttons?
Should we not change the height and expect the owner to enforce it?

I'm leaning towards the latter.

### LINKED ISSUE #2793: Wrong vertical alignment of bar buttons in MDCAppBar when using custom height
When using MDCAppBar with a custom minimumHeight set on the MDCFlexibleHeaderView, bar buttons have incorrect vertical alignment because the MDCNavigationBar still uses the default height of 56. The button bar is added to the MDCNavigationBar, which has a height of 56. The buttons are later vertically aligned to be in the middle.

This is because sizeThatFits: on MDCNavigationBar uses a hardcoded value.

### PR DESCRIPTION
**Pull request by AlimoRabbani**
Make MDCNavigationBar and MDCButtonBar size dynamically. This allows setting a height lower than 56.0f on the AppBar, and still have everything vertically aligned in the middle.

Currently, these two components don't respect the height that is used in MDCAppBar, and position the buttons incorrectly when a height lower than 56.0f is used.

Some screenshots from the catalog app:
[Before with height 44.0f (note the incorrect alignment)](https://user-images.githubusercontent.com/2232489/36812789-4e5fa36c-1ca0-11e8-9c19-6ce8986df60a.png)
[Before with height 56.0f (default)](https://user-images.githubusercontent.com/2232489/36812788-4e4a4ce2-1ca0-11e8-8042-2e31f183c593.png)
[Before with height 100.0f](https://user-images.githubusercontent.com/2232489/36812787-4e2e6022-1ca0-11e8-855f-d3fc84e46e21.png)

[After with height 44.0f (note the corrected alignment)](https://user-images.githubusercontent.com/2232489/36812786-4e1f49ac-1ca0-11e8-8e58-2d97ac53e357.png)
[After with height 56.0f (no changes)](https://user-images.githubusercontent.com/2232489/36812785-4e10ebc8-1ca0-11e8-87e6-5f8db029336a.png)
[After with height 100.0f (no changes)](https://user-images.githubusercontent.com/2232489/36812784-4de2b55a-1ca0-11e8-8629-21a5aed6bcf5.png)

closes #2793 
closes #253

### CODE REVIEW

**Comment by ianegordon** [comment]
Hi @AlimoRabbani , thanks for the PR!  As you may have noticed, the underlying issue is some assumptions we've made about the status bar height and our interactions with safeAreaOffset in MDCAppBar.  Let's see if there is a general solution in AppBar that will let us avoid adding to the API surface.

File: components/NavigationBar/src/MDCNavigationBar.m [hunk 1]
```diff
@@ -27,8 +27,8 @@
 
 static const CGFloat kNavigationBarDefaultHeight = 56;
 static const CGFloat kNavigationBarPadDefaultHeight = 64;
-static const UIEdgeInsets kTextInsets = {16, 16, 16, 16};
-static const UIEdgeInsets kTextPadInsets = {20, 16, 20, 16};
+static const UIEdgeInsets kTextInsets = {0, 16, 0, 16};
```
Comment (jverkoey) [inline components/NavigationBar/src/MDCNavigationBar.m:30]: Do these constants need to change?

**Review by jverkoey — CHANGES_REQUESTED** [review]
Overall looks good to me, with one outstanding question.

File: components/NavigationBar/src/MDCNavigationBar.m (hunk 1 above)
Comment (AlimoRabbani) [reply components/NavigationBar/src/MDCNavigationBar.m:30]: The insets are used to calculate the height of the titleView. However, because we are always centering the titleLabel within the titleView, it doesn't matter if titleView takes up the whole height of the MDCNavigationBar or not.

The reason it needs to change is that if the height of the navbar is smaller than topInset+titleLabelHeight+bottomInset, then titleLabel is centered in titleView, but not the navigation bar.

File: components/NavigationBar/src/MDCNavigationBar.m [hunk 2]
```diff
@@ -372,12 +372,11 @@ - (void)layoutSubviews {
 
 - (CGSize)sizeThatFits:(CGSize)size {
   CGSize intrinsicContentSize = [self intrinsicContentSize];
-  return CGSizeMake(size.width, intrinsicContentSize.height);
+  return CGSizeMake(size.width, MIN(size.height, intrinsicContentSize.height));
```
Comment (AlimoRabbani) [inline components/NavigationBar/src/MDCNavigationBar.m]: I'm not sure if any clients are using sizeThatFits: on MDCNavigationBar or MDCButtonBar with CGSizeZero. In that case, this change can break them. Maybe I should guard this behind size.height > 0?

**Comment by AlimoRabbani** [comment]
@jverkoey Added some comments.

File: components/NavigationBar/src/MDCNavigationBar.m (hunk 1 above)
Comment (jverkoey) [reply components/NavigationBar/src/MDCNavigationBar.m:30]: Got it - thank you!

File: components/NavigationBar/src/MDCNavigationBar.m (hunk 2 above)
Comment (jverkoey) [reply components/NavigationBar/src/MDCNavigationBar.m]: In order to maintain the existing functionality it may be sensible to have a conditional clause for the empty size case where we use the old behavior.

**Review by jverkoey — CHANGES_REQUESTED** [review]

File: components/NavigationBar/src/MDCNavigationBar.m (hunk 2 above)
Comment (AlimoRabbani) [reply components/NavigationBar/src/MDCNavigationBar.m]: Done.

**Review by AlimoRabbani — COMMENTED** [review]
This should be ready now.

**Review by jverkoey — APPROVED** [review]
LGTM. I'll rate this as a moderate risk for client regressions, so we'll want to keep an eye on the next release accordingly.

**Comment by AlimoRabbani** [comment]
Thanks for the review. Is there anything else I should do before this can be merged? I figured kokoro builds are fixed since yesterday, but not sure how I can trigger it on this PR.

**Review by jverkoey — APPROVED** [review]

**Comment by randallli** [comment]
testing internally with cl/189537437

**Comment by ianegordon** [comment]
@randallli would you please merge this once internal testing is complete.

**Comment by randallli** [comment]
kokoro was failing but travis passed
