### PR TITLE
[Dialogs] Rewrite tests in ObjC to prevent the failing unit tests on iOS 13

### LINKED ISSUE #8256: [Dialogs] Unit tests are failing on iOS 13.
Add `ci_mode=autobot` in `.kokoro` above `bazel $COMMAND $TARGET --xcode_version $xcode_version --ios_minimum_os=9.0` in `run_bazel()` to reproduce.

Error occurs when testing using Bazel.
```
Test Case '-[components_Dialogs_unit_test_swift_sources.MDCDialogPresentationControllerTests testTraitCollectionDidChangeCalledWithCorrectParameters]' started.
Child process terminated with signal 11: Segmentation fault
```

---
#### Internal data
- Associated internal bug: [b/139181422](http://b/139181422)

### PR DESCRIPTION
**Pull request by fluxminds**
closes https://github.com/material-components/material-components-ios/issues/8256.

## Context
Error occurs when testing using Bazel.
```
Test Case '-[components_Dialogs_unit_test_swift_sources.MDCDialogPresentationControllerTests testTraitCollectionDidChangeCalledWithCorrectParameters]' started.
Child process terminated with signal 11: Segmentation fault
```

### CODE REVIEW

File: components/Dialogs/tests/unit/MDCDialogPresentationControllerTests.m [hunk 1]
```diff
@@ -0,0 +1,55 @@
...
+             presentingViewController:presentingViewController];
+  XCTestExpectation *expectation =
+      [[XCTestExpectation alloc] initWithDescription:@"traitCollectionDidChange"];
+
+  __block UITraitCollection *passedTraitCollection;
+  __block MDCDialogPresentationController *passedPresentationController;
+  presentationController.traitCollectionDidChangeBlock =
+      ^(MDCDialogPresentationController *_Nonnull presentationControllerInBlock,
+        UITraitCollection *_Nullable previousTraitCollection) {
+        [expectation fulfill];
```
Comment (romoore) [inline components/Dialogs/tests/unit/MDCDialogPresentationControllerTests.m]: Nit: Please fulfill the expectation last.

**Review by romoore — APPROVED** [review]

File: components/Dialogs/tests/unit/MDCDialogPresentationControllerTests.m (hunk 1 above)
Comment (fluxminds) [reply components/Dialogs/tests/unit/MDCDialogPresentationControllerTests.m]: Addressed in e34893f6eb18b64f32d9c78c70891ac0af67a295
