### PR TITLE
[Ink] Fix flaky test

### LINKED ISSUE #3173: [Ink] Flaky tests
```
Test Case '-[MDCInkLayerTests testChangeAnimationTimingInTimeScaledLayer]' started.
components/Ink/tests/unit/MDCInkLayerTests.m:179: error: -[MDCInkLayerTests testChangeAnimationTimingInTimeScaledLayer] : ((animation.beginTime) equal to ([inkLayer convertTime:startTime fromLayer:nil]) +/- (0.005)) failed: ("9909.81288774") is not equal to ("9909.80478034") +/- ("0.005")
Test Case '-[MDCInkLayerTests testChangeAnimationTimingInTimeScaledLayer]' failed (0.212 seconds).
```

### PR DESCRIPTION
**Pull request by yarneo**
Depending on the scheduler and the machine the time given for accuracy is too low (even though both times are set synchronously after each other). I have made it so the `convertTime` invocation is done prior to initiating the `animation.beginTime` and made the accuracy less strict.

Resolves #3173 

Pivotal: https://www.pivotaltracker.com/story/show/156520276

### CODE REVIEW

File: components/Ink/tests/unit/MDCInkLayerTests.m [hunk 1]
```diff
@@ -147,16 +147,13 @@ - (void)testEndAnimationTimingInTimeScaledLayer {
 
   // When
   NSTimeInterval startTime = CACurrentMediaTime();
+  startTime = [inkLayer convertTime:(startTime + 0.9) fromLayer:nil];
```
Comment (romoore) [inline components/Ink/tests/unit/MDCInkLayerTests.m]: I'm probably missing something here.  How does moving the time computation affect the outcome of the test? Unless the receiver's time scale has changed relative to the caller (which I don't believe it does in this case), I fail to see how it can make a difference.

Comment (yarneo) [reply components/Ink/tests/unit/MDCInkLayerTests.m]: There's a difference as the computation went chronologically in between the animation.beginTime and the startTime. However, this will make it even less optimal because it's better to get the computation after both times are received. Updated.

Comment (yarneo) [reply components/Ink/tests/unit/MDCInkLayerTests.m]: It looks like there is less branching if we reorder the beginTime and the startTime, it gives closer accuracy in that case; have switched between the two.

File: components/Ink/tests/unit/MDCInkLayerTests.m [hunk 2]
```diff
@@ -146,17 +146,15 @@ - (void)testEndAnimationTimingInTimeScaledLayer {
...
 
   // Then
   XCTAssertEqual(inkLayer.addedAnimations.count, 1U);
   CAAnimation *animation = inkLayer.addedAnimations.firstObject;
   if (animation) {
-    XCTAssertEqualWithAccuracy(animation.beginTime,
-                               [inkLayer convertTime:(startTime + 0.9) fromLayer:nil],
-                               0.005);
+    startTime = [inkLayer convertTime:(startTime + 0.9) fromLayer:nil];
+    XCTAssertEqualWithAccuracy(animation.beginTime, startTime, 0.010);
```
Comment (romoore) [inline components/Ink/tests/unit/MDCInkLayerTests.m:157]: Any reason not to go to 0.10? Given the speed (0.5) and the duration (0.9), I think being within ~10~ 100 ms should be sufficient to detect whether or not the scale is off by 450 ms.

**Review by romoore — APPROVED** [review]
Spoke offline. I now understand that the real cause of flakiness is the difference between when `-endAnimationAtPoint:` or `-changeAnimationAtPoint:` and the test case each call `CACurrentMediaTime()`.
