### PR TITLE
[Tabs] fix TabBarViewControllerExample to respect safe area

### LINKED ISSUE #3728: [Tabs] TabBarViewControllerExample does not respect safe area
### Overview
The child View Controllers in the TabBarViewController example do not respect the safe area and place their buttons outside the safe area.

screen shot 2018-05-04 at 12 07 32 pm
----
screen shot 2018-05-04 at 12 07 23 pm

### Reproduction steps
1. Open the Catalog in Landscape
1. Open Tab Bar &rarr; TabBarViewController
1. Open "Two" or "Three"

### Version number
55.0.1

### Operating system and device
iPhone X/iOS 11.3 (Simulator)

### PR DESCRIPTION
**Pull request by fluxminds**
closes #3728 

### Before

b1

### After:

a1

### CODE REVIEW

File: components/Tabs/examples/supplemental/TabBarViewControllerExampleSupplemental.m [hunk 1]
```diff
@@ -117,14 +156,40 @@ - (void)setupTabBarColors {
...
+  __weak TabBarViewControllerExample *weakSelf = self;
+  [child2 addMDCButtonWithFrame:CGRectMake(10, 120, 300, 40)
+                   buttonScheme:buttonScheme
+                          title:@"Push and Hide Tab"
+                    actionBlock:^{
+                      TabBarViewControllerExample *strongSelf = weakSelf;
+                      TBVCSampleViewController *vc =
+                      [TBVCSampleViewController sampleWithTitle:@"Push&Hide" color:UIColor.grayColor];
+                      vc.colorScheme = self.colorScheme;
+                      vc.typographyScheme = self.typographyScheme;
```
Comment (romoore) [inline components/Tabs/examples/supplemental/TabBarViewControllerExampleSupplemental.m]: Please use strongSelf here and above.

File: components/Tabs/examples/TabBarViewControllerExample.m [hunk 2]
```diff
@@ -42,54 +40,12 @@ - (void)viewDidLoad {
...
-  button = [[MDCButton alloc] initWithFrame:CGRectMake(10, 120, 300, 40)];
-  [MDCContainedButtonThemer applyScheme:buttonScheme toButton:button];
-  [button setTitle:@"Toggle Tab Bar" forState:UIControlStateNormal];
-  [button sizeToFit];
-  [child2.view addSubview:button];
-  [button addTarget:self
-                action:@selector(toggleTabBar)
-      forControlEvents:UIControlEventTouchUpInside];
-  
+  self.selectedViewController = [self.viewControllers firstObject];
```
Comment (romoore) [inline components/Tabs/examples/TabBarViewControllerExample.m]: Nit: Please use dot notation for property access.

```objc
self.selectedViewController = self.viewControllers.firstObject;
```

File: components/Tabs/examples/supplemental/TabBarViewControllerExampleSupplemental.h [hunk 3]
```diff
@@ -38,7 +41,15 @@
...
+
 @property(nonatomic, nullable) MDCSemanticColorScheme *colorScheme;
 @property(nonatomic, nullable) MDCTypographyScheme *typographyScheme;
+
++ (nonnull instancetype)sampleWithTitle:(nonnull NSString *)title color:(nonnull UIColor *)color;
+
+- (void)addMDCButtonWithFrame:(CGRect)frame
+                 buttonScheme:(id<MDCButtonScheming>)buttonScheme
+                        title:(NSString *)title
+                  actionBlock:(MDCButtonActionBlock)actionBlock;
```
Comment (romoore) [inline components/Tabs/examples/supplemental/TabBarViewControllerExampleSupplemental.h]: Please add nullability specifiers for these arguments.

File: components/Tabs/examples/supplemental/TabBarViewControllerExampleSupplemental.m [hunk 4]
```diff
@@ -46,8 +47,13 @@ - (void)drawRect:(CGRect)rect {
 @end
 
 @interface TBVCSampleViewController ()
+
 @property(nonatomic) MDCAppBarViewController *appBarViewController;
 @property(nonatomic) UILabel *titleLabel;
+@property(nonatomic) CGRect buttonFrame;
```
Comment (romoore) [inline components/Tabs/examples/supplemental/TabBarViewControllerExampleSupplemental.m]: Please document that this is the "target" frame desired by the calling code. Reading the property, I thought it was going to be just a copy of `self.button.frame`.

File: components/Tabs/examples/supplemental/TabBarViewControllerExampleSupplemental.m [hunk 5]
```diff
@@ -46,8 +47,13 @@ - (void)drawRect:(CGRect)rect {
...
+@property(nonatomic) UIButton *button;
```
Comment (romoore) [inline components/Tabs/examples/supplemental/TabBarViewControllerExampleSupplemental.m]: Please make this `MDCButton *` since we cannot apply an `<MDCButtonScheming>` to a `UIButton`.

File: components/Tabs/examples/supplemental/TabBarViewControllerExampleSupplemental.m [hunk 6]
```diff
@@ -78,6 +84,17 @@ - (void)viewWillAppear:(BOOL)animated {
 - (void)viewDidLayoutSubviews {
   [super viewDidLayoutSubviews];
   _titleLabel.center = self.view.center;
+  UIEdgeInsets edgeInsets = UIEdgeInsetsZero;
```
Comment (romoore) [inline components/Tabs/examples/supplemental/TabBarViewControllerExampleSupplemental.m]: Nit/nameing: `safeAreaInsets`

File: components/Tabs/examples/supplemental/TabBarViewControllerExampleSupplemental.m [hunk 7]
```diff
@@ -78,6 +84,17 @@ - (void)viewWillAppear:(BOOL)animated {
...
+  if (@available(iOS 11.0, *)) {
+    edgeInsets = self.view.safeAreaInsets;
+  }
+  CGRect buttonFrame = self.buttonFrame;
+  self.button.frame = CGRectMake(buttonFrame.origin.x + edgeInsets.left,
```
Comment (romoore) [inline components/Tabs/examples/supplemental/TabBarViewControllerExampleSupplemental.m]: Please consider using `CGRectOffset`, since I believe that's what you're going for here.

File: components/Tabs/examples/supplemental/TabBarViewControllerExampleSupplemental.m [hunk 8]
```diff
@@ -106,6 +123,28 @@ + (nonnull instancetype)sampleWithTitle:(nonnull NSString *)title
...
+- (void)addMDCButtonWithFrame:(CGRect)frame
+                 buttonScheme:(id<MDCButtonScheming>)buttonScheme
+                        title:(NSString *)title
+                  actionBlock:(MDCButtonActionBlock)actionBlock {
+  MDCButton *button = [[MDCButton alloc] initWithFrame:CGRectZero];
+  [button setTitle:title forState:UIControlStateNormal];
+  [MDCContainedButtonThemer applyScheme:buttonScheme toButton:button];
+  [self.view addSubview:button];
+  self.button = button;
+  self.buttonFrame = frame;
```
Comment (romoore) [inline components/Tabs/examples/supplemental/TabBarViewControllerExampleSupplemental.m]: Please consider calling CGRectStandardize before assigning the property.

File: components/Tabs/examples/supplemental/TabBarViewControllerExampleSupplemental.h [hunk 9]
```diff
@@ -38,7 +41,15 @@
...
 
 @interface TBVCSampleViewController : UIViewController
-+ (nonnull instancetype)sampleWithTitle:(nonnull NSString *)title color:(nonnull UIColor *)color;
+
 @property(nonatomic, nullable) MDCSemanticColorScheme *colorScheme;
 @property(nonatomic, nullable) MDCTypographyScheme *typographyScheme;
+
++ (nonnull instancetype)sampleWithTitle:(nonnull NSString *)title color:(nonnull UIColor *)color;
+
+- (void)addMDCButtonWithFrame:(CGRect)frame
```
Comment (romoore) [inline components/Tabs/examples/supplemental/TabBarViewControllerExampleSupplemental.h]: Naming/nit: Please make this `setMDCButtonWithFrame:...` since there can only be one. :highlander:

File: components/Tabs/examples/supplemental/TabBarViewControllerExampleSupplemental.m [hunk 10]
```diff
@@ -117,14 +156,40 @@ - (void)setupTabBarColors {
...
   UIImage *starImage =
       [UIImage imageNamed:@"TabBarDemo_ic_star" inBundle:bundle compatibleWithTraitCollection:nil];
   TBVCSampleViewController *child3 =
       [TBVCSampleViewController sampleWithTitle:@"Three" color:UIColor.blueColor icon:starImage];
+  [child3 addMDCButtonWithFrame:CGRectMake(10, 120, 300, 40)
+                   buttonScheme:buttonScheme
+                          title:@"Toggle Tab Bar"
+                    actionBlock:^{
+                      TabBarViewControllerExample *strongSelf = weakSelf;
+                      [strongSelf setTabBarHidden:!strongSelf.tabBarHidden animated:YES];
```
Comment (romoore) [inline components/Tabs/examples/supplemental/TabBarViewControllerExampleSupplemental.m:187]: Since this is a property, please use the dot syntax.

```objc
strongSelf.tabBarHidden = !self.isTabBarHidden;
```

**Review by romoore — APPROVED** [review]

File: components/Tabs/examples/supplemental/TabBarViewControllerExampleSupplemental.m (hunk 10 above)
Comment (fluxminds) [reply components/Tabs/examples/supplemental/TabBarViewControllerExampleSupplemental.m:187]: I kept the original behavior since it wanted to animate out the tab bar. Would it be okay if I change the behavior?

File: components/Tabs/examples/supplemental/TabBarViewControllerExampleSupplemental.h (hunk 9 above)
Comment (fluxminds) [reply components/Tabs/examples/supplemental/TabBarViewControllerExampleSupplemental.h]: Addressed in a46864d6635c5903a535e6436aed7fb783f084b3.

File: components/Tabs/examples/supplemental/TabBarViewControllerExampleSupplemental.m (hunk 8 above)
Comment (fluxminds) [reply components/Tabs/examples/supplemental/TabBarViewControllerExampleSupplemental.m]: Addressed in a46864d6635c5903a535e6436aed7fb783f084b3.

File: components/Tabs/examples/supplemental/TabBarViewControllerExampleSupplemental.m (hunk 7 above)
Comment (fluxminds) [reply components/Tabs/examples/supplemental/TabBarViewControllerExampleSupplemental.m]: Addressed in a46864d6635c5903a535e6436aed7fb783f084b3.

File: components/Tabs/examples/supplemental/TabBarViewControllerExampleSupplemental.m (hunk 6 above)
Comment (fluxminds) [reply components/Tabs/examples/supplemental/TabBarViewControllerExampleSupplemental.m]: Addressed in a46864d6635c5903a535e6436aed7fb783f084b3.

File: components/Tabs/examples/supplemental/TabBarViewControllerExampleSupplemental.m (hunk 5 above)
Comment (fluxminds) [reply components/Tabs/examples/supplemental/TabBarViewControllerExampleSupplemental.m]: Addressed in a46864d6635c5903a535e6436aed7fb783f084b3.

File: components/Tabs/examples/supplemental/TabBarViewControllerExampleSupplemental.m (hunk 4 above)
Comment (fluxminds) [reply components/Tabs/examples/supplemental/TabBarViewControllerExampleSupplemental.m]: Good point! Addressed in a46864d6635c5903a535e6436aed7fb783f084b3.

File: components/Tabs/examples/supplemental/TabBarViewControllerExampleSupplemental.h (hunk 3 above)
Comment (fluxminds) [reply components/Tabs/examples/supplemental/TabBarViewControllerExampleSupplemental.h]: Addressed in a46864d6635c5903a535e6436aed7fb783f084b3.

File: components/Tabs/examples/TabBarViewControllerExample.m (hunk 2 above)
Comment (fluxminds) [reply components/Tabs/examples/TabBarViewControllerExample.m]: Good catch. Addressed in a46864d6635c5903a535e6436aed7fb783f084b3.

File: components/Tabs/examples/supplemental/TabBarViewControllerExampleSupplemental.m (hunk 1 above)
Comment (fluxminds) [reply components/Tabs/examples/supplemental/TabBarViewControllerExampleSupplemental.m]: Good catch! Addressed in a46864d6635c5903a535e6436aed7fb783f084b3.

**Review by fluxminds — COMMENTED** [review]
@romoore thanks for the comments. I addressed them in a46864d6635c5903a535e6436aed7fb783f084b3.
