### PR TITLE
[FlexibleHeader] Fix bug where shadowPath did not animate when using MDCShadowLayer.

### LINKED ISSUE #8644: [FlexibleHeader] Internal issue: b/143282407
This was filed as an internal issue. If you are a Googler, please visit [b/143282407](http://b/143282407) for more details.

---
#### Internal data
- Associated internal bug: [b/143282407](http://b/143282407)

### PR DESCRIPTION
**Pull request by jverkoey**
This change relies on https://github.com/material-components/material-components-ios/pull/8666.

Prior to this change, `setTrackingScrollView:`'s tab-change collapse animation would not animate the shadow if using an MDCShadowLayer.

After this change, the animation will animate the shadow.

The added test fails without the src/ changes and passes with them.

Closes https://github.com/material-components/material-components-ios/issues/8644

### CODE REVIEW

File: components/FlexibleHeader/src/MDCFlexibleHeaderView.m [hunk 1]
```diff
@@ -1554,8 +1560,29 @@ - (void)setTrackingScrollView:(UIScrollView *)trackingScrollView {
...
+  CFTimeInterval duration = kTrackingScrollViewDidChangeAnimationDuration;
+  CAMediaTimingFunction *timingFunction =
+      [CAMediaTimingFunction functionWithName:kCAMediaTimingFunctionEaseInEaseOut];
+
   void (^animate)(void) = ^{
+    self->_isAnimatingTrackingScrollViewChange = YES;
+
+    [CATransaction begin];
+#if TARGET_IPHONE_SIMULATOR
+    [CATransaction setAnimationDuration:duration * [self fhv_dragCoefficient]];
```
Comment (yarneo) [inline components/FlexibleHeader/src/MDCFlexibleHeaderView.m:1572]: what's the reason for the simulator to have a different animation duration?

**Review by yarneo — APPROVED** [review]
Awesome!! Does this close the main bug? If so, please add it to the PR.

**Comment by jverkoey** [comment]
> Awesome!! Does this close the main bug? If so, please add it to the PR.

Fixed.

File: components/FlexibleHeader/src/MDCFlexibleHeaderView.m (hunk 1 above)
Comment (jverkoey) [reply components/FlexibleHeader/src/MDCFlexibleHeaderView.m:1572]: This is so that the "Slowed animations" Simulator debug flag will impact these animation durations as well.

**Comment by jverkoey** [comment]
Pulled the .bzl change out to https://github.com/material-components/material-components-ios/pull/8680

File: components/FlexibleHeader/tests/snapshot/FlexibleHeaderTrackingScrollViewDidChangeTests.swift [hunk 2]
```diff
@@ -0,0 +1,78 @@
...
+    // When
+    // And then collapsed.
+    fhvc.headerView.trackingScrollView = scrollView2
+
+    // Then
+    XCTAssertNotNil(fhvc.headerView.layer.animation(forKey: "bounds.size"))
+    XCTAssertNotNil(fhvc.headerView.layer.animation(forKey: "bounds.origin"))
+    XCTAssertNotNil(fhvc.headerView.layer.animation(forKey: "position"))
+
+    guard let animationDuration =
```
Comment (yarneo) [inline components/FlexibleHeader/tests/snapshot/FlexibleHeaderTrackingScrollViewDidChangeTests.swift:60]: For here and below, guards must have a `return` or `break` statement rather than falling through. Will be better to use an `if let` here and below

**Comment by yarneo** [comment]
Note: This PR was reverted due to internal client breakages

**Comment by jverkoey** [comment]
I have patched this change internally and am running isolated tests to identify the best alternative path forward.
