### PR TITLE
[AppBar] Fix swipe to go back gesture for MDCAppBarNavigationController.

### LINKED ISSUE #9447: [AppBar] Internal issue: b/147826095
This was filed as an internal issue. If you are a Googler, please visit [b/147826095](http://b/147826095) for more details.

---
#### Internal data
- Associated internal bug: [b/147826095](http://b/147826095)

### PR DESCRIPTION
**Pull request by jverkoey**
Originally authored by anthonylai in cl/290091107.

https://developer.apple.com/design/human-interface-guidelines/ios/user-interaction/gestures/

"But users can also navigate back by swiping from the side of the screen."

Closes https://github.com/material-components/material-components-ios/issues/9447

Tested manually on:

- iPhone 7, 11.2
- iPhone X, 12.2
- iPhone 8 Plus, 13.2.2

## Testing Steps
1. Set MDCAppBarNavigationController as the root view controller
2. Push a view controller.
3. Swipe from the trailing edge toward the leading edge.

Tested by running the MDCCatalog and verifying that I can swipe to dismiss pushed view controllers on the root navigation controller.

### CODE REVIEW

File: components/AppBar/src/MDCAppBarNavigationController.m [hunk 1]
```diff
@@ -29,6 +29,9 @@ @interface MDCAppBarNavigationControllerInfo : NSObject
 
 @end
 
+@interface MDCAppBarNavigationController () <UIGestureRecognizerDelegate>
```
Comment (romoore) [inline components/AppBar/src/MDCAppBarNavigationController.m:34]: Please document this category. I assume this is necessary to assign itself as the `interactivePopGestureRecognizer`?

**Review by romoore — CHANGES_REQUESTED** [review]
Please add tests for this PR.   Since `viewDidLoad` is called from `-init` I'm a little wary of the execution path of the code.

-  [x] If automated tests are possible, that's great. If not, please list manual testing steps in the PR summary.  
-  [x] Please add a comment mentioning which iOS versions you tested on. In the past we've had challenges with the AppBar/Header component and initialization flows for some clients.

File: components/AppBar/src/MDCAppBarNavigationController.m (hunk 1 above)
Comment (jverkoey) [reply components/AppBar/src/MDCAppBarNavigationController.m:34]: We do not require documentation of internal categories.

**Comment by jverkoey** [comment]
Added tests + manual testing steps.

File: components/AppBar/src/MDCAppBarNavigationController.m (hunk 1 above)
Comment (romoore) [reply components/AppBar/src/MDCAppBarNavigationController.m:34]: The Google Style Guide says [anything "non-trivial" should be documented](http://google.github.io/styleguide/objcguide.html#declaration-comments).   Do you mean that you feel this is a trivial interface declaration?  I personally questioned why it wasn't in the public declaration of the interface as I was reading.  I still don't know why it shouldn't just be declared public.  I think documenting why it shouldn't be exposed is one good use of the documentation for this category.


> Every non-trivial interface, public and private, should have an accompanying comment describing its purpose *and how it fits into the larger picture*. (emphasis added)

**Review by romoore — APPROVED** [review]
Thanks, I updated the summary to include testing steps. Please take a look and update if they're inaccurate.

LGTM pending docs discussion.

File: components/AppBar/src/MDCAppBarNavigationController.m (hunk 1 above)
Comment (jverkoey) [reply components/AppBar/src/MDCAppBarNavigationController.m:34]: I do feel it is reasonably common practice to keep internal protocol conformances private to the class unless otherwise needed to be exposed publicly. Any comment I would write here would be to the effect of "This is intentionally a private protocol conformance in order to reduce public commitments to specific API contracts". Do you feel that that is necessary here?

Comment (romoore) [reply components/AppBar/src/MDCAppBarNavigationController.m:34]: I would appreciate if you added a comment like that, yes. For me it's explaining that although it requires extra complexity and mental energy to understand the class's conformance, it's worth it to balance keeping this detail private.  If there's a specific risk of clients depending on this protocol, it's worth calling-out as well.

Feel free to make it a non-doc comment, since I don't believe the Style Guide requires and in this case it's largely an explanation to maintainers rather than clients.

Comment (jverkoey) [reply components/AppBar/src/MDCAppBarNavigationController.m:34]: sgtm; thanks Rob!
