### PR TITLE
[Chips] Fix `imagePadding` behavior.

### LINKED ISSUE #9250: [Chips] `imagePadding` mispositions layout for title label
The `imagePadding` API affects the position of the `titleLabel` frame incorrectly.

## Steps to reproduce
1. Assign an `imagePadding` value of `UIEdgeInsetsMake(10, 20, 30, 40)` and all other padding to `.zero`
2. Render the Chip.

Chip with positive image padding values showing incorrect label position.

### Expected Result
1. The chip is inset based on its padding values and the label is unaffected relative to the trailing edge of the Chip.

### Actual Result
1. The label is mispositioned as a result of the image padding.

---
#### Internal data
- Associated internal bug: [b/147294309](http://b/147294309)

### PR DESCRIPTION
**Pull request by romoore**
Corrects the behavior of `imagePadding` in two significant ways:

*   Previously, the union of the frames of `selectedImageView` and `imageView`
    were used to determine the position of the `titleLabel`. However, since
    `selectedImageView` is documented as not having an effect on
    `MDCChipView` unless it is set and the Chip is selected, it should not have
    any effect on the frame calculations when unselected or unset.
*   `imagePadding` is now only applied if either `selectedImageView` or
    `imageView` in the Chip. Previously, `imagePadding` would have been
    applied even without an image present.

Closes #9250

### CODE REVIEW

File: components/Chips/tests/snapshot/MDCChipViewLayoutSnapshotTests.m [hunk 1]
```diff
@@ -259,6 +269,33 @@ - (void)testSelectedChipImagePaddingAllPositiveValuesForLargeSelectedImageLTR {
...
+
+  // When
+  self.chipView.imagePadding = UIEdgeInsetsMake(10, 20, 30, 40);
+
+  // Then
+  [self generateSnapshotAndVerifyForView:self.chipView];
+}
+
+- (void)testSelectedChipImagePaddingAllPositiveValuesForSmallSelectedImageLTR {
+  // Given
```
Comment (galiak11) [inline components/Chips/tests/snapshot/MDCChipViewLayoutSnapshotTests.m:286]: I'm noticing a vertical misalignment between the image on the left and the title+box on the right (in this and otehr snapshots). Is that a bug?

File: components/Chips/src/MDCChipView.m [hunk 2]
```diff
@@ -744,11 +744,22 @@ - (CGSize)sizeForAccessoryViewWithMaxSize:(CGSize)maxSize {
 }
 
 - (CGRect)titleLabelFrame {
-  CGRect imageFrame = CGRectUnion(_imageView.frame, _selectedImageView.frame);
+  // Default to the unselected image, but account for the selected image if it's shown.
+  CGRect imageFrame = _imageView.frame;
+  if (self.showSelectedImageView) {
```
Comment (andrewoverton) [inline components/Chips/src/MDCChipView.m:749]: Do we need to do anything if `showSelectedImageView` is false?

Comment (romoore) [reply components/Chips/src/MDCChipView.m:749]: In that case, the default behavior would be to use the frame of `_imageView` (above).

**Review by galiak11 — COMMENTED** [review]
In snapshot_test_goldens/goldens_64/MDCChipViewLayoutSnapshotTests/testUnselectedChipImagePaddingShiftToTrailingEdgeLTR_11_2@2x.png (as well as the RTL one) - the image overlaps the label. Is that intentional?

**Review by galiak11 — APPROVED** [review]

File: components/Chips/tests/snapshot/MDCChipViewLayoutSnapshotTests.m (hunk 1 above)
Comment (romoore) [reply components/Chips/tests/snapshot/MDCChipViewLayoutSnapshotTests.m:286]: Do you mean the `imageView`'s vertical alignment compared to that of the `titleLabel` and `accessoryView`?  This test is adjusting the `imagePadding` value, would should manipulate the space around the `imageView`. Since `top` and `left` are less than `bottom` and `right`, the imageView should be pushed up and toward the leading edge of the Chip.

**Comment by romoore** [comment]
In `testUnselectedChipImagePaddingShiftToTrailingEdgeLTR_11_2` the Image is shifted toward the trailing edge of the Chip.  So yep, it would be expected to overlap the label.   Thanks for asking. :)
