### PR TITLE
[FeatureHighlight] Accessibility title and body mutator added to fix UIAppearance issue

### LINKED ISSUE #3023: [FeatureHighlight] Setting `titleColor` or `bodyColor` via UIAppearance does not work
### Overview
Setting the UIAppearance proxy values for `MDCFeatureHighlightView.bodyColor` and `MDCFeatureHighlightView.titleColor` does nothing when using `MDCFeatureHighlightViewController` because the VC will inspect their values in `viewWillAppear` (before UIAppearance) and will reassign new values instead.  The logic for this behavior&mdash;checking the `backgroundColor` and computing an accessible color&mdash;will also fail when UIAppearance is used for the `backgroundColor` property of the FHV.

It would make more sense (and match other components like Buttons) to extract the accessible text color behavior into a **Mutator** object and allow clients to decide if they're going to use it or not.

### Reproduction steps
1. Set the `titleColor` and `bodyColor` values on `MDCFeatureHighlightView` via UIAppearance
1. Use the `MDCFeatureHighlightViewController` to present a FHV

Expect that the `titleColor` and `bodyColor` values match the UIAppearance proxied values.

### Version number
46.0.0

### Operating system and device
iPhone 5/iOS 8.1 (Simulator)

### PR DESCRIPTION
**Pull request by mohammadcazig**
The issue was the fact that by auto setting accessible colors for body and title, we were overwriting UIAppearance colors.
By refactoring that code and putting it in a mutator, we made option available for the user to decide on changing the colors or not.
Close #3023 .

### CODE REVIEW

File: components/FeatureHighlight/src/FeatureHighlightAccessibilityMutator/MDCFeatureHighlightAccessibilityMutator.h [hunk 1]
```diff
@@ -0,0 +1,28 @@
...
+ */
+
+@class MDCFeatureHighlightViewController;
+@class MDCFeatureHighlightView;
+
+#import <UIKit/UIKit.h>
+
+@interface MDCFeatureHighlightAccessibilityMutator : NSObject
+
++ (void)changeTitleAndBodyColorForFeatureHighlightViewControllerIfApplicable:
```
Comment (romoore) [inline components/FeatureHighlight/src/FeatureHighlightAccessibilityMutator/MDCFeatureHighlightAccessibilityMutator.h]: Please provide documentation here.  Specifically, when is it "applicable" to change the body/title color?

Comment (romoore) [inline components/FeatureHighlight/src/FeatureHighlightAccessibilityMutator/MDCFeatureHighlightAccessibilityMutator.h]: Please consider splitting these into two methods.  It may be that brand color is important for title, but not so much for body or vice-versa.

File: components/FeatureHighlight/src/FeatureHighlightAccessibilityMutator/MDCFeatureHighlightAccessibilityMutator.h [hunk 2]
```diff
@@ -0,0 +1,28 @@
...
+
+ Unless required by applicable law or agreed to in writing, software
+ distributed under the License is distributed on an "AS IS" BASIS,
+ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ See the License for the specific language governing permissions and
+ limitations under the License.
+ */
+
+@class MDCFeatureHighlightViewController;
+@class MDCFeatureHighlightView;
```
Comment (romoore) [inline components/FeatureHighlight/src/FeatureHighlightAccessibilityMutator/MDCFeatureHighlightAccessibilityMutator.h]: I see `MDCFeatureHighlightView` forward-declared but not used. Did you intend to have an API for the view as well?

File: components/FeatureHighlight/src/FeatureHighlightAccessibilityMutator/MDCFeatureHighlightAccessibilityMutator.m [hunk 3]
```diff
@@ -0,0 +1,66 @@
...
+
+ Unless required by applicable law or agreed to in writing, software
+ distributed under the License is distributed on an "AS IS" BASIS,
+ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ See the License for the specific language governing permissions and
+ limitations under the License.
+ */
+
+#import "MDCFeatureHighlightAccessibilityMutator.h"
+#import "MaterialFeatureHighlight.h"
```
Comment (romoore) [inline components/FeatureHighlight/src/FeatureHighlightAccessibilityMutator/MDCFeatureHighlightAccessibilityMutator.m]: Nit: Please sort imports alphabetically.

File: components/FeatureHighlight/src/FeatureHighlightAccessibilityMutator/MDCFeatureHighlightAccessibilityMutator.m [hunk 4]
```diff
@@ -0,0 +1,66 @@
...
+#import "MaterialTypography.h"
+
+@implementation MDCFeatureHighlightAccessibilityMutator
+
++ (void)changeTitleAndBodyColorForFeatureHighlightViewControllerIfApplicable:
+    (MDCFeatureHighlightViewController *)featureHighlightViewController {
+  MDCFeatureHighlightView *featureHighlightView =
+      (MDCFeatureHighlightView *)featureHighlightViewController.view;
+  NSAssert([featureHighlightView isKindOfClass:[MDCFeatureHighlightView class]],
+           @"FeatureHighlightViewController should have FeatureHighlightView");
```
Comment (romoore) [inline components/FeatureHighlight/src/FeatureHighlightAccessibilityMutator/MDCFeatureHighlightAccessibilityMutator.m]: I think it might be good to return early if this assert fails. That way we don't accidentally crash in production builds.

File: components/FeatureHighlight/src/FeatureHighlightAccessibilityMutator/MDCFeatureHighlightAccessibilityMutator.m [hunk 5]
```diff
@@ -0,0 +1,66 @@
...
+  MDFTextAccessibilityOptions options = MDFTextAccessibilityOptionsPreferLighter;
```
Comment (romoore) [inline components/FeatureHighlight/src/FeatureHighlightAccessibilityMutator/MDCFeatureHighlightAccessibilityMutator.m]: Can this be a parameter to the caller? If the app is using a dark theme, then a darker text color may be preferred.

File: components/FeatureHighlight/src/FeatureHighlightAccessibilityMutator/MDCFeatureHighlightAccessibilityMutator.m [hunk 6]
```diff
@@ -0,0 +1,66 @@
...
+  }
+
+  UIColor *outerColor =
+      [featureHighlightViewController.outerHighlightColor colorWithAlphaComponent:1.0f];
+  if (![MDFTextAccessibility textColor:featureHighlightViewController.bodyColor
+               passesOnBackgroundColor:outerColor
+                               options:options]) {
+    featureHighlightViewController.bodyColor =
+        [MDFTextAccessibility textColorOnBackgroundColor:outerColor
+                                         targetTextAlpha:[MDCTypography captionFontOpacity]
```
Comment (romoore) [inline components/FeatureHighlight/src/FeatureHighlightAccessibilityMutator/MDCFeatureHighlightAccessibilityMutator.m]: Please consider getting the alpha from the view or view controller in some way.

File: components/FeatureHighlight/src/FeatureHighlightAccessibilityMutator/MDCFeatureHighlightAccessibilityMutator.m [hunk 7]
```diff
@@ -0,0 +1,66 @@
...
+  // Since MDFTextAccessibility can return either a dark value or light value color we want to
+  // guarantee that the title and body have the same value.
+  if (![MDFTextAccessibility textColor:featureHighlightViewController.titleColor
+               passesOnBackgroundColor:outerColor
+                               options:options]) {
+    CGFloat titleAlpha =
+        [MDFTextAccessibility minAlphaOfTextColor:featureHighlightViewController.bodyColor
+                                onBackgroundColor:outerColor
+                                          options:options];
+    titleAlpha = MAX([MDCTypography titleFontOpacity], titleAlpha);
```
Comment (romoore) [inline components/FeatureHighlight/src/FeatureHighlightAccessibilityMutator/MDCFeatureHighlightAccessibilityMutator.m]: Same here - please consider getting the titleFontOpacity from the view or view controller.

File: components/FeatureHighlight/src/FeatureHighlightAccessibilityMutator/MDCFeatureHighlightAccessibilityMutator.m [hunk 8]
```diff
@@ -0,0 +1,66 @@
...
+                                         targetTextAlpha:[MDCTypography captionFontOpacity]
+                                                 options:options];
+  }
+
+  options = MDFTextAccessibilityOptionsPreferLighter;
+  if ([MDFTextAccessibility isLargeForContrastRatios:featureHighlightView.titleFont]) {
+    options |= MDFTextAccessibilityOptionsLargeFont;
+  }
+  // Since MDFTextAccessibility can return either a dark value or light value color we want to
+  // guarantee that the title and body have the same value.
```
Comment (romoore) [inline components/FeatureHighlight/src/FeatureHighlightAccessibilityMutator/MDCFeatureHighlightAccessibilityMutator.m]: Why do we want to guarantee that both title and body have the same color value? I think it makes sense to permit them to be different if they started different.

File: components/FeatureHighlight/tests/unit/FeatureHighlightTitleBodyAccessibilityMutatorTests.m [hunk 9]
```diff
@@ -0,0 +1,70 @@
+//
+//  FeatureHighlightTitleBodyAccessibilityMutatorTests.m
```
Comment (romoore) [inline components/FeatureHighlight/tests/unit/FeatureHighlightTitleBodyAccessibilityMutatorTests.m]: License stanza

File: components/FeatureHighlight/examples/FeatureHighlightColorExample.m [hunk 10]
```diff
@@ -15,6 +15,7 @@
  */
 
 #import "MaterialFeatureHighlight.h"
+#import "MDCFeatureHighlightAccessibilityMutator.h"
```
Comment (romoore) [inline components/FeatureHighlight/examples/FeatureHighlightColorExample.m:18]: Naming/nit: Prefer `MDCFeatureHighlightTextAccessibilityMutator.h` since you aren't mutating the outerColor or innerColor.

File: components/FeatureHighlight/tests/unit/FeatureHighlightTitleBodyAccessibilityMutatorTests.m [hunk 11]
```diff
@@ -0,0 +1,70 @@
...
+
+@end
+
+@implementation FeatureHighlightTitleBodyAccessibilityMutatorTests
+
+- (void)testMutateChangesTextColor {
+  for (UIColor *color in testColors()) {
+    // Given
+    MDCFeatureHighlightViewController *highlightVC =
+        [[MDCFeatureHighlightViewController alloc] initWithHighlightedView:[UIView new]
```
Comment (romoore) [inline components/FeatureHighlight/tests/unit/FeatureHighlightTitleBodyAccessibilityMutatorTests.m]: Nit: Please use `alloc] init]` instead of `new]`

File: components/FeatureHighlight/tests/unit/FeatureHighlightTitleBodyAccessibilityMutatorTests.m [hunk 12]
```diff
@@ -0,0 +1,70 @@
...
+                                                                completion:nil];
+    MDCFeatureHighlightView *highlightView = (MDCFeatureHighlightView *)highlightVC.view;
+
+    // Making the background color the same as the title/body color.
```
Comment (romoore) [inline components/FeatureHighlight/tests/unit/FeatureHighlightTitleBodyAccessibilityMutatorTests.m]: Please add a test where the title/body colors differ.

File: components/FeatureHighlight/tests/unit/FeatureHighlightTitleBodyAccessibilityMutatorTests.m [hunk 13]
```diff
@@ -0,0 +1,70 @@
...
+    highlightView.outerHighlightColor = color;
+    highlightView.titleColor = color;
+    highlightView.bodyColor = color;
+
+    // When
+    [MDCFeatureHighlightAccessibilityMutator
+        changeTitleAndBodyColorForFeatureHighlightViewControllerIfApplicable:highlightVC];
+
+    // Then
+    XCTAssertNotEqualObjects(highlightView.titleColor, color, @"Not same color");
```
Comment (romoore) [inline components/FeatureHighlight/tests/unit/FeatureHighlightTitleBodyAccessibilityMutatorTests.m]: Please assert the correct colors here.    You can use code similar to `UIColor+ForcedFloatComparison.swift` to extract the expected values for the test.

File: components/FeatureHighlight/tests/unit/FeatureHighlightTitleBodyAccessibilityMutatorTests.m [hunk 14]
```diff
@@ -0,0 +1,70 @@
...
+  for (UIColor *color in colors) {
+ // Given
+  MDCFeatureHighlightViewController *highlightVC =
+      [[MDCFeatureHighlightViewController alloc] initWithHighlightedView:[UIView new]
+                                                              completion:nil];
+  MDCFeatureHighlightView *highlightView = (MDCFeatureHighlightView *)highlightVC.view;
+
+  // Making the background color accessible with title/body color.
+  highlightView.outerHighlightColor = colors[color];
+  highlightView.titleColor = color;
```
Comment (romoore) [inline components/FeatureHighlight/tests/unit/FeatureHighlightTitleBodyAccessibilityMutatorTests.m]: Please add tests for:
* Body is accessible, title is not
* Title is accessible, body is not

File: components/FeatureHighlight/tests/unit/FeatureHighlightTitleBodyAccessibilityMutatorTests.m [hunk 15]
```diff
@@ -0,0 +1,70 @@
...
+  highlightView.bodyColor = color;
+
+  // When
+  [MDCFeatureHighlightAccessibilityMutator
+      changeTitleAndBodyColorForFeatureHighlightViewControllerIfApplicable:highlightVC];
+
+  // Then
+  XCTAssertEqualObjects(highlightView.titleColor, color, @"Same color");
```
Comment (romoore) [inline components/FeatureHighlight/tests/unit/FeatureHighlightTitleBodyAccessibilityMutatorTests.m]: Nit: Please drop these comments (and in the test above) since the default message is sufficient. It will already state something like, "(UIColor(1, 2, 3, 4)) is not equal to (UIColor(4, 3, 3, 2))."

**Review by romoore — DISMISSED** [review]

File: components/FeatureHighlight/src/FeatureHighlightAccessibilityMutator/MDCFeatureHighlightAccessibilityMutator.h (hunk 1 above)
Comment (ianegordon) [reply components/FeatureHighlight/src/FeatureHighlightAccessibilityMutator/MDCFeatureHighlightAccessibilityMutator.h]: To match our existing mutators, this should be

mutate:

**Review by ianegordon — DISMISSED** [review]

File: components/FeatureHighlight/examples/FeatureHighlightColorExample.m (hunk 10 above)
Comment (mohammadcazig) [reply components/FeatureHighlight/examples/FeatureHighlightColorExample.m:18]: I think it's better to leave the class name as is, we could add more functionality to it if needed.

File: components/FeatureHighlight/src/FeatureHighlightAccessibilityMutator/MDCFeatureHighlightAccessibilityMutator.h (hunk 2 above)
Comment (mohammadcazig) [reply components/FeatureHighlight/src/FeatureHighlightAccessibilityMutator/MDCFeatureHighlightAccessibilityMutator.h]: removed.

File: components/FeatureHighlight/src/FeatureHighlightAccessibilityMutator/MDCFeatureHighlightAccessibilityMutator.h (hunk 1 above)
Comment (mohammadcazig) [reply components/FeatureHighlight/src/FeatureHighlightAccessibilityMutator/MDCFeatureHighlightAccessibilityMutator.h]: done

Comment (mohammadcazig) [reply components/FeatureHighlight/src/FeatureHighlightAccessibilityMutator/MDCFeatureHighlightAccessibilityMutator.h]: done.

File: components/FeatureHighlight/src/FeatureHighlightAccessibilityMutator/MDCFeatureHighlightAccessibilityMutator.m (hunk 3 above)
Comment (mohammadcazig) [reply components/FeatureHighlight/src/FeatureHighlightAccessibilityMutator/MDCFeatureHighlightAccessibilityMutator.m]: I thought the guide line is to put interface of the class on top?

File: components/FeatureHighlight/src/FeatureHighlightAccessibilityMutator/MDCFeatureHighlightAccessibilityMutator.m (hunk 4 above)
Comment (mohammadcazig) [reply components/FeatureHighlight/src/FeatureHighlightAccessibilityMutator/MDCFeatureHighlightAccessibilityMutator.m]: done.

File: components/FeatureHighlight/src/FeatureHighlightAccessibilityMutator/MDCFeatureHighlightAccessibilityMutator.m (hunk 8 above)
Comment (mohammadcazig) [reply components/FeatureHighlight/src/FeatureHighlightAccessibilityMutator/MDCFeatureHighlightAccessibilityMutator.m]: NA.

File: components/FeatureHighlight/tests/unit/FeatureHighlightTitleBodyAccessibilityMutatorTests.m (hunk 11 above)
Comment (mohammadcazig) [reply components/FeatureHighlight/tests/unit/FeatureHighlightTitleBodyAccessibilityMutatorTests.m]: done.

File: components/FeatureHighlight/tests/unit/FeatureHighlightTitleBodyAccessibilityMutatorTests.m (hunk 12 above)
Comment (mohammadcazig) [reply components/FeatureHighlight/tests/unit/FeatureHighlightTitleBodyAccessibilityMutatorTests.m]: Changed the test for the new functions.

File: components/FeatureHighlight/tests/unit/FeatureHighlightTitleBodyAccessibilityMutatorTests.m (hunk 13 above)
Comment (mohammadcazig) [reply components/FeatureHighlight/tests/unit/FeatureHighlightTitleBodyAccessibilityMutatorTests.m]: hmm I don't think, this should depend on the color it self since accessibility could possibly change the color at any time. It would be ideal to make sure that this class is setting the color to what accessibility returns but without OCMock that requires a lot of effort.

File: components/FeatureHighlight/tests/unit/FeatureHighlightTitleBodyAccessibilityMutatorTests.m (hunk 14 above)
Comment (mohammadcazig) [reply components/FeatureHighlight/tests/unit/FeatureHighlightTitleBodyAccessibilityMutatorTests.m]: NA.

File: components/FeatureHighlight/tests/unit/FeatureHighlightTitleBodyAccessibilityMutatorTests.m (hunk 15 above)
Comment (mohammadcazig) [reply components/FeatureHighlight/tests/unit/FeatureHighlightTitleBodyAccessibilityMutatorTests.m]: done.

File: components/FeatureHighlight/src/FeatureHighlightAccessibilityMutator/MDCFeatureHighlightAccessibilityMutator.m (hunk 3 above)
Comment (romoore) [reply components/FeatureHighlight/src/FeatureHighlightAccessibilityMutator/MDCFeatureHighlightAccessibilityMutator.m]: Yes, I believe either:

*  "<MDF..." comes before "Material..." (capital ordering first)
* "<MDF..." comes last since it is a separate project

I think randallli@ knows best.

File: components/FeatureHighlight/src/FeatureHighlightAccessibilityMutator/MDCFeatureHighlightAccessibilityMutator.m (hunk 6 above)
Comment (mohammadcazig) [reply components/FeatureHighlight/src/FeatureHighlightAccessibilityMutator/MDCFeatureHighlightAccessibilityMutator.m]: but that could effect the accessibility couldn't it?

File: components/FeatureHighlight/src/FeatureHighlightAccessibilityMutator/MDCFeatureHighlightAccessibilityMutator.m (hunk 7 above)
Comment (mohammadcazig) [reply components/FeatureHighlight/src/FeatureHighlightAccessibilityMutator/MDCFeatureHighlightAccessibilityMutator.m]: replied to the other comment.

File: components/FeatureHighlight/src/FeatureHighlightAccessibilityMutator/MDCFeatureHighlightAccessibilityMutator.m (hunk 5 above)
Comment (mohammadcazig) [reply components/FeatureHighlight/src/FeatureHighlightAccessibilityMutator/MDCFeatureHighlightAccessibilityMutator.m]: done.

File: components/FeatureHighlight/tests/unit/FeatureHighlightTitleBodyAccessibilityMutatorTests.m (hunk 9 above)
Comment (mohammadcazig) [reply components/FeatureHighlight/tests/unit/FeatureHighlightTitleBodyAccessibilityMutatorTests.m]: done

File: components/FeatureHighlight/BUILD [hunk 16]
```diff
@@ -70,6 +70,18 @@ mdc_objc_library(
     visibility = ["//visibility:public"],
 )
 
+mdc_objc_library(
+    name = "FeatureHighlightAccessibilityMutator",
+    srcs = native.glob(["src/FeatureHighlightAccessibilityMutator/*.m"]),
+    hdrs = native.glob(["src/FeatureHighlightAccessibilityMutator/*.h"]),
+    includes = ["src/FeatureHighlightAccessibilityMutator"],
```
Comment (romoore) [inline components/FeatureHighlight/BUILD:77]: Please don't export this to the include path.

File: components/FeatureHighlight/BUILD [hunk 17]
```diff
@@ -92,7 +104,8 @@ mdc_objc_library(
         ":FeatureHighlight",
         ":ColorThemer",
         ":FontThemer",
-        ":private",
+	":FeatureHighlightAccessibilityMutator",
+       	":private",
```
Comment (romoore) [inline components/FeatureHighlight/BUILD]: Nit/formatting: Please remove tab characters and only use spaces.

File: components/FeatureHighlight/src/FeatureHighlightAccessibilityMutator/MDCFeatureHighlightAccessibilityMutator.h [hunk 18]
```diff
@@ -0,0 +1,43 @@
...
+ A Mutator that will change an instance of MDCFeatureHighlightAccessibilityMutator to have a high
+ enough contrast text between its background.
+ */
+@interface MDCFeatureHighlightAccessibilityMutator : NSObject
+
+/**
+ This method will change the title color of the feature highlight to ensure a high accessiblity
+ contrast with its background if needed.
+ */
++ (void)mutateBodyColorForFeatureHighlightViewController:(MDCFeatureHighlightViewController *)fhvc
```
Comment (romoore) [inline components/FeatureHighlight/src/FeatureHighlightAccessibilityMutator/MDCFeatureHighlightAccessibilityMutator.h]: Nit/naming: Please don't use shortened parameter names like "fhvc".

File: components/FeatureHighlight/src/FeatureHighlightAccessibilityMutator/MDCFeatureHighlightAccessibilityMutator.h [hunk 19]
```diff
@@ -0,0 +1,43 @@
...
+#import <UIKit/UIKit.h>
+
+/**
+ A Mutator that will change an instance of MDCFeatureHighlightAccessibilityMutator to have a high
+ enough contrast text between its background.
+ */
+@interface MDCFeatureHighlightAccessibilityMutator : NSObject
+
+/**
+ This method will change the title color of the feature highlight to ensure a high accessiblity
```
Comment (romoore) [inline components/FeatureHighlight/src/FeatureHighlightAccessibilityMutator/MDCFeatureHighlightAccessibilityMutator.h]: Documentation: s/title/body/

File: components/FeatureHighlight/src/FeatureHighlightAccessibilityMutator/MDCFeatureHighlightAccessibilityMutator.h [hunk 20]
```diff
@@ -0,0 +1,43 @@
...
+ contrast with its background if needed.
+ */
++ (void)mutateBodyColorForFeatureHighlightViewController:(MDCFeatureHighlightViewController *)fhvc
+                            withTextAccessibilityOptions:(MDFTextAccessibilityOptions)options;
+
+/**
+ This method will change the body color of the feature highlight to ensure a high accessiblity
```
Comment (romoore) [inline components/FeatureHighlight/src/FeatureHighlightAccessibilityMutator/MDCFeatureHighlightAccessibilityMutator.h]: Documentation: s/body/title/

File: components/FeatureHighlight/src/FeatureHighlightAccessibilityMutator/MDCFeatureHighlightAccessibilityMutator.m [hunk 21]
```diff
@@ -0,0 +1,85 @@
...
+  UIColor *textColor = fhvc.bodyColor;
+  UIColor *backgroundColor =
+      [fhvc.outerHighlightColor colorWithAlphaComponent:1.0f];
+  fhvc.bodyColor =
+      [MDCFeatureHighlightAccessibilityMutator accessibleColorForTextColor:textColor
+                                                       withBackgroundColor:backgroundColor
+                                                                   options:options];
+}
+
+#pragma mark - private
```
Comment (romoore) [inline components/FeatureHighlight/src/FeatureHighlightAccessibilityMutator/MDCFeatureHighlightAccessibilityMutator.m]: Super-nit: Capitalize "private" to "Private"

File: components/FeatureHighlight/tests/unit/FeatureHighlightTitleBodyAccessibilityMutatorTests.m [hunk 22]
```diff
@@ -0,0 +1,120 @@
...
+@property (nonatomic, strong) UIView *showView;
+@end
+
+@implementation FeatureHighlightTitleBodyAccessibilityMutatorTests
+
+- (void)setUp {
+  self.showView = [[UIView alloc] init];
+  self.highlightedView = [[UIView alloc] init];
+  [self.showView addSubview:self.highlightedView];
+}
```
Comment (romoore) [inline components/FeatureHighlight/tests/unit/FeatureHighlightTitleBodyAccessibilityMutatorTests.m]: Please add `tearDown` to nil-out these properties.

File: components/FeatureHighlight/tests/unit/FeatureHighlightTitleBodyAccessibilityMutatorTests.m [hunk 23]
```diff
@@ -0,0 +1,120 @@
...
+
+- (void)testMutatorChangesTextColor {
+  for (UIColor *color in testColors()) {
+    MDCFeatureHighlightViewController *hfvc =
+        [[MDCFeatureHighlightViewController alloc] initWithHighlightedView:_highlightedView
```
Comment (romoore) [inline components/FeatureHighlight/tests/unit/FeatureHighlightTitleBodyAccessibilityMutatorTests.m]: Nit: Please use property accessors instead of the backing ivars.

File: components/FeatureHighlight/tests/unit/FeatureHighlightTitleBodyAccessibilityMutatorTests.m [hunk 24]
```diff
@@ -0,0 +1,120 @@
...
+  [MDCFeatureHighlightAccessibilityMutator
+   mutateTitleColorForFeatureHighlightViewController:hfvc
+   withTextAccessibilityOptions:options];
+  [MDCFeatureHighlightAccessibilityMutator
+   mutateBodyColorForFeatureHighlightViewController:hfvc
+   withTextAccessibilityOptions:options];
+
+  XCTAssertNotNil(hfv.titleColor);
+  XCTAssertNotNil(hfv.bodyColor);
+  XCTAssertNotEqualObjects(hfv.titleColor, [UIColor blackColor], @"");
```
Comment (romoore) [inline components/FeatureHighlight/tests/unit/FeatureHighlightTitleBodyAccessibilityMutatorTests.m]: Please verify that the expected color is set. This seems to only check that it isn't `blackColor`.

Comment (romoore) [inline components/FeatureHighlight/tests/unit/FeatureHighlightTitleBodyAccessibilityMutatorTests.m]: Please remove the empty message for the XCTAssert (here and below)

**Review by romoore — APPROVED** [review]

File: components/FeatureHighlight/tests/unit/FeatureHighlightTitleBodyAccessibilityMutatorTests.m (hunk 24 above)
Comment (mohammadcazig) [reply components/FeatureHighlight/tests/unit/FeatureHighlightTitleBodyAccessibilityMutatorTests.m]: Already replied to this on your first PR.

Comment (mohammadcazig) [reply components/FeatureHighlight/tests/unit/FeatureHighlightTitleBodyAccessibilityMutatorTests.m]: done

File: components/FeatureHighlight/tests/unit/FeatureHighlightTitleBodyAccessibilityMutatorTests.m (hunk 23 above)
Comment (mohammadcazig) [reply components/FeatureHighlight/tests/unit/FeatureHighlightTitleBodyAccessibilityMutatorTests.m]: done

File: components/FeatureHighlight/tests/unit/FeatureHighlightTitleBodyAccessibilityMutatorTests.m (hunk 22 above)
Comment (mohammadcazig) [reply components/FeatureHighlight/tests/unit/FeatureHighlightTitleBodyAccessibilityMutatorTests.m]: done

File: components/FeatureHighlight/src/FeatureHighlightAccessibilityMutator/MDCFeatureHighlightAccessibilityMutator.m (hunk 21 above)
Comment (mohammadcazig) [reply components/FeatureHighlight/src/FeatureHighlightAccessibilityMutator/MDCFeatureHighlightAccessibilityMutator.m]: done.

File: components/FeatureHighlight/src/FeatureHighlightAccessibilityMutator/MDCFeatureHighlightAccessibilityMutator.h (hunk 20 above)
Comment (mohammadcazig) [reply components/FeatureHighlight/src/FeatureHighlightAccessibilityMutator/MDCFeatureHighlightAccessibilityMutator.h]: Done.

File: components/FeatureHighlight/src/FeatureHighlightAccessibilityMutator/MDCFeatureHighlightAccessibilityMutator.h (hunk 19 above)
Comment (mohammadcazig) [reply components/FeatureHighlight/src/FeatureHighlightAccessibilityMutator/MDCFeatureHighlightAccessibilityMutator.h]: Done.

File: components/FeatureHighlight/src/FeatureHighlightAccessibilityMutator/MDCFeatureHighlightAccessibilityMutator.h (hunk 18 above)
Comment (mohammadcazig) [reply components/FeatureHighlight/src/FeatureHighlightAccessibilityMutator/MDCFeatureHighlightAccessibilityMutator.h]: Done.

File: components/FeatureHighlight/BUILD (hunk 17 above)
Comment (mohammadcazig) [reply components/FeatureHighlight/BUILD]: Done.

File: components/FeatureHighlight/BUILD (hunk 16 above)
Comment (mohammadcazig) [reply components/FeatureHighlight/BUILD:77]: Done.

Comment (romoore) [reply components/FeatureHighlight/BUILD:77]: Looks like the `includes` property is still here.

File: components/FeatureHighlight/BUILD [hunk 25]
```diff
@@ -92,7 +104,8 @@ mdc_objc_library(
         ":FeatureHighlight",
         ":ColorThemer",
         ":FontThemer",
-        ":private",
+        ":FeatureHighlightAccessibilityMutator",
+       	":private",
```
Comment (romoore) [inline components/FeatureHighlight/BUILD]: Nit: Indentation for dependencies.

File: components/FeatureHighlight/tests/unit/FeatureHighlightTitleBodyAccessibilityMutatorTests.m [hunk 26]
```diff
@@ -0,0 +1,127 @@
...
+
+- (void)tearDown {
+  [super tearDown];
+  self.showView = nil;
+  self.highlightedView = nil;
+}
+
+- (void)testMutatorChangesTextColor {
+  for (UIColor *color in testColors()) {
+    MDCFeatureHighlightViewController *hfvc =
```
Comment (romoore) [inline components/FeatureHighlight/tests/unit/FeatureHighlightTitleBodyAccessibilityMutatorTests.m]: Nit/naming: `hfvc` should be `featureHighlightViewController`

File: components/FeatureHighlight/tests/unit/FeatureHighlightTitleBodyAccessibilityMutatorTests.m [hunk 27]
```diff
@@ -0,0 +1,127 @@
...
+        [[MDCFeatureHighlightViewController alloc] initWithHighlightedView:self.highlightedView
+                                                               andShowView:self.showView
+                                                                completion:nil];
+    MDCFeatureHighlightView *hfv = (MDCFeatureHighlightView *)hfvc.view;
```
Comment (romoore) [inline components/FeatureHighlight/tests/unit/FeatureHighlightTitleBodyAccessibilityMutatorTests.m]: Nit/naming: `hfv` should be `featureHighlightView`

File: components/FeatureHighlight/tests/unit/FeatureHighlightTitleBodyAccessibilityMutatorTests.m (hunk 13 above)
Comment (romoore) [reply components/FeatureHighlight/tests/unit/FeatureHighlightTitleBodyAccessibilityMutatorTests.m]: That would be the point - if MDFTextAccessibility changes the colors, we should flag that as a change to be addressed.  Automatic unit tests are the easiest way to get that review noticed.

File: components/FeatureHighlight/tests/unit/FeatureHighlightTitleBodyAccessibilityMutatorTests.m [hunk 28]
```diff
@@ -0,0 +1,127 @@
...
+    XCTAssertNotEqualObjects(hfv.titleColor, color);
+    XCTAssertNotEqualObjects(hfv.bodyColor, color);
+  }
+}
+
+- (void)testMutatorKeepsAccessibleTextColor {
+  NSDictionary* colors = @{ [UIColor redColor]: [UIColor blackColor]};
+  for (UIColor *color in colors) {
+    MDCFeatureHighlightViewController *hfvc =
+        [[MDCFeatureHighlightViewController alloc] initWithHighlightedView:_highlightedView
```
Comment (romoore) [inline components/FeatureHighlight/tests/unit/FeatureHighlightTitleBodyAccessibilityMutatorTests.m]: Nit: Please use property accessors instead of the backing ivars here and below.

**Review by romoore — APPROVED** [review]

File: components/FeatureHighlight/BUILD (hunk 16 above)
Comment (romoore) [reply components/FeatureHighlight/BUILD:77]: Spoke offline: This is a limitation of Bazel builds until we get full rewrite rules for ObjC files.

File: components/FeatureHighlight/src/FeatureHighlightAccessibilityMutator/MDCFeatureHighlightAccessibilityMutator.h [hunk 29]
```diff
@@ -0,0 +1,45 @@
...
+ A Mutator that will change an instance of MDCFeatureHighlightAccessibilityMutator to have a high
+ enough contrast text between its background.
+ */
+@interface MDCFeatureHighlightAccessibilityMutator : NSObject
+
+/**
+ This method will change the body color of the feature highlight to ensure a high accessiblity
+ contrast with its background if needed.
+ */
++ (void)mutateBodyColorForFeatureHighlightViewController:(MDCFeatureHighlightViewController *)
```
Comment (ianegordon) [inline components/FeatureHighlight/src/FeatureHighlightAccessibilityMutator/MDCFeatureHighlightAccessibilityMutator.h]: Please merge these two methods and rename to mutate: to match our other mutators.

**Review by ianegordon — CHANGES_REQUESTED** [review]

File: components/FeatureHighlight/src/FeatureHighlightAccessibilityMutator/MDCFeatureHighlightAccessibilityMutator.h [hunk 30]
```diff
@@ -0,0 +1,37 @@
...
+ */
+@interface MDCFeatureHighlightAccessibilityMutator : NSObject
+
+/**
+ This method will change the title and body color of the feature highlight to ensure a high
+ accessiblity contrast with its background if needed.
+ */
++ (void)mutateFeatureHighlightViewController:(MDCFeatureHighlightViewController *)
+                                                    featureHighlightViewController
+                withTextAccessibilityOptions:(MDFTextAccessibilityOptions)options;
```
Comment (ianegordon) [inline components/FeatureHighlight/src/FeatureHighlightAccessibilityMutator/MDCFeatureHighlightAccessibilityMutator.h]: + (void)mutate:(MDCFeatureHighlightViewContorller *)featureHighlightViewController;

**Review by ianegordon — DISMISSED** [review]

File: components/FeatureHighlight/src/FeatureHighlightAccessibilityMutator/MDCFeatureHighlightAccessibilityMutator.h (hunk 30 above)
Comment (romoore) [reply components/FeatureHighlight/src/FeatureHighlightAccessibilityMutator/MDCFeatureHighlightAccessibilityMutator.h]: Could we please keep the MDFTextAccessibilityOptions so clients can go lighter/darker depending on their color choices?

File: components/FeatureHighlight/src/FeatureHighlightAccessibilityMutator/MDCFeatureHighlightAccessibilityMutator.h [hunk 31]
```diff
@@ -0,0 +1,35 @@
...
+ limitations under the License.
+ */
+
+@class MDCFeatureHighlightViewController;
+
+#import <MDFTextAccessibility/MDFTextAccessibility.h>
+#import <UIKit/UIKit.h>
+
+/**
+ A Mutator that will change an instance of MDCFeatureHighlightAccessibilityMutator to have a high
```
Comment (romoore) [inline components/FeatureHighlight/src/FeatureHighlightAccessibilityMutator/MDCFeatureHighlightAccessibilityMutator.h]: s/MDCFeatureHighlightAccessibilityMutator/MDCFeatureHighlightViewController/

Comment (romoore) [inline components/FeatureHighlight/src/FeatureHighlightAccessibilityMutator/MDCFeatureHighlightAccessibilityMutator.h]: Please document that this explicitly does not work for UIAppearance.

File: components/FeatureHighlight/tests/unit/FeatureHighlightTitleBodyAccessibilityMutatorTests.m [hunk 32]
```diff
@@ -0,0 +1,141 @@
...
+  featureHighlightView.bodyColor = [UIColor whiteColor];
+  [MDCFeatureHighlightAccessibilityMutator mutate:featureHighlightViewController];
+
+  XCTAssertNotNil(featureHighlightView.titleColor);
+  XCTAssertNotNil(featureHighlightView.bodyColor);
+
+  // Hard coded values, if this test fails it only means that we could mean that we changed the
+  // accessible color we are returning.
+  XCTAssertEqualObjects(featureHighlightView.titleColor,
+                        [UIColor colorWithWhite:0 alpha:0.87000000476837158]);
```
Comment (romoore) [inline components/FeatureHighlight/tests/unit/FeatureHighlightTitleBodyAccessibilityMutatorTests.m:95]: Does this pass on 32-bit and 64-bit?

File: components/FeatureHighlight/tests/unit/FeatureHighlightTitleBodyAccessibilityMutatorTests.m [hunk 33]
```diff
@@ -0,0 +1,141 @@
...
+      (MDCFeatureHighlightView *)featureHighlightViewController.view;
+
+  // Making the background color accessible with title/body color.
+  featureHighlightView.outerHighlightColor = [UIColor blackColor];
+
+  [MDCFeatureHighlightAccessibilityMutator mutate:featureHighlightViewController];
+
+  XCTAssertNotNil(featureHighlightView.titleColor);
+  XCTAssertNotNil(featureHighlightView.bodyColor);
+  XCTAssertNotEqualObjects(featureHighlightView.titleColor, [UIColor blackColor]);
```
Comment (romoore) [inline components/FeatureHighlight/tests/unit/FeatureHighlightTitleBodyAccessibilityMutatorTests.m]: I'm concerned that we're testing that it isn't `blackColor`.  Colors like `clearColor` should not be considered "passing".

File: components/Snackbar/src/private/MDCSnackbarOverlayView.m [hunk 34]
```diff
@@ -489,7 +489,7 @@ - (void)slideMessageView:(MDCSnackbarMessageView *)snackbarView
                         options:0
                      animations:^{
                        // Trigger snackbar animation.
-                       [_containingView layoutIfNeeded];
+                       [self->_containingView layoutIfNeeded];
```
Comment (romoore) [inline components/Snackbar/src/private/MDCSnackbarOverlayView.m]: Is this needed for this PR? Can we move it to a separate PR?

**Review by romoore — DISMISSED** [review]

File: components/FeatureHighlight/tests/unit/FeatureHighlightTitleBodyAccessibilityMutatorTests.m (hunk 32 above)
Comment (mohammadcazig) [reply components/FeatureHighlight/tests/unit/FeatureHighlightTitleBodyAccessibilityMutatorTests.m:95]: I believe it works with both.

**Review by romoore — APPROVED** [review]

**Review by ianegordon — APPROVED** [review]
