### PR TITLE
[NavigationBar] Pixel-align title

### LINKED ISSUE #2039: [NavigationBar] Title label is misaligned on 3x devices
### Overview
Depending on the font size and number of characters, the titleLabel in MDCNavigationBar is not pixel-aligned on 3x devices (iPhone X).

navbar-misaligned-title

### Reproduction steps
1. Open MDC Catalog &rarr; Buttons &rarr; Buttons (Dynamic Type) in a 3x retina simulator
2. Turn on Simulator Debugging option "Color Misaligned Images"
3. Verify no purple/magenta coloring in MDCNavigationBar

### Version number
35.1.0

### Operating system and device
iPhone X/iOS 11 (Simulator)

### PR DESCRIPTION
**Pull request by romoore**
On 3x devices, centering the Title label was not aligning the origin to
pixels, resulting in blurry text.

### Misaligned
navbar-title-misaligned

### Aligned
navbar-title-aligned

Closes #2039

### CODE REVIEW

**Review by willlarche — APPROVED** [review]
Oh, wow. So much better. Do you really need to check for a 0 scale?

**Review by ianegordon — APPROVED** [review]
Ah!...... nothing quite like a simple fix. ;)

File: components/NavigationBar/src/MDCNavigationBar.m [hunk 1]
```diff
@@ -317,8 +317,13 @@ - (void)layoutSubviews {
   CGRect alignedFrame = [self mdc_frameAlignedVertically:titleFrame
                                             withinBounds:textFrame
                                                alignment:titleVerticalAlignment];
-  _titleLabel.frame =
-      [self mdc_frameAlignedHorizontally:alignedFrame alignment:self.titleAlignment];
+  alignedFrame = [self mdc_frameAlignedHorizontally:alignedFrame alignment:self.titleAlignment];
+  CGFloat scale = self.window.screen.scale;
```
Comment (ianegordon) [inline components/NavigationBar/src/MDCNavigationBar.m]: Perhaps we want MDC*ToScale() to treat a scale of 0.0 as if it were equal to device.screen.scale?
We could avoid checking for 0.0 every time.
Might be an issue for people outputting to a second screen via airplay?

**Comment by romoore** [comment]
Regarding the 0-check, you aren't the first person to ask about it *cough* Ian *cough*. I think maybe it's better to change the behavior of the function to just return the original CGRect if the scale is 0. It's just pixel-pushing, so if the rect is misaligned it's not going to cause functional errors.

I'll wait for my current PRs to roll through Travis before pushing up the change.

File: components/NavigationBar/src/MDCNavigationBar.m (hunk 1 above)
Comment (romoore) [reply components/NavigationBar/src/MDCNavigationBar.m]: Since this is a C-function, it's difficult to know [which of the screens](https://developer.apple.com/documentation/uikit/uiscreen/1617812-screens) we should use for the scale factor.  It would work as an extension on UIView, though.

Comment (romoore) [reply components/NavigationBar/src/MDCNavigationBar.m]: I think between returning an unaligned frame and trying to guess which scale to use, it might make sense to just default to 1x if it's not provided - at least then it'll point-align and be guaranteed to be pixel-aligned.

Comment (willlarche) [reply components/NavigationBar/src/MDCNavigationBar.m]: I'm still not convinced this is really a problem and I don't want to clutter up the codebase with a check for it. We use scale all over the place.

Comment (romoore) [reply components/NavigationBar/src/MDCNavigationBar.m]: Yes, I think we're in agreement that the check should not be necessary for clients. I'd like to change the function to be safe (it currently returns CGRectNull), so  I hope we're discussing what default behavior to provide.

My recommendation is to return the rect aligned to a 1x scale, though we could just return the original rect instead.

**Comment by romoore** [comment]
Tests were failing on Travis CI because we perform MDCNavBar layout during unit tests. Travis seems to be a headless environment where there is no window available to retrieve the scale factor.
