### PR TITLE
[BottomNavigation] Remove ink for canceled touch

### LINKED ISSUE #2909: [BottomNavigation]  Abandoned ink persists in bottom navigation bar after rotation (b/73060904)
Originally reported by @brianjmoore 

### Overview
The bottom navigation bar can sometimes end up with abandoned ink that sticks around seemingly indefinitely.

bottomnav-ink-bug

### Reproduction steps
1. Build and run the MDC catalog
2. Open the bottom nav example
3. Touch one of the tabs and while holding rotate the device

RESULT: Ink is abandoned, sticks around indefinitely.

### Version number
44.6.0

### Operating system and device
iPhone 5/iOS 10.3.3

### PR DESCRIPTION
**Pull request by romoore**
When a touch was canceled (e.g., by rotating the device) and the touch event
was canceled, the Bottom Navigation Bar was not canceling the ink animation.

Closes #2909

### CODE REVIEW

File: components/BottomNavigation/src/MDCBottomNavigationBar.m [hunk 1]
```diff
@@ -452,6 +452,9 @@ - (void)setItems:(NSArray<UITabBarItem *> *)items {
     [itemView.button addTarget:self
                         action:@selector(didTouchUpOutsideButton:)
               forControlEvents:UIControlEventTouchUpOutside];
+    [itemView.button addTarget:self
+                        action:@selector(didTouchUpOutsideButton:)
+              forControlEvents:UIControlEventTouchCancel];
```
Comment (ajsecord) [inline components/BottomNavigation/src/MDCBottomNavigationBar.m]: You don't want animation for cancelations.

**Review by ajsecord — DISMISSED** [review]

File: components/BottomNavigation/src/MDCBottomNavigationBar.m (hunk 1 above)
Comment (romoore) [reply components/BottomNavigation/src/MDCBottomNavigationBar.m]: Why not? It looks good for the use cases I could think of:

* Tap-and-hold a tab item and then rotate the device (ink dissipates)
* Tap-and-hold a tab item, then swipe down and swipe up to show the Control Panel.

Is there a use case where we are canceling touch events and Ink should not dissipate?

**Animated Cancel**
bottomnav-ink-fix-animated

**Immediate Cancel**
bottomnav-ink-fix-immediate

Comment (romoore) [reply components/BottomNavigation/src/MDCBottomNavigationBar.m]: Switched to immediately cancel ink after further discussion with @randallli and @yarneo .

Comment (randallli) [reply components/BottomNavigation/src/MDCBottomNavigationBar.m]: This should work the same way we cancel the ink when a collection view scroll gesture may initially start ink.

**Review by ianegordon — APPROVED** [review]
LGTM
