### PR TITLE
[BottomAppBar] Use the height of bottom app bar as the contentInset of table view

### LINKED ISSUE #3689: [BottomAppBar] "Toggle FAB Visibility" cell is inaccessible in landscape
### Overview
When the example is in landscape orientation, the cell for "Toggle FAB Visibility" is completely unreachable.

bab-landscape-hidden-cell

### Reproduction steps
1 Set the device text larger using the Settings App &rarr; General &rarr; Larger text
1. Open the catalog
1. Rotate to Landscape
1. Open Bottom App Bar &rarr; Start Demo
1. Scroll to the bottom

### Version number
55.0.0

### Operating system and device
iPhone X/iOS 11.3 (Simulator)

### PR DESCRIPTION
**Pull request by fluxminds**
closes #3689

Before the change:
simulator screen shot - iphone 5 - 2018-08-28 at 14 53 04

After the change:
simulator screen shot - iphone x - 2018-08-30 at 16 35 01

### CODE REVIEW

File: components/BottomAppBar/examples/supplemental/BottomAppBarTypicalUseSupplemental.m [hunk 1]
```diff
@@ -81,7 +81,9 @@ - (instancetype)initWithNibName:(NSString *)nibNameOrNil bundle:(NSBundle *)nibB
                                         @"Trailing Floating Button",
                                         @"Primary Elevation Floating Button",
                                         @"Secondary Elevation Floating Button",
-                                        @"Visible FAB" ];
+                                        @"Visible FAB",
+                                        @"",
+                                        @""]; // the last two empty items are used for offset
```
Comment (andrewoverton) [inline components/BottomAppBar/examples/supplemental/BottomAppBarTypicalUseSupplemental.m]: I'm a little confused about what's going on... Is the problem that without these extra cells the last few cells are obscured by the bottom app bar/fab? If this is the case, it might be worth taking advantage of the [`contentInset`](https://developer.apple.com/documentation/uikit/uiscrollview/1619406-contentinset) property to make sure you can scroll to every cell, even the part that the app bar is covering. Not sure though, I could be misunderstanding something.

Comment (fluxminds) [reply components/BottomAppBar/examples/supplemental/BottomAppBarTypicalUseSupplemental.m]: Good point! Addressed in 08dffd2

**Comment by jverkoey** [comment]
@wenyuzhang666 Please update the PR description and title with the fact that you're now using contentInset to solve the bug.

File: components/BottomAppBar/examples/supplemental/BottomAppBarTypicalUseSupplemental.m [hunk 2]
```diff
@@ -130,7 +139,7 @@ - (UITableViewCell *)tableView:(UITableView *)tableView
   cell.layoutMargins = UIEdgeInsetsZero;
   cell.textLabel.text = self.listItems[indexPath.item];
   [self.fabVisibilitySwitch removeFromSuperview];
-  if (indexPath.row == (NSInteger)(self.listItems.count - 1)) {
+  if ([self.listItems[indexPath.row] isEqualToString:@"Visible FAB"]) {
```
Comment (jverkoey) [inline components/BottomAppBar/examples/supplemental/BottomAppBarTypicalUseSupplemental.m]: This is probably a good change, but it's unrelated to this PR. Can you break this out to a separate pull request?

Comment (fluxminds) [reply components/BottomAppBar/examples/supplemental/BottomAppBarTypicalUseSupplemental.m]: Since the implementation was changed to using contentInset, I think the original implementation here is good. I reverted this one in the code review change commit.

**Comment by fluxminds** [comment]
@jverkoey Comments have been addressed, and description has been updated.

**Review by jverkoey — APPROVED** [review]
