### PR TITLE
[FlexibleHeader] Introduce minMaxHeightIncludesSafeArea and fix rotation bugs.

### LINKED ISSUE #2156: AppBar Covering top of scrollview after rotation
### Overview
I've managed to repro what appears to be #2151 or a related issue outside of the Catalog app. It is affecting all ScrollViews tracked by MDCAppBar on all devices iOS 11.

### Example project
https://github.com/despisedIcon/AppBarBugExample

simulator screen shot - iphone x - 2017-10-12 at 09 07 50simulator screen shot - iphone x - 2017-10-12 at 09 07 54

### Reproduction steps
 - Download example project
 - Set simulator to landscape
 - Launch project
 - Rotate simulator 90deg CW to portrait

### Version number
 - 35.3.0

### Operating system and device
 - iOS 11
 - iPhone 6,7,8,X

### Related issues
 - #2151 #2069

### PR DESCRIPTION
**Pull request by chuga**
Starting on iOS 11, this component adjusts its height to account for changes in the Safe Area insets. But the current solution only works for the default min/max height values, as we've internally de-hardcoded the status bar height from them. We currently don't offer an API for people who want to use a custom mix/max height and still get the same behavior. This PR introduces such API.

The new `minMaxHeightIncludesSafeArea` property lets us know if the provided min/max height already includes the safe area insets or not. If this is set to NO (the default is YES), we take care of adjusting for any safe area changes internally.

Note: This rollbacks the rollback https://github.com/material-components/material-components-ios/pull/2161 + introduces a few fixes.

Closes #2156

### CODE REVIEW

File: components/FlexibleHeader/src/MDCFlexibleHeaderView.m [hunk 1]
```diff
@@ -298,16 +308,24 @@ - (void)commonMDCFlexibleHeaderViewInit {
...
   if (@available(iOS 11.0, *)) {
-    // Starting from iOS 11, we should adapt the size of this component to take into account
-    // the new status bar sizes and the "no status bar in landscape" functionality.
-    CGFloat statusBarHeight = [UIApplication mdc_safeSharedApplication].statusBarFrame.size.height;
+    // Starting from iOS 11, the default behavior of this component is to adapt its height to
+    // account for changes in the Safe Area insets. We're using the status bar frame instead of
+    // the safeAreaInsets property because at this point this view's Safe Area hasn't been
+    // calculated by the OS.
+    CGFloat statusBarHeight =
+        CGRectGetMaxY([UIApplication mdc_safeSharedApplication].statusBarFrame);
```
Comment (jverkoey) [inline components/FlexibleHeader/src/MDCFlexibleHeaderView.m]: I think that all of these types of calls will likely want to move to using a `DeviceTopSafeAreaInset()` call in order to be consistent across hardware.

File: components/FlexibleHeader/src/MDCFlexibleHeaderView.m [hunk 2]
```diff
@@ -1310,6 +1350,38 @@ - (void)setMaximumHeight:(CGFloat)maximumHeight {
   }
 }
 
+- (CGFloat)computedTotalMinHeight {
```
Comment (jverkoey) [inline components/FlexibleHeader/src/MDCFlexibleHeaderView.m]: `computedMinimumHeight`

File: components/FlexibleHeader/src/MDCFlexibleHeaderView.m [hunk 3]
```diff
@@ -1310,6 +1350,38 @@ - (void)setMaximumHeight:(CGFloat)maximumHeight {
...
+  if (_minMaxHeightIncludesSafeArea) {
+    return _minimumHeight;
+  } else {
+    return _minimumHeight + [self flexibleHeaderSafeAreaTop];
+  }
+}
+
+- (CGFloat)computedTotalMaxHeight {
```
Comment (jverkoey) [inline components/FlexibleHeader/src/MDCFlexibleHeaderView.m]: `computedMaximumHeight`

File: components/FlexibleHeader/src/MDCFlexibleHeaderView.m [hunk 4]
```diff
@@ -1408,6 +1481,23 @@ - (void)setContentIsTranslucent:(BOOL)contentIsTranslucent {
...
+    // Note: This appears to be fixed on iOS 11.1.
+    if ([self isDescendantOfView:_trackingScrollView]) {
+      return _trackingScrollView.safeAreaInsets.top;
+    } else {
+      return self.safeAreaInsets.top;
+    }
+  }
+#endif
+  // If < iOS 11.0 we should return the hardcoded status bar height for backwards compatibility.
+  return kPreIOS11ExpectedStatusBarHeight;
```
Comment (jverkoey) [inline components/FlexibleHeader/src/MDCFlexibleHeaderView.m]: This looks pretty similar to DeviceTopSafeAreaInset - is it time to extract that impl to MDC?

**Comment by jverkoey** [comment]
#2185 is out for review. We'll be able to use that API to improve the stability of top margin calculations in both the Flexible Header and the App Bar.

File: components/FlexibleHeader/src/MDCFlexibleHeaderView.m [hunk 5]
```diff
@@ -436,46 +454,44 @@ - (void)setBackgroundColor:(UIColor *)backgroundColor {
...
+    _currentSafeAreaInsetTop = safeAreaTop;
+
+    // If the min or max height have been explicitly set, don't adjust anything if the values
+    // already include a Safe Area inset.
+    if (_hasExplicitlySetMinOrMaxHeight && _minMaxHeightIncludesSafeArea) {
+      return;
+    } else if (!_hasExplicitlySetMinOrMaxHeight && _minMaxHeightIncludesSafeArea) {
+      // If we're using the defaults we need to update them to account for the new Safe Area inset.
+      _minimumHeight = kFlexibleHeaderDefaultHeight + [self flexibleHeaderSafeAreaTop];
+      _maximumHeight = kFlexibleHeaderDefaultHeight + [self flexibleHeaderSafeAreaTop];;
```
Comment (jverkoey) [inline components/FlexibleHeader/src/MDCFlexibleHeaderView.m]: `_maximumHeight = _minimumHeight`

File: components/FlexibleHeader/src/MDCFlexibleHeaderView.m [hunk 6]
```diff
@@ -436,46 +454,44 @@ - (void)setBackgroundColor:(UIColor *)backgroundColor {
...
       CGRect bounds = self.bounds;
-      bounds.size.height = _minimumHeight;
+      bounds.size.height = self.computedMinimumHeight;
       self.bounds = bounds;
-      [self fhv_commitAccumulatorToFrame];
+      CGPoint position = self.center;
+      position.y = -MIN([self fhv_accumulatorMax], _shiftAccumulator);
+      position.y += self.bounds.size.height / 2;
+      self.center = position;
+      [self.delegate flexibleHeaderViewFrameDidChange:self];
```
Comment (jverkoey) [inline components/FlexibleHeader/src/MDCFlexibleHeaderView.m]: Can you document why we're not using fhv_commitAccumulatorToFrame here? The main difference I see is that the `_statusBarShifter` isn't being updated anymore.

Comment (chuga) [reply components/FlexibleHeader/src/MDCFlexibleHeaderView.m]: fhv_commitAccumulatorToFrame calls fhv_accumulatorDidChange, and that method sets the shadow opacity to the default opacity (0.4) even when we're not tracking a scroll view -_-

**Comment by chuga** [comment]
Ready for review, now using MDCDeviceTopSafeAreaInset

**Comment by chuga** [comment]
Ping

File: MaterialComponents.podspec [hunk 7]
```diff
@@ -551,6 +552,14 @@ Pod::Spec.new do |s|
...
     end
 
+    pss.subspec "UIMetrics" do |ss|
+      ss.ios.deployment_target = '8.0'
+      ss.public_header_files = "components/private/#{ss.base_name}/src/*.h"
+      ss.source_files = "components/private/#{ss.base_name}/src/*.{h,m}", "components/private/#{ss.base_name}/src/private/*.{h,m}"
+
+      ss.dependency "MaterialComponents/private/Application"
+    end
+
```
Comment (jverkoey) [inline MaterialComponents.podspec]: May have to rebase off the latest develop?

File: components/FlexibleHeader/src/MDCFlexibleHeaderView.m [hunk 8]
```diff
@@ -436,46 +442,44 @@ - (void)setBackgroundColor:(UIColor *)backgroundColor {
...
+    _currentSafeAreaInsetTop = safeAreaTop;
+
+    // If the min or max height have been explicitly set, don't adjust anything if the values
+    // already include a Safe Area inset.
+    if (_hasExplicitlySetMinOrMaxHeight && _minMaxHeightIncludesSafeArea) {
+      return;
+    } else if (!_hasExplicitlySetMinOrMaxHeight && _minMaxHeightIncludesSafeArea) {
+      // If we're using the defaults we need to update them to account for the new Safe Area inset.
+      _minimumHeight = kFlexibleHeaderDefaultHeight + MDCDeviceTopSafeAreaInset();
+      _maximumHeight = kFlexibleHeaderDefaultHeight + MDCDeviceTopSafeAreaInset();
```
Comment (jverkoey) [inline components/FlexibleHeader/src/MDCFlexibleHeaderView.m]: `_maximumHeight = _minimumHeight`

**Review by jverkoey — APPROVED** [review]

**Review by jverkoey — APPROVED** [review]

**Comment by chuga** [comment]
Since Travis ran with the latest changes that are not documentation, I'll go ahead and merge without waiting for it. Thanks for the reviews!
