### PR TITLE
[FlexibleHeader] Make sure we update the layout when the safe area changes

### LINKED ISSUE #2067: [FlexibleHeader] The height isn't being updated if we're not tracking a scroll view
### Overview
The FlexibleHeader's updateLayout is a no-op when there's no trackingScrollView. Since this component now reacts to changes to the safe area, and adjusts its size accordingly, we need to make sure we update its frame when that happens.

### Reproduction steps
- Open the Catalog app
- Navigate to Collections
- Open an example
- Rotate the device and notice that the flexible header didn't change in size.

### Version number
35.2.0

### Operating system and device
iPhone X

### PR DESCRIPTION
**Pull request by chuga**
Closes #2067

### CODE REVIEW

File: components/FlexibleHeader/src/MDCFlexibleHeaderView.m [hunk 1]
```diff
@@ -822,7 +822,15 @@ - (void)fhv_accumulatorDidChange {
 
 - (void)fhv_updateLayout {
   if (!_trackingScrollView) {
-    return;
+    // Even if we're not tracking a scroll view, our minimumHeight might have changed due to new
+    // safe area insets.
+    if (_minimumHeight > 0 && self.bounds.size.height != _minimumHeight) {
```
Comment (ianegordon) [inline components/FlexibleHeader/src/MDCFlexibleHeaderView.m]: frame and bounds may have negative values for size.height and size.width.
Use CGRectGetHeight(self.frame) and other CGRectFunc() instead of accessing the struct directly.

File: components/FlexibleHeader/src/MDCFlexibleHeaderView.m [hunk 2]
```diff
@@ -822,7 +822,15 @@ - (void)fhv_accumulatorDidChange {
...
+      CGRect bounds = self.bounds;
+      bounds.size.height = _minimumHeight;
+      self.bounds = bounds;
+      [self fhv_commitAccumulatorToFrame];
+      return;
```
Comment (ianegordon) [inline components/FlexibleHeader/src/MDCFlexibleHeaderView.m]: We are moving this return call, should it be outside this if block?

**Review by ianegordon — CHANGES_REQUESTED** [review]

File: components/FlexibleHeader/src/MDCFlexibleHeaderView.m (hunk 1 above)
Comment (chuga) [reply components/FlexibleHeader/src/MDCFlexibleHeaderView.m]: Done

File: components/FlexibleHeader/src/MDCFlexibleHeaderView.m (hunk 2 above)
Comment (chuga) [reply components/FlexibleHeader/src/MDCFlexibleHeaderView.m]: Good catch, done.

**Review by randallli — APPROVED** [review]

**Comment by chuga** [comment]
This *did* pass on Travis (see https://travis-ci.org/material-components/material-components-ios/builds/283731076, the error is not an actual test that failed).

I'll go ahead and merge this in.
