### PR TITLE
[Catalog] Track our scroll views.

### LINKED ISSUE #2209: [Catalog] AppBar does not have the Collections example as tracking scroll view
### Overview
The AppBar used in the Collections example does not have the collection as tracking scroll view. It creates problems, in particular on iPhone X: when rotating, there is a visible gap between the AppBar and the collection.
Also the shadow is not displayed below the AppBar when scrolling the collection.

simulator screen shot - iphone x - 2017-10-17 at 17 04 12

### Reproduction steps
 - Open a Collection example and rotate the device.

### Version number
 - 36.3.0

### Operating system and device
- iPhone X, iOS 11.

### PR DESCRIPTION
**Pull request by chuga**
Closes #2209 and #2069

### CODE REVIEW

**Review by willlarche — APPROVED** [review]

File: catalog/MDCCatalog/MDCNodeListViewController.swift [hunk 1]
```diff
@@ -382,26 +382,32 @@ extension MDCNodeListViewController {
...
-        let headerSize = headerView.sizeThatFits(container.contentViewController.view.frame.size)
-        contentFrame.origin.y = headerSize.height
-        contentFrame.size.height = self.view.bounds.size.height - headerSize.height
-        container.contentViewController.view.frame = contentFrame
+        // TODO(featherless): Remove once
+        // https://github.com/material-components/material-components-ios/issues/367 is resolved.
+        contentVC.title = node.title
+
+        let headerView = container.appBar.headerViewController.headerView
+        if contentVC.isKind(of: MDCCollectionViewController.self) {
```
Comment (willlarche) [inline catalog/MDCCatalog/MDCNodeListViewController.swift]: Use an `if let` here instead of an `if` followed by force unwrapping. It would be more expected.

File: catalog/MDCCatalog/MDCNodeListViewController.swift [hunk 2]
```diff
@@ -382,26 +382,32 @@ extension MDCNodeListViewController {
...
+          let collectionVC = contentVC as! MDCCollectionViewController
+          headerView.trackingScrollView = collectionVC.collectionView
+        } else if contentVC.view.isKind(of: UIScrollView.self) {
+          headerView.trackingScrollView = contentVC.view as? UIScrollView
```
Comment (willlarche) [inline catalog/MDCCatalog/MDCNodeListViewController.swift]: Can you do an `if let ... as?` here?

File: catalog/MDCCatalog/MDCNodeListViewController.swift [hunk 3]
```diff
@@ -382,26 +382,32 @@ extension MDCNodeListViewController {
...
+        } else {
+          // TODO(chuga): This is bad. We should be adjusting for Safe Area changes.
+          var contentFrame = container.contentViewController.view.frame
+          let headerSize = headerView.sizeThatFits(container.contentViewController.view.frame.size)
+          contentFrame.origin.y = headerSize.height
+          contentFrame.size.height = self.view.bounds.size.height - headerSize.height
```
Comment (willlarche) [inline catalog/MDCCatalog/MDCNodeListViewController.swift]: You don't have to go thru `size` to get to height. You can `rect.height` in swift.

**Review by willlarche — CHANGES_REQUESTED** [review]

**Comment by chuga** [comment]
Thanks for the review, ptal

**Review by willlarche — APPROVED** [review]
