### PR TITLE
[Chips] Make collectionView in Chip Demo respect safe area

### LINKED ISSUE #3704: [Chips] Demo does not respect safe area
### Overview
The Chips Demo causes Chips to overlap the safe area in Landscape mode.

chips-1

### Reproduction steps
1. Open the catalog 
1. Open Chips &rarr; Start Demo
1. Rotate to Landscape

### Version number
55.0.1

### Operating system and device
iPhone X/iOS 11.3 (Simulator)

### Related issues
#3690 

---
https://www.pivotaltracker.com/story/show/157313289

### PR DESCRIPTION
**Pull request by fluxminds**
closes #3704

Before:
image

After:
chip2

### CODE REVIEW

File: components/Chips/examples/ChipsTypicalUseViewController.m [hunk 1]
```diff
@@ -73,6 +73,11 @@ - (void)viewDidLoad {
                                            selector:@selector(contentSizeCategoryDidChange)
                                                name:UIContentSizeCategoryDidChangeNotification
                                              object:nil];
+#if defined(__IPHONE_11_0) && (__IPHONE_OS_VERSION_MAX_ALLOWED >= __IPHONE_11_0)
```
Comment (romoore) [inline components/Chips/examples/ChipsTypicalUseViewController.m]: I believe you can drop the macros. We no longer support Xcode 8.

**Review by romoore — APPROVED** [review]
