### PR TITLE
[Button|Ink|TextFields|Palettes] Fixed NSNumber conversion static analyzer errors

### LINKED ISSUE #2935: Static Analyzer - Converting NSNumber to primitive
Open MDCCatalog -> MDCDragons
Product Analyze

Multiple warnings:
Converting a pointer value of type 'NSNumber *' to a primitive boolean value; instead, either compare the pointer to nil or call -boolValue.

### PR DESCRIPTION
**Pull request by sigito**
Fixes #2935.

### CODE REVIEW

File: components/Buttons/src/MDCButton.m [hunk 1]
```diff
@@ -686,13 +686,10 @@ - (void)setBackgroundColor:(UIColor *)backgroundColor forState:(UIControlState)s
...
   NSNumber *elevation = _userElevations[@(state)];
-  if (state != UIControlStateNormal && !elevation) {
+  if (state != UIControlStateNormal && elevation == nil) {
     elevation = _userElevations[@(UIControlStateNormal)];
   }
-  if (elevation) {
-    return (CGFloat)[elevation doubleValue];
-  }
-  return 0;
+  return (CGFloat)elevation.doubleValue;
```
Comment (ajsecord) [inline components/Buttons/src/MDCButton.m]: FYI, we usually prefer an explicit value instead of relying on the Objective-C runtime to return zero when the pointer is nil. The reason is twofold: it shows the programmer thought about the case and deliberately chose zero, and if the value to return changes it can be easily updated.

I usually prefer the `?:` form below, but that's up to the individual programmer.

**Review by ajsecord — APPROVED** [review]

File: components/Buttons/src/MDCButton.m [hunk 2]
```diff
@@ -727,11 +724,7 @@ - (void)setBorderColor:(UIColor *)borderColor forState:(UIControlState)state {
 #pragma mark - Border Width
 
 - (CGFloat)borderWidthForState:(UIControlState)state {
-  NSNumber *borderWidth = _borderWidths[@(state)];
-  if (borderWidth) {
-    return (CGFloat)borderWidth.doubleValue;
-  }
-  return 0;
+  return (CGFloat)_borderWidths[@(state)].doubleValue;
```
Comment (ianegordon) [inline components/Buttons/src/MDCButton.m]: The implementation of borderWidthForState: and elevationForState: are different.
elevation returns valueForState:UIControlStateNormal if valueForState:state doesn't exist.
This one returns 0 and handles in updateBorderWidth.

Please migrate borderWidthForState to the same implementation as elevationForState.

Understood if you want to do this in a different PR.

Comment (ianegordon) [inline components/Buttons/src/MDCButton.m]: return (CGFloat)_borderWidth[@(state)].doubleValue doesn't convey to future engineers that undefined values are explicitly intended to be 0.

Please use the Elvis operator:
return _borderWidth[@(state)] ? (CGFloat)_borderWidths[@(state)].doubleValue : (CGFloat)0;

**Review by ianegordon — CHANGES_REQUESTED** [review]

File: components/Buttons/src/MDCButton.m (hunk 1 above)
Comment (sigito) [reply components/Buttons/src/MDCButton.m]: Oh, I did not know that. Thanks.

I used a ternary instead since we want to unbox the value.

File: components/Buttons/src/MDCButton.m (hunk 2 above)
Comment (sigito) [reply components/Buttons/src/MDCButton.m]: Moved logic from `updateBorderWidth`.

Should we apply the same logic for `titleFontForState:`?

Comment (sigito) [reply components/Buttons/src/MDCButton.m]: Done. However, I added a `nil` check, since that is exactly what the analyzer complains about.

**Review by ianegordon — DISMISSED** [review]

**Review by ianegordon — CHANGES_REQUESTED** [review]
LGTM.  Fix casting issues in Travis and we can land.
Thanks for the PR!

**Comment by sigito** [comment]
Done.

**Review by ianegordon — APPROVED** [review]

**Comment by ianegordon** [comment]
Thank you @sigito !
