### PR TITLE
[ButtonBar] Fix incorrect casts in ButtonBar

### LINKED ISSUE #4934: [ButtonBar] Clean up improper casts after isKindOfClass checks
There are a few places in ButtonBar where we do an isKindOfClass check followed by a cast to a different type. These checks are unsafe and could potentially lead to crashes. We should be casting only to the type that we're checking or vice versa.

https://github.com/material-components/material-components-ios/blob/63eeff1d3020615d8be5f088887a2a7b7ec4dbec/components/ButtonBar/src/MDCButtonBar.m#L412-L414

### PR DESCRIPTION
**Pull request by rami-a**
This change updates a couple of improper casts in ButtonBar that had the potential to cause a crash.
Closes #4934

### CODE REVIEW

File: components/ButtonBar/src/MDCButtonBar.m [hunk 1]
```diff
@@ -477,7 +477,7 @@ - (void)setButtonsTitleColor:(nullable UIColor *)color forState:(UIControlState)
 
   for (UIView *viewObj in _buttonViews) {
     if ([viewObj isKindOfClass:[UIButton class]]) {
```
Comment (codeman7) [inline components/ButtonBar/src/MDCButtonBar.m]: _Tip:_ I think we should match our checks and cast throughout the file, I noticed there are a couple of instances that check against `MDCButton` maybe update this to check `MDCButton` then cast to `MDCButton`.

**Review by codeman7 — APPROVED** [review]

File: components/ButtonBar/src/MDCButtonBar.m (hunk 1 above)
Comment (rami-a) [reply components/ButtonBar/src/MDCButtonBar.m]: Agree, done

**Review by jverkoey — APPROVED** [review]

File: components/ButtonBar/src/MDCButtonBar.m [hunk 2]
```diff
@@ -446,7 +446,7 @@ - (void)setButtonsTitleFont:(UIFont *)font forState:(UIControlState)state {
 
   for (NSUInteger i = 0; i < [_buttonViews count]; ++i) {
     UIView *viewObj = _buttonViews[i];
-    if ([viewObj isKindOfClass:[UIButton class]]) {
+    if ([viewObj isKindOfClass:[MDCButton class]]) {
       MDCButton *button = (MDCButton *)viewObj;
```
Comment (jverkoey) [inline components/ButtonBar/src/MDCButtonBar.m:450]: I think in this case because we're not using any traits of MDCButton we can just cast to a UIButton instead. What do you think?

File: components/ButtonBar/src/MDCButtonBar.m [hunk 3]
```diff
@@ -476,7 +476,7 @@ - (void)setButtonsTitleColor:(nullable UIColor *)color forState:(UIControlState)
   [_defaultBuilder setTitleColor:color forState:state];
 
   for (UIView *viewObj in _buttonViews) {
-    if ([viewObj isKindOfClass:[UIButton class]]) {
+    if ([viewObj isKindOfClass:[MDCButton class]]) {
       MDCButton *button = (MDCButton *)viewObj;
       [button setTitleColor:color forState:state];
```
Comment (jverkoey) [inline components/ButtonBar/src/MDCButtonBar.m:481]: Possibly similarly here.

File: components/ButtonBar/src/MDCButtonBar.m (hunk 2 above)
Comment (rami-a) [reply components/ButtonBar/src/MDCButtonBar.m:450]: `setTitleFont` looks specific to MDCButton, so this would have to remain.

File: components/ButtonBar/src/MDCButtonBar.m (hunk 3 above)
Comment (rami-a) [reply components/ButtonBar/src/MDCButtonBar.m:481]: This could be UIButton, I think either cast would be fine but I'm going to go with MDCButton for consistency.

File: components/ButtonBar/src/MDCButtonBar.m (hunk 2 above)
Comment (jverkoey) [reply components/ButtonBar/src/MDCButtonBar.m:450]: Cool - thanks for checking!

**Comment by AdibContractorCC** [comment]
This needs full regression
