### PR TITLE
[TextFields] Arabic RTL snapshot tests

### LINKED ISSUE #6022: [TextFields] Snapshot tests need a way to force RTL layout
The snapshot tests for Text Fields should be able to render RTL script in RTL layout. However, setting neither the `effectiveUserInterfaceLayoutDirection` nor the `semanticContentAttribute`  seems to convince the text input that the text is in RTL.  The best that happens is some constraints updates, but neither the helper text nor the actual input text is positioned correctly.

## (Broken) Example:
failed_testtextfieldwithshortinputplaceholderhelpertextsisediting_11_2 2x

---
#### Internal data
- Associated internal bug: [b/121040596](http://b/121040596)

### PR DESCRIPTION
**Pull request by romoore**
Adding a single set of Arabic-language RTL snapshot tests for Text Fields. 

Closes #6022

### CODE REVIEW

File: components/TextFields/tests/snapshot/supplemental/MDCAbstractTextFieldSnapshotTests+I18N.m [hunk 1]
```diff
@@ -20,6 +20,34 @@
...
 
+- (void)MDCForceTextInputRightToLeft:(UIView *)view {
+  if ([view conformsToProtocol:@protocol(UITextInput)]) {
+    id<UITextInput> textInput = (id<UITextInput>)view;
+    UITextRange *textRange = [textInput textRangeFromPosition:textInput.beginningOfDocument
+                                                   toPosition:textInput.endOfDocument];
+    if (textRange) {
+      [textInput setBaseWritingDirection:UITextWritingDirectionRightToLeft forRange:textRange];
+    } else {
+      XCTAssertNotNil(textRange);
```
Comment (fluxminds) [inline components/TextFields/tests/snapshot/supplemental/MDCAbstractTextFieldSnapshotTests+I18N.m:32]: I might misunderstand things here. What are `textRange` expected to look like here?

**Review by fluxminds — APPROVED** [review]
One small question left on the pull request.

File: components/TextFields/tests/snapshot/supplemental/MDCAbstractTextFieldSnapshotTests+I18N.m (hunk 1 above)
Comment (romoore) [reply components/TextFields/tests/snapshot/supplemental/MDCAbstractTextFieldSnapshotTests+I18N.m:32]: textRange is the UITextRange of the currently-input text of the text field.

Comment (fluxminds) [reply components/TextFields/tests/snapshot/supplemental/MDCAbstractTextFieldSnapshotTests+I18N.m:32]: Followed up offline, we want an assertion failure to be thrown if the `else` block is executed. And because XCTAssert doesn't stop execution. Moving this line above the `setBase..` would still require the `if (textRange)` guard. Putting a comment there would make it clear:)

Comment (romoore) [reply components/TextFields/tests/snapshot/supplemental/MDCAbstractTextFieldSnapshotTests+I18N.m:32]: Done
