### PR TITLE
[Buttons] [MaskedTransition] Apply safe area to floating button example and masked transition example

### LINKED ISSUE #3702: [Buttons] FloatingButtonExampleViewController does not respect safe area
### Overview
The buttons are overlapping the notch in landscape mode. When started in Portrait and rotated to Landscape, there is an extra black bar at the top (below the AppBar) that is the backing view's empty background.

floating-1

### Reproduction Steps
1. Open the catalog in Portrait
1. Open Buttons &rarr; Floating Action Button
1. Note the position of the FABs
1. Rotate to Portrait, not the black bar below the AppBar

### Version number
55.0.1

### Operating system and device
iPhone X/iOS 11.3 (Simulator)

### Related issues
#3685

### LINKED ISSUE #3714: [MaskedTransition] Presented sheet ignores safe area
### Overview
The Masked Transition example completely ignores the safe area when presenting the view controller. I'm not sure if the bottom sheet should be presented within the safe area or if the presented VC should position its content within the safe area instead.

simulator screen shot - iphone x - 2018-05-04 at 10 18 52

----

simulator screen shot - iphone x - 2018-05-04 at 10 18 56

----

simulator screen shot - iphone x - 2018-05-04 at 10 19 06

### Reproduction steps
1. Open the catalog
1. Open Masked Transition &rarr; Start Demo
1. Tap on one of the FABs

### Version number
55.0.1

### Operating system and device
iPhone X/iOS 11.3 (Simulator)

### PR DESCRIPTION
**Pull request by rami-a**
This change applies the safe area to the examples for Floating Button and Masked Transition so that they appear correct on notched displays in landscape.

Closes #3702 
Closes #3714 

Floating Buttons Before:
simulator screen shot - iphone x - 2018-10-10 at 12 53 13

Floating Buttons After:
simulator screen shot - iphone x - 2018-10-10 at 12 52 33

Masked Transition Before:
simulator screen shot - iphone x - 2018-10-10 at 12 53 23

Masked Transition After:
simulator screen shot - iphone x - 2018-10-10 at 12 52 28

Additionally, I noticed in the Masked Transition example that the left/right fabs were swapped in their position so I fixed this. I also applied the safe area to the fullscreen transition example.

### CODE REVIEW

File: components/MaskedTransition/examples/MaskedTransitionTypicalUse.swift [hunk 1]
```diff
@@ -174,8 +184,48 @@ private class ModalViewController: UIViewController {
...
+    var topOffset: CGFloat = 0
+    var bottomOffset: CGFloat = 0
+    if #available(iOS 11.0, *) {
+      leftOffset += additionalSafeAreaInsets.left
+      rightOffset += additionalSafeAreaInsets.right
+      topOffset += additionalSafeAreaInsets.top
+      bottomOffset += additionalSafeAreaInsets.bottom
+    }
+
+    NSLayoutConstraint(item: view,
```
Comment (andrewoverton) [inline components/MaskedTransition/examples/MaskedTransitionTypicalUse.swift:208]: _Tip:_ Some of this layout logic could be extracted into another method

**Review by andrewoverton — APPROVED** [review]

File: components/MaskedTransition/examples/MaskedTransitionTypicalUse.swift (hunk 1 above)
Comment (rami-a) [reply components/MaskedTransition/examples/MaskedTransitionTypicalUse.swift:208]: Agreed and done!
