### PR TITLE
[Dialogs] Add designated initializer to MDCAlertController

### LINKED ISSUE #2775: [Dialogs] MDCAlertController has no designated initializer
### Overview
`MDCAlertController` has no designated initializer and has made both superclass designated initializers (`initWithNibName:bundle:` and `initWithCoder:`) unavailable. Calling `init` (the next designated initializer in the hierarchy) results in no initializer calls to `MDCAlertController`.

### Reproduction steps
1. Set a breakpoint in all initializers of `MDCAlertController`
1. Call `[[MDCAlertController alloc] init]`
1. Verify that one of the breakpoints is hit

### Version number
43.1.0

### PR DESCRIPTION
**Pull request by romoore**
If MDCAlertController does not override the superclasses designated
initializers, then its own designated initializer may never get called.
This can lead to problems.  Although the superclass designated
initializers are unavailable in MDCAlertController, they must still have
implementations.

Closes #2775

### CODE REVIEW

File: components/Dialogs/src/MDCAlertController.m [hunk 1]
```diff
@@ -124,6 +124,15 @@ - (nonnull instancetype)initWithTitle:(nullable NSString *)title
   return self;
 }
 
+- (nonnull instancetype)initWithNibName:(nullable NSString *)nibNameOrNil
+                                 bundle:(nullable NSBundle *)nibBundleOrNil {
+  return [self initWithTitle:nil message:nil];
+}
+
+- (nullable instancetype)initWithCoder:(nonnull NSCoder *)aDecoder {
```
Comment (ajsecord) [inline components/Dialogs/src/MDCAlertController.m]: Does initWithCoder still work with this change?

**Review by ajsecord — DISMISSED** [review]

File: components/Dialogs/src/MDCAlertController.m (hunk 1 above)
Comment (romoore) [reply components/Dialogs/src/MDCAlertController.m]: We can make `initWithCoder:` available to subclasses, but the current design won't allow encoding of the full state of the AlertController. Specifically, the actions array is not possible to encode since its members (`MDCAlertAction *`) have block properties. If we were to switch to a delegate structure, it would be possible to encode the actions.

**Review by ianegordon — APPROVED** [review]
LGTM!
