### PR TITLE
[Collections] Fixes SwipeToDismiss ability to swipe when not editing.

### LINKED ISSUE #1207: Catalog Swipe-To-Dismiss Example Does Not Enter Edit Mode
### Overview
The MDCCatalog "Swipe-to-Dismiss" example and "Swipe-to-Dismiss Section" example do not enter edit mode to allow for swipe to delete functionality.

### Reproduction steps
1.) Open MDCCatalog application
2.) Navigation to Collections
3.) Open "Swipe-to-Dismiss" example
4.) Cannot swipe to delete

### Version number
 - Found in 21.1.0

### Operating system and device
- iPhone 6S

### PR DESCRIPTION
**Pull request by chriscox**
Closes #1207, #1300, #1301.

### CODE REVIEW

File: components/Collections/src/private/MDCCollectionViewEditor.m [hunk 1]
```diff
@@ -344,11 +344,18 @@ - (BOOL)gestureRecognizer:(UIGestureRecognizer *)gestureRecognizer
...
-    return NO;
+  BOOL allowsSwipeToDismissItem = NO;
+  if ([_delegate respondsToSelector:@selector(collectionViewAllowsSwipeToDismissItem:)]) {
+    allowsSwipeToDismissItem = [_delegate collectionViewAllowsSwipeToDismissItem:_collectionView];
+  }
+
+  BOOL allowsSwipeToDismissSection = NO;
+  if ([_delegate respondsToSelector:@selector(collectionViewAllowsSwipeToDismissSection:)]) {
+    allowsSwipeToDismissSection =
+    [_delegate collectionViewAllowsSwipeToDismissSection:_collectionView];
```
Comment (ajsecord) [inline components/Collections/src/private/MDCCollectionViewEditor.m:355]: +4

**Review by ajsecord — APPROVED** [review]

File: components/Collections/src/private/MDCCollectionViewEditor.m (hunk 1 above)
Comment (chriscox) [reply components/Collections/src/private/MDCCollectionViewEditor.m:355]: Hey @ajsecord looks like this got merged before I could fix. Fixing in new PR here: https://github.com/material-components/material-components-ios/pull/1428
