### PR TITLE
[Feature Highlight] Fix feature highlight on iOS8 devices

### LINKED ISSUE #1272: [Feature Highlight] broken on iOS 8
Feature Highlights don't render correctly on iOS 8.

### PR DESCRIPTION
**Pull request by samnm**
Fixes #1272

Turns out `convertPoint:toView:` changed from iOS8 to iOS9, so we have to use `convertPoint:toCoordinateSpace:` on iOS8.

### CODE REVIEW

File: components/FeatureHighlight/src/MDCFeatureHighlightViewController.m [hunk 1]
```diff
@@ -102,8 +102,15 @@ - (void)loadView {
...
   [super viewWillAppear:animated];
 
-  CGPoint point = [_highlightedView.superview convertPoint:_highlightedView.center
-                                                    toView:_featureHighlightView];
+  CGPoint point;
+  if ([self deviceUsesCoordinateSpaces]) {
+    // We have to use coordinate spaces on iOS8 devices
+    point = [_highlightedView.superview convertPoint:_highlightedView.center
+                                   toCoordinateSpace:_featureHighlightView];
+  } else {
```
Comment (ianegordon) [inline components/FeatureHighlight/src/MDCFeatureHighlightViewController.m]: Won't all iOS version iOS 8+ will return YES for deviceUsersCoordinateSpaces?
If that is the case, this else clause will never be called.

**Review by ianegordon — CHANGES_REQUESTED** [review]

File: components/FeatureHighlight/src/MDCFeatureHighlightViewController.m (hunk 1 above)
Comment (samnm) [reply components/FeatureHighlight/src/MDCFeatureHighlightViewController.m]: Oops, you're right! Fixed.

**Comment by ianegordon** [comment]
Tested on iPhone 5 Sim 8.1 and 10.3.
LGTM.

**Review by ianegordon — APPROVED** [review]
