### PR TITLE
[Ripple] Fail the ripple gesture when other scroll view gestures are competing unless they are tap or long press gestures.

### LINKED ISSUE #4105: [Ink] MDCInkView behavior in a UIScrollView
From the internal bug:

> MDCInkView/MDCInkTouchController do not behave as expected when set for a collection view cell. Specifically, scrolling while highlighting and a panning gesture that goes outside the view don't show consistent behavior. 
>
> Two possible solutions, either this is the intended behavior by the MATERIAL SPEC and it is stated correctly in the documentation (maybe that should be in the platform adaption section), or, this is a bug affecting a wide range of iOS apps in production.

---

This is an internal issue. If you are a Googler, please visit [b/65101224](http://b/65101224) for more details.

---
#### Internal data
- Associated internal bug: [b/65101224](http://b/65101224)

### PR DESCRIPTION
**Pull request by yarneo**
There is a long standing issue where the Ink is sometimes invoked as a user scrolls/pans a collectionView/tableView/scrollView while tapping on an Ink view.

This property helps resolve this issue for clients who wish the ink/ripple only be invoked when there are no competing gestures that belong to a UIScrollView.

The only time a competing gesture recognizer of a UIScrollView doesn't fail the ripple is if the gesture itself is a TapGestureRecognizer or a LongPressGestureRecognizer.

This behavior is set as opt in due to taking a more cautious approach if a user believes there are competing gestures in their UIScrollView that shouldn't fail the ripple/ink from spreading. I will discuss with the team regarding this property to see what the team prefers in terms of having this an opt out instead.

resolves: #4105

| Before | After |
|:-------|:-----|
| beforeripplescrollingfix | afterripplescrollingfix |

### CODE REVIEW

**Comment by jverkoey** [comment]
The text "Helps resolve: #4105" appears to be considered by GitHub as closing the issue #4105. Is this PR intended to close #4105 or is it just related to it? If it's the latter, please update the wording so that GitHub won't automatically close the issue.

**Comment by jverkoey** [comment]
Please attach gifs showing the before/after behavior to the PR.

**Review by jverkoey — DISMISSED** [review]
Requesting gifs of the old/new behavior.

**Comment by yarneo** [comment]
Please see updated PR description for before/after GIFs

**Comment by yarneo** [comment]
Update to "resolves" rather than "help resolves" to remove ambiguity.

**Comment by jverkoey** [comment]
Yessss! This improvement is 🔥

File: components/Ripple/src/MDCRippleTouchController.h [hunk 1]
```diff
@@ -46,6 +46,16 @@
  */
 @property(nonatomic, strong, readonly, nonnull) UILongPressGestureRecognizer *gestureRecognizer;
 
+
+/**
+ If set to NO, the ripple gesture will fail and not be initiated if there are other competing
+ gestures that belong to a UIScrollView. This helps the ripple not be invoked if a user wants
+ to scroll but does so while tapping on a view that incorporates a ripple.
+
+ Defaults to YES.
```
Comment (jverkoey) [inline components/Ripple/src/MDCRippleTouchController.h:54]: What's an example of when we'd want this to be YES? Based on the UX shown in the videos I'd assume we'd want `NO` to be the default.

Comment (yarneo) [reply components/Ripple/src/MDCRippleTouchController.h:54]: The reason i defaulted to YES is because I want to take a cautious approach as I am not sure what gestures could be invoked with their UIScrollView or its subclasses, and if for instance a long press or a tap gesture recognizer is an added gesture, then the ripple will never be invoked as those gesture will cause the ripple gesture to fail. A good example is for instance the dragged behavior in UICollectionViews from iOS 9, which is a gesture that is part of the UICollectionView and will be invoked with a long press.

Therefore I would prefer the client to recognize if this behavior is desirable for them and opt in.

I have also tried to identify if the gesture is a long press or a tap and let the ripple gesture not fail, or only fail when there is a swipe or drag gesture, but I quickly found out that Apple uses a lot of internal gesture classes and I wouldn't want to depend on internal classes especially when they can easily be changed/updated by Apple.

Comment (jverkoey) [reply components/Ripple/src/MDCRippleTouchController.h:54]: I see; is this something where we can be more focused in indicating which gestures should cause the handler to cancel?

It sounds like we might be looking at too many gesture recognizers?

Comment (yarneo) [reply components/Ripple/src/MDCRippleTouchController.h:54]: Yeah, the system gestures just from UICollectionView I've been able to gather are called:
`_UISystemGestureGateGestureRecognizer`, `UIScreenEdgePanGestureRecognizer`, `UIScrollViewDelayedTouchesBeganGestureRecognizer`, `UIScrollViewPanGestureRecognizer`, `UILongPressGestureRecognizer`, `UIScrollViewPanGestureRecognizer`.

As you can see most of them are internal, and I think it would be unsafe to call them out in the method to try and be more focused. I could specifically choose known gesture recognizers like Tap and LongPress as gestures that shouldn't fail the ripple to help improve the behavior though if you think that makes sense.

Comment (jverkoey) [reply components/Ripple/src/MDCRippleTouchController.h:54]: > I could specifically choose known gesture recognizers like Tap and LongPress as gestures that shouldn't fail the ripple to help improve the behavior though if you think that makes sense.

If this has a chance of letting us make the desired behavior be the default then I think it's worth the exploration. This feels like a thing we could possibly iterate on independent of the ability to opt in to this behavior (which is my understanding of what this new property does).

**Review by jverkoey — APPROVED** [review]

**Comment by jverkoey** [comment]
Please consider updating the PR title + description to reflect the code changes.

File: components/Ripple/src/MDCRippleTouchController.h (hunk 1 above)
Comment (jverkoey) [reply components/Ripple/src/MDCRippleTouchController.h:54]: Filed https://github.com/material-components/material-components-ios/issues/7314 to track
