### PR TITLE
[FlexibleHeader] Fixed behavior for top layout guide and safe area insets.

### LINKED ISSUE #2471: [FlexibleHeader] Set additionalSafeAreaInsets in the parent VC
We currently only update the topLayoutGuide. For the safeAreaLayoutGuide to work as expected we need to set the additionalSafeAreaInsets in the parent view controller of the flexible header.

---
https://www.pivotaltracker.com/story/show/156806665

### PR DESCRIPTION
**Pull request by jverkoey**
This change introduces more predictable behavior surrounding topLayoutGuide and additionalSafeAreaInsets when using a flexible header (fhvc) container view controller (vc).

The purpose of this change is to support flexible header container view controllers with no-tracking-scroll-view based content.

## Background

Prior to this change, the fhvc was not adjusting the topLayoutGuide of the content vc when using a MDCFlexibleHeaderContainerViewController. The container vc was also not setting the bounds and autoresizing mask of the content view controller, leading to an oddly positioned content vc with no awareness of its occluding header. Many of our catalog examples are implemented with incorrect layout because of this, and I've seen a few examples of client usage that's attempting to work around this behavior.

The content vc's top layout guide is not being adjusted was because the flexible header view was always assuming that its parent vc was the vc whose topLayoutGuide should be updated. This is not the case when using a container vc - the flexible header vc is a sibling to the content vc, with the parent being the container view controller.

## Possible solutions

There were two paths to fixing this that I could see:

1. Make the fhvc a child of the content view controller. This would require zero changes to the fhvc, but may introduce behavioral changes to clients. This would require introducing a somewhat tricky behavioral flag (on change, we'd have to reparent the fhvc).
2. Allow the fhvc to keep updating the container vc's top layout guide, and constrain the container vc's top layout guide to the content vc's top layout guide.
2. Make it possible for the fhvc to target a specific view controller's top layout guide. This will also be a behavioral change, but a somewhat easier one to gate.

In any path, we need to also set the content vc's frame to match the container vc's bounds and set an autoresizing mask accordingly.

This PR represents option 3 because it represents the cleanest, most explicit mechanism for updating the correct top layout guide. We don't care if the container's top layout guide gets updated (option 2), and changing the fhvc hierarchy for containers is a fairly involved task that I feel could be tackled separately.

## This change

After this change, clients can enable a new flag on the container view controller to enable the desired topLayoutGuide behavior.

For example:

```swift
container.topLayoutGuideAdjustmentEnabled = true
```

This will ensure that the topLayoutGuide and additionalSafeAreaInsets of the content view controller are modified when the flexible header's height changes.

This runtime flag introduces new behavior and is off by default to avoid creating a breaking change. We will eventually enable this flag by default once all internal clients have migrated to the new behavior. The breaking behavior is primarily due to the fact that we are now properly setting the content view controller’s frame and autoresizing mask, which can affect client layouts.

This change is the first in a series of changes that will allow us to better support scroll view-less view controllers that otherwise have no way to position their content below the flexible header. Scroll view-less controllers are most commonly wrapped in a container view controller.

## Upcoming deprecations

This change marks `updateTopLayoutGuide` on MDCFlexibleHeaderViewController as to-be-deprecated because it exposes an implementation detail.

## Follow-up work

I will add this same flag and behavior to AppBar's container vc.

I will then enable this behavior in the MDCCatalog on a case-by-case basis so that we can fix layouts by using the top layout guide and/or safe area insets.

---

Closes: https://github.com/material-components/material-components-ios/issues/2471

### CODE REVIEW

File: components/FlexibleHeader/src/MDCFlexibleHeaderContainerViewController.m [hunk 1]
```diff
@@ -96,6 +91,39 @@ - (void)setContentViewController:(UIViewController *)contentViewController {
...
+
+- (void)setTopLayoutGuideAdjustmentEnabled:(BOOL)topLayoutGuideAdjustmentEnabled {
+  if (_topLayoutGuideAdjustmentEnabled == topLayoutGuideAdjustmentEnabled) {
+    return;
+  }
+  _topLayoutGuideAdjustmentEnabled = topLayoutGuideAdjustmentEnabled;
+
+  if (_topLayoutGuideAdjustmentEnabled) {
+    if ([self isViewLoaded] && [self.contentViewController isViewLoaded]) {
+      self.contentViewController.view.autoresizingMask = (UIViewAutoresizingFlexibleWidth
```
Comment (romoore) [inline components/FlexibleHeader/src/MDCFlexibleHeaderContainerViewController.m]: A few questions here:
* Do you need to update `translatesAutoresizingMaskIntoConstraints`?
* Is this safe to do if the contained VC has constraints against its view to some sibling view (or its container)?

File: components/FlexibleHeader/src/MDCFlexibleHeaderContainerViewController.m [hunk 2]
```diff
@@ -96,6 +91,39 @@ - (void)setContentViewController:(UIViewController *)contentViewController {
...
+                                                          | UIViewAutoresizingFlexibleHeight);
+      self.contentViewController.view.frame = self.view.bounds;
+    }
+
+    // The flexible header view controller, by default, will assume that it is a child view
+    // controller of the content view controller and modify its parent view controller's
+    // topLayoutGuide. With an App Bar container view controller, however, our flexible header's
+    // parent is the app bar container view controller instead. There does not appear to be a way to
+    // make two top layout guides constrain to one other
```
Comment (romoore) [inline components/FlexibleHeader/src/MDCFlexibleHeaderContainerViewController.m:120]: Why can you not target each of the top/bottom/leading/trailing of the layout guides in a series on constraints? Can you add a PR comment with the specific error/crash/effect?

File: components/FlexibleHeader/examples/FlexibleHeaderTopLayoutGuideExample.m [hunk 3]
```diff
@@ -132,28 +132,13 @@ - (void)viewWillAppear:(BOOL)animated {
   [self.navigationController setNavigationBarHidden:YES animated:animated];
 }
 
-- (void)viewWillLayoutSubviews {
```
Comment (romoore) [inline components/FlexibleHeader/examples/FlexibleHeaderTopLayoutGuideExample.m:135]: Don't you need to set `topLayoutGuideAdjustmentEnabled=YES` if you are removing the call to `updateTopLayoutGuide`? The header documentation for the property states that it *must* be called.

File: components/FlexibleHeader/src/MDCFlexibleHeaderViewController.m [hunk 4]
```diff
@@ -128,25 +121,18 @@ - (void)didMoveToParentViewController:(UIViewController *)parent {
   // If there is no tracking scroll view then we have to poke the header into sizing itself.
   if (!_headerView.trackingScrollView) {
     [_headerView sizeToFit];
+
```
Comment (romoore) [inline components/FlexibleHeader/src/MDCFlexibleHeaderViewController.m]: Nit/whitespace?

File: components/FlexibleHeader/src/MDCFlexibleHeaderViewController.m [hunk 5]
```diff
@@ -207,19 +199,94 @@ - (void)scrollViewWillEndDragging:(UIScrollView *)scrollView
   }
 }
 
+#pragma mark - Top layout guide support
+
+// Whenever the flexible header's height changes, we want to adjust the topLayoutGuide length
```
Comment (romoore) [inline components/FlexibleHeader/src/MDCFlexibleHeaderViewController.m]: Can you make this a comment block /* */ ? Any reason to keep it as a sequence of one-line comments?

File: components/FlexibleHeader/src/MDCFlexibleHeaderContainerViewController.m (hunk 2 above)
Comment (jverkoey) [reply components/FlexibleHeader/src/MDCFlexibleHeaderContainerViewController.m:120]: To be clear: I was unable to constrain two topLayoutGuides from two different view controllers. Doing so did not have any perceivable effect on the content view controller's top layout guide length.

File: components/FlexibleHeader/src/MDCFlexibleHeaderContainerViewController.m (hunk 1 above)
Comment (jverkoey) [reply components/FlexibleHeader/src/MDCFlexibleHeaderContainerViewController.m]: > Do you need to update translatesAutoresizingMaskIntoConstraints?

Might be good to ensure that our autoresizingMask is being respected, yes.

> Is this safe to do if the contained VC has constraints against its view to some sibling view (or its container)?

From the moment this view controller is assigned as a content view controller we take ownership over its layout. Any prior constraints added by the client would need to also be removed by the client prior to making this view controller be the content. I'll add docs.

File: components/FlexibleHeader/examples/FlexibleHeaderTopLayoutGuideExample.m (hunk 3 above)
Comment (jverkoey) [reply components/FlexibleHeader/examples/FlexibleHeaderTopLayoutGuideExample.m:135]: I've removed the documentation - it is no longer correct.

File: components/FlexibleHeader/src/MDCFlexibleHeaderViewController.m (hunk 4 above)
Comment (jverkoey) [reply components/FlexibleHeader/src/MDCFlexibleHeaderViewController.m]: Done.

File: components/FlexibleHeader/src/MDCFlexibleHeaderViewController.m (hunk 5 above)
Comment (jverkoey) [reply components/FlexibleHeader/src/MDCFlexibleHeaderViewController.m]: Done.

Comment (jverkoey) [reply components/FlexibleHeader/src/MDCFlexibleHeaderViewController.m]: Historically we've only used // comments in implementation files because `/** */` blocks otherwise get picked up in documentation generators. I've updated this to use a `/* */` block instead, but there isn't a particularly strong style requirement here.

Comment (romoore) [reply components/FlexibleHeader/src/MDCFlexibleHeaderViewController.m]: Ah, sorry. I didn't mean the doc comments, I was referring to C++-style block comments with a single star.

Comment (jverkoey) [reply components/FlexibleHeader/src/MDCFlexibleHeaderViewController.m]: Ah! Np I misread that as well.

**Comment by jverkoey** [comment]
Reviewers, I've updated the PR description with a bit more structure and background so that it's hopefully easier to understand what went in to this change.

**Review by jmdetloff — APPROVED** [review]
Feeling a little uneasy about some of the undocumented assumptions made regarding initializing and accessing the top layout guide constraint... but I suppose we were already doing this. Otherwise this looks like a good fix to me.

**Comment by jverkoey** [comment]
This had to be reverted in v55.1.0 due to introduced behavioral changes.
