### PR TITLE
[Tabs] Always call MDCTabBarControllerDelegate methods when a tab is tapped

### LINKED ISSUE #2154: [Tabs] MDCTabBarViewController should notify delegate when tapping already selected view controller
### Overview
MDCTabBarViewController will only call the  MDCTabBarViewController delegate methods -tabBarController:shouldSelectViewController: and -tabBarController:didSelectViewController: if the newly selected view controller is different than the currently selected view controller.  This behavior is different than the behavior of UITabBarController (since iOS 3.0).

Calling the delegate in the already-selected tab case allows the client to reset the tab to some default state, such as popping to the top of a deep navigation stack, or scrolling to the top of a scroll view, and in seen in apps such as Instagram, Google Translate, and Newsstand.

### Reproduction steps
Create a client application with MDCTabBarViewController and two more more tabs.  Tap on an already selected tab, and confirm that the delegate callbacks are not invoked.

### Version number
 35.3.0

### Operating system and device
iPhone SE / iOS 11

### Related issues
N/A

### PR DESCRIPTION
**Pull request by Icycle**
To more closely align with UITabBarController behavior, MDCTabBarController will invoke
the -tabBarController:shouldSelectViewController: and -tabBarController:didSelectViewController: delegate methods any time a tab is tapped, even if the selected view controller is unchanged.

closes #2154

### CODE REVIEW

File: components/Tabs/src/MDCTabBarViewController.h [hunk 1]
```diff
@@ -71,6 +71,9 @@ IB_DESIGNABLE
  If you provide this method, you can control whether tapping on a tab bar item actually
  switches to that viewController. If not provided, MDCTabBarViewController will always switch.
 
+ The tab bar controller calls this method regardless of whether the selected view controller
+ changed.
```
Comment (romoore) [inline components/Tabs/src/MDCTabBarViewController.h]: I think I misread this comment when I first went through it.  If I understand this PR correctly, I think the following phrasing might be clearer to readers.  Please feel free to edit. :)

> @note The tab bar controller will call this method even when the tapped tab bar item is the currently-selected tab bar item.

File: components/Tabs/src/MDCTabBarViewController.h [hunk 2]
```diff
@@ -80,6 +83,9 @@ IB_DESIGNABLE
  Called when the user taps on a tab bar item. Not called for programmatic selection.
  MDCTabBarViewController will call your delegate once it has responded to the user's tap
  by changing the selected view controller.
+
+ The tab bar controller calls this method regardless of whether the selected view controller
+ changed.
```
Comment (romoore) [inline components/Tabs/src/MDCTabBarViewController.h]: Same suggestion here:

> The tab bar controller will call this method even if the selected view controller was the same before and after selection.

**Review by romoore — CHANGES_REQUESTED** [review]

**Review by brianjmoore — APPROVED** [review]

File: components/Tabs/src/MDCTabBarViewController.h (hunk 1 above)
Comment (Icycle) [reply components/Tabs/src/MDCTabBarViewController.h]: I pulled this text directly from UITabBarController's docs, but I think your suggestion is clearer.  I'll update this PR in just a moment.

**Review by romoore — APPROVED** [review]
👍

**Review by ianegordon — APPROVED** [review]
LGTM.
@romoore, please merge when Travis is happy.  (You were here first 😄  )
