### PR TITLE
[TextFields] Clear button X value adjustment.

### LINKED ISSUE #2171: [TextFields] Clear button out of bounds
### Overview
Clear button out of bounds

### Reproduction steps
Text field clipped to bounds

### Version number
35.3.0

### Operating system and device
iPhone SE iOS 11.0

screen shot 2017-10-12 at 11 49 52 pm

### PR DESCRIPTION
**Pull request by willlarche**
Closes #2171 

Here are 3 screenshots with injected color to show it's now in bounds. Tested iPhone X, 7 Plus, 5s.

screen shot 2017-10-13 at 12 49 37 pm

screen shot 2017-10-13 at 12 49 26 pm
screen shot 2017-10-13 at 12 49 13 pm

5s has some antialiasing that's harsh but it's actually cleaner on the right side of the image.

### CODE REVIEW

**Review by jgunaratne — APPROVED** [review]

**Comment by willlarche** [comment]
Related, the hitzone of this button is not to spec. Created #2177 for that.

File: components/TextFields/src/private/MDCTextInputArt.h [hunk 1]
```diff
@@ -18,7 +18,7 @@
 
 #import "MaterialMath.h"
 
-static const CGFloat MDCTextInputClearButtonImageBuiltInPadding = 2.5f;
+static const CGFloat MDCTextInputClearButtonImageBuiltInPadding = 2.0f;
```
Comment (romoore) [inline components/TextFields/src/private/MDCTextInputArt.h:21]: Is this magic number based on anything?

**Review by romoore — APPROVED** [review]

**Comment by willlarche** [comment]
Yes! The standard padding around all icon assets (I was once told.) But
this adjustment is done by eye.
