### PR TITLE
[FlexibleHeader] Fix infinite recursion when VoiceOver is enabled.

### LINKED ISSUE #4744: [Catalog] Infinite loop/crash when opening "ActivityIndicator" example with VoiceOver
The catalog crashes (caused by blowing the stack in an infinite loop) when opening the "Start Demo" example in Activity Indicator using VoiceOver.

It looks like [there is custom VoiceOver code in MDCFlexibleHeaderView.m that is at least part of the problem](https://github.com/material-components/material-components-ios/blob/develop/components/FlexibleHeader/src/MDCFlexibleHeaderView.m#L1137).

|Stack trace|EXC_BAD_ACCESS screencap|
|-|-|
|screen shot 2018-08-08 at 12 57 43 pm|screen shot 2018-08-08 at 1 01 15 pm
|

## Reproduction steps
1. Turn on VoiceOver
1. Open the Catalog &rarr; Activity Indicator &rarr; Start Demo

## Device
Reproducible on iPad Mini 4/iOS 10.3.2

### PR DESCRIPTION
**Pull request by jverkoey**
The recursion was happening when both VoiceOver and observesTrackingScrollViewScrollEvents were enabled.

After this change, the VoiceOver fix added by 5dc67c88c06f11761769de1d0bae34ff2c657046 will use fhv_setContentOffset instead of directly setting the contentOffset so that we don't create an infinite KVO recursion.

I tested this fix on an iPhone SE running iOS 12. I verified that the crash existed before this change, and that it no longer crashed after this fix.

Closes https://github.com/material-components/material-components-ios/issues/4744

### CODE REVIEW

File: components/FlexibleHeader/src/MDCFlexibleHeaderView.m [hunk 1]
```diff
@@ -1140,7 +1140,7 @@ - (void)fhv_contentOffsetDidChange {
       // focusing.
       CGPoint offset = self.trackingScrollView.contentOffset;
       offset.y = MAX(offset.y, -self.maximumHeight);
-      self.trackingScrollView.contentOffset = offset;
```
Comment (romoore) [inline components/FlexibleHeader/src/MDCFlexibleHeaderView.m:1143]: So will the scrollview's contentOffset be mismatched with what the FHV thinks it is after this? If the user turns off VoiceOver after scrolling, is the FHV going to be offset incorrectly or anything like that?

**Review by romoore — APPROVED** [review]
LGTM, just some questions since I don't understand the FHV too well.

File: components/FlexibleHeader/src/MDCFlexibleHeaderView.m (hunk 1 above)
Comment (jverkoey) [reply components/FlexibleHeader/src/MDCFlexibleHeaderView.m:1143]: The FHV always reads the scroll view’s content offset directly, so changing it like so here won’t affect the FHV’s future readings.

Comment (romoore) [reply components/FlexibleHeader/src/MDCFlexibleHeaderView.m:1143]: Thanks! I guess I was confused because it looked like there were 2 different mechanisms for updating the FHV's contentOffset.
